// 이 파일은 tools/build-articles.py 가 만듭니다. 직접 고치지 마세요.
// 글은 content/articles-en/*.md 에서 고칩니다.
const ARTICLES = [
  { slug: "open-image-model-license", title: "A free image model that even does transparent backgrounds. Can you use it for work?", desc: "While companies shift to cheap open models, Alibaba's new image model Qwen-Image-2.1 shut the door on commercial use. The difference between being able to download a model and being allowed to use it for work.", date: "2026-09-28", tag: "AI Design", min: 4 },
  { slug: "ai-price-cut-week", title: "AI got half price in a week. Will design tools follow?", desc: "On September 22, Opus 5.5, GPT-6 Sol and Luna all launched on the same day and the price sheets changed dramatically. What that means, in numbers, for the credits and subscriptions designers pay for.", date: "2026-09-27", tag: "AI Design", min: 4 },
  { slug: "claude-fable-5-1-vs-gpt-6-astra", title: "Claude Fable 5.1 vs GPT-6 Astra, by the numbers", desc: "Two frontier models released two days apart. Official specs, third-party evaluations and early reactions from designers, side by side with sources.", date: "2026-09-26", tag: "AI Design", min: 5 },
  { slug: "ai-design-tools-in-practice", title: "Why thirty AI drafts don't make the work any shorter", desc: "Exploration and mass production go to AI; direction and final checks stay with people. A boundary I only saw after months of use.", date: "2026-09-25", tag: "AI Design", min: 4 },
  { slug: "describing-design-style", title: "Putting \"make it feel right\" into words", desc: "Whether it's a client or a prompt box, you end up explaining style in words. A way of breaking style into six layers.", date: "2026-09-24", tag: "Design", min: 4 },
  { slug: "how-to-collect-references", title: "The references we save and never open again", desc: "Twenty-plus boards, and still I start every project by searching from scratch. How to collect references you can actually pull back out.", date: "2026-09-23", tag: "Design", min: 3 },
  { slug: "korean-design-community-map", title: "Where Korean designers talk to each other", desc: "When you want to read, when you want to show your work, when you need an answer fast. Korea's design communities, sorted by what they're good for.", date: "2026-09-22", tag: "Community", min: 3 },
  { slug: "ai-image-commercial-use", title: "Can you use AI-generated images in client work?", desc: "Copyright, terms of service, lookalikes, contracts. What to check in practice, in order. Written from Korea, with the US for comparison.", date: "2026-09-21", tag: "AI Design", min: 4 },
];
