// 이 파일은 tools/build-articles.py 가 만듭니다. 직접 고치지 마세요.
// 글은 content/articles-en/*.md 에서 고칩니다.
const ARTICLES = [
  { slug: "ai-design-week-1007", title: "Last week, AI design tools moved toward less luck", desc: "Six AI and design stories from September 30 to October 6, on one page. The whole store, the rules, what to edit, the order of shots: what was left to luck is turning into something people decide. With numbers on how much designers use AI.", date: "2026-10-07", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "kling-4-keyframes", title: "AI video starts taking a storyboard. Kling 4.0's ten keyframes", desc: "Kling 4.0 takes 30 seconds, 10 keyframes and 15 references in one generation. It moves from giving just a first and last frame to laying out the flow of a scene yourself. Here's what changes and what isn't out yet, in a diagram and a table.", date: "2026-10-06", tag: "AI Design", min: 3, views: ["ai", "tool"] },
  { slug: "chatgpt-image-generation-ads", title: "While ChatGPT draws your picture, an ad appears beside it", desc: "On October 5, OpenAI announced image ads that appear in ChatGPT's image generation screen. Here's the eight months from text ads to image ads, and what it means for designers, both the new work and the things to watch out for.", date: "2026-10-05", tag: "AI Design", min: 3, views: ["ai", "tool"] },
  { slug: "instructmesh-ai-3d-print", title: "Four in five AI-made 3D models can't be printed as they are", desc: "MIT researchers released InstructMesh, a tool for fixing AI-generated 3D models before printing. About 80% of generated models had structural flaws, and novices fixed about 90% with the tool. Here's how the fixing works and what to check before you print.", date: "2026-10-04", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "image-ai-edit-not-reroll", title: "Edit, don't re-roll. The week image AI turned toward editing", desc: "Ideogram 4.5 on September 30, FLUX 3 Image on October 2. This week's two image models led with \"change one spot only\" rather than prettier pictures. Here's box-first layout and price by size, in diagrams and numbers.", date: "2026-10-03", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "design-md-for-ai", title: "DESIGN.md, one file that hands your design rules to AI", desc: "As AI makes more of our drafts and code, where you write down your rules starts to matter. I wrote this site's rules in Google's DESIGN.md format and ran the official checker on it. Here's what it caught.", date: "2026-10-02", tag: "AI Design", min: 5, views: ["ai", "tool"] },
  { slug: "shopify-canvas-sidekick", title: "Shopify Canvas lays out your whole store at once and lets you edit it with AI", desc: "Shopify's Canvas, launched October 1, puts every page of a store on one surface. You click to edit, or tell Sidekick what you want. Here's what changed and what doesn't work yet, with diagrams and a table.", date: "2026-10-01", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "openai-devday-2026-designers", title: "Canva, Figma and Adobe move into ChatGPT. What designers should take from DevDay", desc: "OpenAI's DevDay brought more than twenty announcements. Here are only the ones that touch design work, laid out with diagrams and numbers.", date: "2026-09-30", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "claude-sonnet-5-5-design", title: "Claude Sonnet 5.5 leads with \"an eye for design\", and the mid-priced tier changes", desc: "Anthropic's Sonnet 5.5, released September 28, put design sense front and center. Same price, faster work. Plus what happened when someone had it build a one-page site, in numbers.", date: "2026-09-29", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "open-image-model-license", title: "A free image model that even does transparent backgrounds. Can you use it for work?", desc: "While companies shift to cheap open models, Alibaba's new image model Qwen-Image-2.1 shut the door on commercial use. The difference between being able to download a model and being allowed to use it for work.", date: "2026-09-28", tag: "AI Design", min: 4, views: ["ai", "asset"] },
  { slug: "ai-price-cut-week", title: "AI got half price in a week. Will design tools follow?", desc: "On September 22, Opus 5.5, GPT-6 Sol and Luna all launched on the same day and the price sheets changed dramatically. What that means, in numbers, for the credits and subscriptions designers pay for.", date: "2026-09-27", tag: "AI Design", min: 4, views: ["ai", "tool"] },
  { slug: "claude-fable-5-1-vs-gpt-6-astra", title: "Claude Fable 5.1 vs GPT-6 Astra, by the numbers", desc: "Two frontier models released two days apart. Official specs, third-party evaluations and early reactions from designers, side by side with sources.", date: "2026-09-26", tag: "AI Design", min: 5, views: ["ai", "tool"] },
  { slug: "ai-design-tools-in-practice", title: "Why thirty AI drafts don't make the work any shorter", desc: "Exploration and mass production go to AI; direction and final checks stay with people. A boundary I only saw after months of use.", date: "2026-09-25", tag: "AI Design", min: 4, views: ["ai", "tool", "dev"] },
  { slug: "describing-design-style", title: "Putting \"make it feel right\" into words", desc: "Whether it's a client or a prompt box, you end up explaining style in words. A way of breaking style into six layers.", date: "2026-09-24", tag: "Design", min: 4, views: ["ai", "styles", "glossary"] },
  { slug: "how-to-collect-references", title: "The references we save and never open again", desc: "Twenty-plus boards, and still I start every project by searching from scratch. How to collect references you can actually pull back out.", date: "2026-09-23", tag: "Design", min: 3, views: ["uiux", "graphic", "styles"] },
  { slug: "korean-design-community-map", title: "Where Korean designers talk to each other", desc: "When you want to read, when you want to show your work, when you need an answer fast. Korea's design communities, sorted by what they're good for.", date: "2026-09-22", tag: "Community", min: 3, views: ["job", "community", "creator"] },
  { slug: "ai-image-commercial-use", title: "Can you use AI-generated images in client work?", desc: "Copyright, terms of service, lookalikes, contracts. What to check in practice, in order. Written from Korea, with the US for comparison.", date: "2026-09-21", tag: "AI Design", min: 4, views: ["freelance", "ai"] },
];
