/* =========================================================
   디자인 허브 영문판 데이터 (/en/)
   - js/data.js 의 한국어 내용을 영어로 옮긴 것입니다. data.js 뒤에 불러옵니다.
   - 사이트는 주소(url), 스타일은 영문 이름(en), 트렌드와 용어는 한국어 이름으로 짝을 찾습니다.
   - 여기에 없는 항목은 영문판에서 한국어 그대로 보입니다.
     사이트를 새로 넣으면 SITES_EN 에도 한 줄 넣어 주세요. (python3 tools/build-en.py 를 돌리면 빠진 것을 알려 줍니다)
   ========================================================= */

const EN = {
  categories: {
    uiux:      { label: "UI/UX", desc: "App and web screens, user flows, landing page inspiration" },
    graphic:   { label: "Graphic & Branding", desc: "Posters, logos, packaging, branding and editorial design" },
    color:     { label: "Color", desc: "Palette generators, gradients, contrast checkers" },
    typo:      { label: "Type & Fonts", desc: "Free fonts, font pairing, typography references" },
    asset:     { label: "Icons & Assets", desc: "Icons, illustrations, photos and video footage" },
    mockup:    { label: "Mockups", desc: "Device, print, packaging and apparel mockups, mockup generators" },
    dev:       { label: "Design & Code", desc: "Design systems, platform guidelines, building interactions" },
    tool:      { label: "Design Tools", desc: "Tools for making, collaborating, prototyping and everyday utilities" },
    freelance: { label: "Freelance", desc: "Freelance marketplaces, contracts and fee standards" },
    job:       { label: "Jobs", desc: "Design jobs, company info and careers" },
    ai:        { label: "AI", desc: "Image, video and UI generation, AI coding tools" },
    community: { label: "Community & Media", desc: "Articles, newsletters, courses and designer communities" },
    creator:   { label: "Creators", desc: "Design YouTubers, Instagram curators and podcasts" },
  },
  aiSubs: {
    "LLM · 대화형": "Chat assistants",
    "이미지 생성": "Image generation",
    "이미지 편집 · 업스케일": "Image editing & upscaling",
    "영상 생성 · 편집": "Video generation & editing",
    "오디오 · 음성": "Audio & voice",
    "UI · 코드 생성": "UI & code generation",
    "문서 · 프레젠테이션": "Docs & presentations",
    "리서치 · 모델 허브": "Research & model hubs",
  },
  tags: { "한국": "Korean", "무료": "Free", "유료": "Paid", "AI": "AI", "유튜브": "YouTube", "인스타그램": "Instagram", "팟캐스트": "Podcast" },
  glossaryGroups: { typo: "Typography", print: "Editorial & Print", color: "Color", brand: "Graphic & Branding", ui: "UI Design", ux: "UX & Research", dev: "Working with Developers" },
  trendSources: {
    "Pantone Color of the Year 2026": "Pantone's official Color of the Year page",
    "Behance Trends": "Behance's curated trend gallery",
    "Pinterest Predicts": "Pinterest's annual trend report based on search data",
  },
};

/* 사이트: url -> [영문 이름(한국어 이름일 때만), 설명] */
const SITES_EN = {
  "https://mobbin.com": [null, "A UI archive of real app and web screens, captured as complete flows. Screen-level search is excellent."],
  "https://refero.design": [null, "Search UI patterns from real products by component or page type."],
  "https://dribbble.com": [null, "Designers' \"shots\" from around the world. Good for keeping up with visual trends."],
  "https://www.behance.net": [null, "Adobe's portfolio platform. Full projects rather than single shots."],
  "https://www.awwwards.com": [null, "The best-known web design awards. Picks a standout, interaction-heavy site every day."],
  "https://www.gdweb.co.kr": ["GDWEB", "Korean web and app design awards. Handy when you need references from Korean company sites."],
  "https://www.dbcut.com": ["DBCUT", "A Korean web design reference collection, browsable by industry and style."],
  "https://land-book.com": [null, "Landing page gallery with solid filters for industry, style and color."],
  "https://www.lapa.ninja": [null, "Landing page inspiration, plus free UI kits and books."],
  "https://recent.design": ["Recent (formerly Godly)", "A tight curation of tasteful websites. Renamed from Godly."],
  "https://www.siteinspire.com": [null, "A showcase of clean, refined websites, filterable by style, type and subject."],
  "https://httpster.net": [null, "A gallery of trendy, experimental websites."],
  "https://minimal.gallery": [null, "Minimal websites only."],
  "https://www.darkmodedesign.com": [null, "Dark mode website references, nothing else."],
  "https://saaslandingpage.com": [null, "SaaS landing page examples, organized by section and type."],
  "https://nicelydone.club": [null, "UI patterns and flows from SaaS products."],
  "https://pageflows.com": [null, "User flows like onboarding and checkout, recorded as video."],
  "https://www.pttrns.com": [null, "A classic among mobile app UI pattern libraries."],
  "https://screensdesign.com": [null, "App Store screenshots alongside the real in-app UI flows."],
  "https://collectui.com": [null, "Dribbble shots sorted by UI element: login, 404, dashboard and more."],
  "https://www.designspells.com": [null, "Small UI details and interactions that make people smile."],
  "https://www.footer.design": [null, "Website footers, and only footers."],
  "https://www.navbar.gallery": [null, "Navigation bar design references."],
  "https://www.curated.design": [null, "Trendy web design curation with type and style filters."],
  "https://muz.li": [null, "A design inspiration feed you can open in every new tab via its Chrome extension."],
  "https://ui-patterns.com": [null, "A pattern library that frames each UI pattern as a problem and its solution."],
  "https://lawsofux.com": [null, "Hick's law, Fitts's law and other UX psychology principles, one card each."],
  "https://growth.design": [null, "Comic-style case studies that break down the UX of well-known products."],
  "https://www.checklist.design": [null, "Design checklists for pages and components."],
  "https://www.nngroup.com": [null, "The authority on UX research. Deep archive of heuristics and research articles."],
  "https://kr.pinterest.com": [null, "Image-based inspiration boards. Essential for moodboards."],
  "https://notefolio.net": ["Notefolio", "Korea's largest designer portfolio platform. Graphic, branding and illustration work."],
  "https://www.are.na": [null, "An ad-free tool for research and curation. Browse channels made by designers."],
  "https://savee.com": [null, "A visual inspiration saver with a tasteful image feed."],
  "https://www.cosmos.so": [null, "A curation-first moodboard platform with no algorithmic feed."],
  "https://www.designspiration.com": [null, "Graphic design inspiration search. You can search by color."],
  "https://www.itsnicethat.com": [null, "A UK magazine covering work across the creative industries."],
  "https://www.underconsideration.com/brandnew/": [null, "A branding blog that reviews corporate logo and identity redesigns."],
  "https://bpando.org": [null, "An archive that covers branding and packaging projects in depth."],
  "https://thedieline.com": [null, "The packaging design magazine."],
  "https://packagingoftheworld.com": [null, "A gallery of packaging design from around the world."],
  "https://www.logobook.com": [null, "An archive of classic logos, sorted by form and industry."],
  "https://www.logolounge.com": [null, "Annual logo trend reports and a huge logo database."],
  "https://brandingstyleguides.com": [null, "A collection of real brand guideline documents."],
  "https://www.typographicposters.com": [null, "An archive of typography-driven posters."],
  "https://www.adsoftheworld.com": [null, "An archive of ad campaigns from around the world."],
  "https://abduzeedo.com": [null, "An inspiration blog for graphic design, branding and illustration."],
  "https://visuelle.co.uk": [null, "A curation blog focused on editorial and branding design."],
  "https://bookcoverarchive.com": [null, "An archive of book cover design."],
  "https://coolors.co": [null, "Hit the spacebar to generate palettes fast. Also extracts colors from images and checks contrast."],
  "https://color.adobe.com": [null, "Build harmonious palettes on a color wheel. The Trends and Explore tabs are useful too."],
  "https://colorhunt.co": [null, "Curated four-color palettes, sortable by popular and trending."],
  "https://www.realtimecolors.com": [null, "Try a palette on a real web UI as you pick it."],
  "https://www.happyhues.co": [null, "Pick a palette by seeing it applied to an entire page."],
  "https://www.khroma.co": [null, "An AI color tool that learns your taste and recommends palettes."],
  "https://huemint.com": [null, "AI-generated palettes for brands, websites and gradients."],
  "http://colormind.io": [null, "A deep-learning palette generator. Lock some colors and let it suggest the rest."],
  "https://paletton.com": [null, "A classic color-theory scheme generator."],
  "https://uicolors.app": [null, "Turns one color into a Tailwind-style 50–950 shade scale."],
  "https://www.radix-ui.com/colors": [null, "A 12-step color scale system designed with accessibility in mind."],
  "https://material-foundation.github.io/material-theme-builder/": [null, "Generates dynamic color themes based on Google's Material 3."],
  "https://webaim.org/resources/contrastchecker/": [null, "Checks whether a color pair passes WCAG contrast requirements."],
  "https://oklch.com": [null, "A picker for the perceptually uniform OKLCH color space. Useful for modern CSS color work."],
  "https://colorleap.app": [null, "Historical color palettes, from antiquity to today."],
  "https://picular.co": [null, "Color search: type a word and it pulls colors from related images."],
  "https://mycolor.space": [null, "Enter one color and get a range of schemes and gradients at once."],
  "https://www.grabient.com": [null, "Make CSS gradients and copy the code."],
  "https://grainient.supply": [null, "Grainy and soft gradients, animated gradients and AI backgrounds. Build your own with shaders or grab the free packs."],
  "https://www.colorsandfonts.com": [null, "Color palettes, gradients and font pairings in one place."],
  "https://encycolorpedia.kr": [null, "An encyclopedia of color codes: HEX, RGB, CMYK and paint matches."],
  "https://www.pantone.com": [null, "The Pantone color system and Color of the Year."],
  "https://noonnu.cc": ["Noonnu", "Free Korean fonts cleared for commercial use, with the license scope shown at a glance."],
  "https://fonts.google.com": [null, "The standard for open-source web fonts, including many Korean typefaces."],
  "https://github.com/orioncactus/pretendard": [null, "The free Korean font most widely used in Korean UI design."],
  "https://www.sandollcloud.com": ["Sandoll Cloud", "Sandoll's font subscription service. The largest catalog of commercial Korean fonts."],
  "https://hangeul.naver.com": ["Naver Hangeul Fonts", "Naver's free Korean fonts, including Nanum and MaruBuri."],
  "https://fonts.adobe.com": [null, "The font library included with Creative Cloud."],
  "https://www.fontshare.com": [null, "High-quality free fonts from Indian Type Foundry."],
  "https://uncut.wtf": [null, "A catalog of hand-picked, contemporary free fonts."],
  "https://velvetyne.fr": [null, "An experimental open-source type foundry."],
  "https://www.freefaces.gallery": [null, "A gallery for browsing free fonts by style."],
  "https://fontesk.com": [null, "A broad collection of free and paid fonts."],
  "https://fontsinuse.com": [null, "An archive showing how typefaces are actually used in real work."],
  "https://www.typewolf.com": [null, "Font recommendations, pairings and alternatives, well organized."],
  "https://www.fontpair.co": [null, "Google Fonts pairing suggestions."],
  "https://typ.io": [null, "Font pairings spotted on real websites."],
  "https://fontjoy.com": [null, "Generates font pairings with deep learning."],
  "https://typescale.com": [null, "A calculator for typographic scales."],
  "https://wordmark.it": [null, "Preview a phrase in every font installed on your computer at once."],
  "https://www.myfonts.com/pages/whatthefont": [null, "Identifies the font in an image."],
  "https://lucide.dev": [null, "A clean, consistent open-source icon set with packages for React and more."],
  "https://heroicons.com": [null, "SVG icons from the Tailwind team."],
  "https://phosphoricons.com": [null, "A flexible icon family in six weights."],
  "https://tabler.io/icons": [null, "Over 5,000 free SVG icons."],
  "https://icon-sets.iconify.design": [null, "Search over 200,000 icons in one place."],
  "https://feathericons.com": [null, "A classic set of simple line icons."],
  "https://thenounproject.com": [null, "A huge library of pictograms and icons."],
  "https://www.flaticon.com": [null, "A large icon site with plenty of icon packs by style."],
  "https://www.svgrepo.com": [null, "Free SVG icons and vectors."],
  "https://3dicons.co": [null, "Open-source 3D icons, with Figma and Blender files."],
  "https://lordicon.com": [null, "An animated icon library."],
  "https://lottiefiles.com": [null, "A marketplace and editor for Lottie vector animations."],
  "https://undraw.co": [null, "Open-source illustrations you can recolor."],
  "https://storyset.com": [null, "Customizable illustrations from Freepik."],
  "https://www.humaaans.com": [null, "A mix-and-match library of people illustrations."],
  "https://www.opendoodles.com": [null, "Free hand-drawn style illustrations."],
  "https://blush.design": [null, "Compose illustrations from different artists' sets."],
  "https://unsplash.com": [null, "The go-to source for high-quality free photos."],
  "https://www.pexels.com": [null, "Free photos and videos."],
  "https://www.freepik.com": [null, "An all-in-one source for vectors, photos, PSDs and mockups."],
  "https://mixkit.co": [null, "Free video clips, music and sound effects."],
  "https://coverr.co": [null, "Free video footage for website backgrounds."],
  "https://www.mockupworld.co": [null, "Free PSD mockups."],
  "https://www.ls.graphics": [null, "High-quality mockups, 3D illustrations and UI kits."],
  "https://shots.so": [null, "Turns screenshots into polished mockups instantly."],
  "https://contentcore.xyz": [null, "Build 3D device mockups and motion templates in the browser, then export as images or MP4."],
  "https://placeit.net": [null, "Envato's in-browser mockup generator for devices, apparel and print. Also has logo and video templates."],
  "https://mockuuups.studio": [null, "Drop in a screenshot and it's placed into 5,200+ scene mockups."],
  "https://artboard.studio": [null, "An online mockup editor that also handles animated scenes."],
  "https://rotato.app": [null, "A Mac app that spins and animates 3D device mockups and exports video."],
  "https://previewed.app": [null, "Turns app screenshots into 3D mockups and App Store images."],
  "https://deviceframes.com": [null, "Rotate device frames in 3D to make mockup images."],
  "https://angle.sh": [null, "7,600+ device mockups for Figma, Sketch and XD."],
  "https://mockey.ai": [null, "An AI mockup generator with around 30,000 templates."],
  "https://yellowimages.com": [null, "A mockup marketplace especially strong in packaging and product objects."],
  "https://mockupmark.com": [null, "Apparel mockups like T-shirts and hoodies, made by photo compositing."],
  "https://mockups-design.com": [null, "High-quality PSD mockups, free to download."],
  "https://mockupden.com": [null, "A search site that gathers free and paid mockups from across the web."],
  "https://unblast.com": [null, "Free mockups, fonts and icons."],
  "https://pixelbuddha.net": [null, "Mockups, fonts and graphics, free or via membership."],
  "https://www.pixeden.com": [null, "Mockups, templates and icons. Free resources plus the Pixeden Club membership."],
  "https://haikei.app": [null, "A generator for SVG backgrounds like waves and blobs."],
  "https://bookofshapes.com": [null, "Generative SVG patterns (grids, noise, isometric and more) with adjustable parameters. Free for commercial use, no attribution needed."],
  "https://www.figma.com/community": [null, "Duplicate UI kits, icons, templates and plugins for free."],
  "https://www.untitledui.com": [null, "The most widely used Figma UI kit. A free version is available."],
  "https://m3.material.io": [null, "Google's Material Design guidelines and components."],
  "https://developer.apple.com/design/human-interface-guidelines/": [null, "Human Interface Guidelines for iOS, macOS and other Apple platforms."],
  "https://www.krds.go.kr": ["KRDS (Korea Digital Government UI/UX)", "Korea's UI/UX guidelines for digital government services. Required reading for public-sector projects in Korea."],
  "https://designsystem.line.me": [null, "LINE's public design system."],
  "https://atlassian.design": [null, "A textbook example of a well-documented design system."],
  "https://shopify.dev/docs/api/polaris": [null, "Shopify's design system. The content guidelines are especially good."],
  "https://carbondesignsystem.com": [null, "IBM's open-source design system."],
  "https://ant.design": [null, "An enterprise UI design language with React components."],
  "https://designsystemsrepo.com": [null, "A collection of public design systems."],
  "https://component.gallery": [null, "Compare the same component across many design systems."],
  "https://ui.shadcn.com": [null, "Copy-and-paste React components. Practically the default for web UI lately."],
  "https://tailwindcss.com": [null, "A utility-class CSS framework."],
  "https://www.radix-ui.com": [null, "Accessible headless UI components."],
  "https://storybook.js.org": [null, "Build and document UI components in isolation."],
  "https://zeroheight.com": [null, "A documentation platform for design systems."],
  "https://www.supernova.io": [null, "Design token management and code sync."],
  "https://zeplin.io": [null, "A design-to-development handoff tool."],
  "https://tympanus.net/codrops/": [null, "Demos and tutorials for advanced web interaction and animation."],
  "https://codepen.io": [null, "A playground for sharing front-end code snippets."],
  "https://gsap.com": [null, "The standard web animation library."],
  "https://motion.dev": [null, "A modern animation library for React and JS (formerly Framer Motion)."],
  "https://shaders.com": [null, "Design web shader effects in an editor and drop them in as components. Free to create; paid for production use."],
  "https://threejs.org": [null, "The web 3D library. Its examples gallery doubles as inspiration."],
  "https://easings.net": [null, "An easing function cheat sheet."],
  "https://cubic-bezier.com": [null, "A visual editor for CSS cubic-bezier easing curves."],
  "https://animista.net": [null, "Click through CSS animations, pick one and copy the code."],
  "https://developer.mozilla.org/ko/": [null, "The reference docs for HTML, CSS and JS."],
  "https://css-tricks.com": [null, "Articles and guides on CSS techniques."],
  "https://caniuse.com": [null, "Check browser support for CSS and JS features."],
  "https://www.w3.org/WAI/WCAG22/quickref/": [null, "A quick reference for the web accessibility guidelines."],
  "https://responsively.app": [null, "A browser that shows many device screens at once for responsive testing."],
  "https://www.figma.com": [null, "The standard tool for UI design, prototyping and collaboration."],
  "https://www.framer.com": [null, "A no-code builder: design a website like a canvas and publish it directly."],
  "https://webflow.com": [null, "A visual web builder with a built-in CMS."],
  "https://www.protopie.io": [null, "A Korean-made prototyping tool for advanced interactions without code."],
  "https://rive.app": [null, "A tool for interactive vector animation."],
  "https://spline.design": [null, "A 3D design tool for the web. Makes interactive 3D approachable."],
  "https://www.adobe.com/kr/": [null, "Photoshop, Illustrator, InDesign and the rest."],
  "https://www.affinity.studio": [null, "The Adobe alternative. Became free after Canva acquired it in 2025."],
  "https://www.canva.com": [null, "Template-based design made easy."],
  "https://www.photopea.com": [null, "A free Photoshop alternative that runs in the browser."],
  "https://procreate.com": [null, "The iPad drawing and painting app."],
  "https://www.blender.org": [null, "Free, open-source 3D software."],
  "https://glyphsapp.com": [null, "A font editor for Mac, widely used for Korean fonts too."],
  "https://fontforge.org": [null, "A free, open-source font editor."],
  "https://miro.com": [null, "An online whiteboard for workshops and research synthesis."],
  "https://whimsical.com": [null, "Quick wireframes, flowcharts and mind maps."],
  "https://excalidraw.com": [null, "A free diagram tool with a hand-drawn look."],
  "https://www.notion.com": [null, "Docs and project management. Also works as a portfolio page."],
  "https://maze.co": [null, "Prototype usability testing and surveys."],
  "https://contentsquare.com/hotjar/": [null, "Heatmaps and session recordings of real user behavior. Now part of Contentsquare."],
  "https://tinypng.com": [null, "Compresses PNG, JPG and WebP images."],
  "https://squoosh.app": [null, "Google's in-browser image compression and conversion tool."],
  "https://www.remove.bg": [null, "Removes image backgrounds automatically."],
  "https://screen.studio": [null, "Polished screen recordings with automatic zoom and motion (Mac)."],
  "https://cleanshot.com": [null, "Screenshots and screen recording for Mac."],
  "https://kmong.com": ["Kmong", "Korea's largest freelance marketplace. The design category is its busiest."],
  "https://soomgo.com": ["Soomgo", "A Korean platform that matches you with pros through quote requests."],
  "https://www.wishket.com": ["Wishket", "A Korean outsourcing platform for IT and design projects, often larger ones."],
  "https://www.freemoa.net": ["Freemoa", "A Korean freelance project matching platform."],
  "https://www.loud.kr": ["Loud Sourcing", "A Korean design contest platform for logos, naming and packaging."],
  "https://www.elancer.co.kr": ["Elancer", "Korean IT freelancer matching, with many on-site projects."],
  "https://www.wanted.co.kr/gigs": ["Wanted Gigs", "Wanted's freelance and gig project matching (Korea)."],
  "https://www.designdb.com": ["DesignDB (KIDP)", "Official Korean reference for design fee standards and standard contracts."],
  "https://www.upwork.com": [null, "A global freelance platform for working with international clients."],
  "https://www.fiverr.com": [null, "A global freelance marketplace where services are sold as packages."],
  "https://www.toptal.com": [null, "Premium matching with a screened pool of top freelancers."],
  "https://99designs.com": [null, "Design contests and one-to-one projects."],
  "https://contra.com": [null, "A commission-free platform for independent freelancers, with a built-in portfolio."],
  "https://www.wanted.co.kr": ["Wanted", "Korea's hub for tech and startup hiring. Lots of product designer openings."],
  "https://www.saramin.co.kr": ["Saramin", "One of Korea's biggest job sites."],
  "https://www.jobkorea.co.kr": ["JobKorea", "One of Korea's biggest job sites."],
  "https://www.rocketpunch.com": ["Rocketpunch", "Korean startup jobs and business networking."],
  "https://www.designerjob.co.kr": ["DesignerJob", "A Korean job board just for designers."],
  "https://www.rallit.com": ["Rallit", "Incruit's Korean job platform for tech and design roles."],
  "https://www.rememberapp.co.kr": ["Remember", "Experienced-hire offers in Korea, built on a business card app."],
  "https://www.jobplanet.co.kr": ["JobPlanet", "Korean company reviews and salary data. Check the culture before you apply."],
  "https://www.catch.co.kr": ["Catch", "Korean company info, job listings and job-prep resources."],
  "https://www.teamblind.com/kr": ["Blind", "An anonymous community for employees. Useful for insider views on a company."],
  "https://kr.indeed.com": ["Indeed Korea", "The Korean edition of the global job search engine."],
  "https://www.linkedin.com/jobs/": [null, "Jobs at global and international companies."],
  "https://dribbble.com/jobs": [null, "A design job board with international listings."],
  "https://www.behance.net/joblist": [null, "Job listings on Behance."],
  "https://workingnotworking.com": [null, "A talent and hiring platform for creatives."],
  "https://uxjobsboard.com": [null, "A job board just for UX roles."],
  "https://remoteok.com": [null, "Remote jobs, with a design category."],
  "https://www.midjourney.com": [null, "The most widely used image generation AI. Style references are its strength."],
  "https://chatgpt.com": [null, "OpenAI's chat assistant. Image generation, planning and copywriting."],
  "https://claude.ai": [null, "Anthropic's chat assistant. Strong at long documents and writing code."],
  "https://firefly.adobe.com": [null, "Adobe's generative AI, designed to be safe for commercial use."],
  "https://ideogram.ai": [null, "Image generation that renders text well. Good for poster and logo drafts."],
  "https://www.recraft.ai": [null, "Image generation built for vectors and consistent brand styles."],
  "https://leonardo.ai": [null, "An image generation platform strong in game and concept art."],
  "https://www.krea.ai": [null, "Creative AI with real-time generation, upscaling and video."],
  "https://civitai.com": [null, "A community for sharing Stable Diffusion models and LoRAs."],
  "https://runway.com": [null, "A leader in AI video generation and editing."],
  "https://lumalabs.ai": [null, "AI image and video generation."],
  "https://kling.ai": [null, "High-quality AI video generation."],
  "https://sora.chatgpt.com": [null, "OpenAI's video generation AI."],
  "https://stitch.withgoogle.com": [null, "Google's tool that generates UI screens from prompts and exports to Figma."],
  "https://uizard.io": [null, "Generates UI prototypes from text or sketches."],
  "https://www.relume.ai": [null, "AI-generated sitemaps and wireframes, exportable to Figma and Webflow."],
  "https://www.figma.com/make/": [null, "Figma's AI feature that turns prompts into working prototypes."],
  "https://v0.app": [null, "Vercel's UI code generator for React and Tailwind components."],
  "https://lovable.dev": [null, "An AI builder that makes full-stack web apps through conversation."],
  "https://bolt.new": [null, "Build and deploy web apps from prompts, right in the browser."],
  "https://cursor.com": [null, "An AI code editor that lowers the barrier for designers who want to code."],
  "https://claude.com/product/claude-code": [null, "Anthropic's agent that writes and edits code from the terminal or desktop."],
  "https://www.magnific.com": [null, "An AI upscaler that brings out detail."],
  "https://upscayl.org": [null, "A free, open-source AI image upscaler."],
  "https://clipdrop.co": [null, "A set of AI image tools: background removal, relighting, expansion and more."],
  "https://vizcom.com": [null, "AI for industrial design that turns sketches into renderings."],
  "https://looka.com": [null, "AI-generated logos and brand kits."],
  "https://gamma.app": [null, "AI-generated presentations, documents and web pages."],
  "https://www.napkin.ai": [null, "Turns text into diagrams and infographics."],
  "https://elevenlabs.io": [null, "AI voice synthesis for video and prototype narration."],
  "https://suno.com": [null, "AI music generation."],
  "https://www.perplexity.ai": [null, "AI search that shows its sources."],
  "https://notebooklm.google.com": [null, "Google's AI that turns your uploaded sources into summaries, Q&A and podcasts."],
  "https://wrtn.ai": ["Wrtn", "A Korean AI portal that offers several models in one place for free."],
  "https://huggingface.co": [null, "The hub for open-source AI models and demos."],
  "https://www.jungle.co.kr": ["Design Jungle", "Korean design news, columns and exhibitions, plus design job listings."],
  "https://mdesign.designhouse.co.kr": ["Monthly Design", "Design House's monthly design magazine (Korea)."],
  "https://blog.naver.com/designpress2016": ["Design Press", "Naver's Design Press: interviews with Korean designers and industry issues."],
  "https://www.surfit.io": ["Surfit", "Article curation for designers and developers, with a new-tab extension (Korean)."],
  "https://yozm.wishket.com": ["Yozm IT", "Wishket's magazine of tech and design articles (Korean)."],
  "https://disquiet.io": ["Disquiet", "A community for product makers to share side projects (Korean)."],
  "https://careerly.co.kr": ["Careerly", "A career social network where practitioners share insights (Korean)."],
  "https://brunch.co.kr": ["Brunch", "A writing platform with many essays and retrospectives by designers (Korean)."],
  "https://toss.tech": ["Toss Tech Blog", "Design and engineering articles from Toss, the Korean fintech."],
  "https://designbase.co.kr": ["Designbase", "Design tool courses and articles. Good for beginners (Korean)."],
  "https://coloso.co.kr": [null, "Online courses taught by working designers and artists."],
  "https://www.inflearn.com": ["Inflearn", "A Korean online course platform for tech and design."],
  "https://fastcampus.co.kr": ["Fast Campus", "Practical, job-focused online courses (Korean)."],
  "https://class101.net": ["Class101", "A subscription for creative courses, from hobbies to professional skills (Korean)."],
  "https://layers.to": [null, "A community and portfolio platform for designers."],
  "https://www.producthunt.com": [null, "A community where new products and tools launch every day."],
  "https://sidebar.io": [null, "A newsletter with five design links a day."],
  "https://uxdesign.cc": [null, "The biggest UX publication on Medium."],
  "https://uxplanet.org": [null, "A publication of UX articles."],
  "https://www.smashingmagazine.com": [null, "In-depth articles on web design and front-end."],
  "https://www.figma.com/blog/": [null, "Figma's articles on design and product."],
  "https://eyeondesign.aiga.org": [null, "AIGA's graphic design magazine."],
  "https://www.creativeboom.com": [null, "News and interviews from the creative industries."],
  "https://www.dezeen.com": [null, "The architecture, interiors and product design magazine."],
  "https://design-milk.com": [null, "A magazine of modern design, art and interiors."],
  "https://www.refactoringui.com": [null, "A practical UI design book for developers and designers."],
  "https://ixdf.org": [null, "A nonprofit offering UX theory and courses."],
  "https://www.youtube.com/@thefutur": [null, "The business of design, client negotiation and brand strategy. The largest designer channel."],
  "https://www.youtube.com/@FluxAcademy": [null, "Practical web design and running a freelance business. Figma and Webflow tutorials."],
  "https://www.youtube.com/@DesignCourse": [null, "A channel that covers UI design and front-end together."],
  "https://www.youtube.com/@SatoriGraphics": [null, "Logo and graphic design theory, plus Illustrator tips."],
  "https://www.youtube.com/@WillPaterson": [null, "Logo design, hand lettering and branding process."],
  "https://www.youtube.com/@ForeverDansky": [null, "Short, clear tutorials for Adobe tools and Figma."],
  "https://www.youtube.com/@Mizko": [null, "Product design in practice, advanced Figma and career advice."],
  "https://www.youtube.com/@MalewiczHype": [null, "UI design tips and trend critique. Short, blunt videos."],
  "https://www.youtube.com/@juxtopposed": [null, "UI/UX redesign case studies with humor and polished editing."],
  "https://www.youtube.com/@JesseShowalter": [null, "UI/UX basics, portfolios and tool tutorials."],
  "https://www.youtube.com/@LinusBoman": [null, "Video essays on typography and logos: type history and critique."],
  "https://www.youtube.com/@yesimadesigner": [null, "Photoshop and Illustrator tutorials from Adobe Certified Instructor Martin Perhiniak."],
  "https://www.youtube.com/@PiXimperfect": [null, "The textbook channel for Photoshop retouching and compositing."],
  "https://www.youtube.com/@AbiConnick": [null, "A branding designer's process, freelance tips and client work."],
  "https://www.youtube.com/@TheDesignTheory": [null, "An essay channel on design theory, history and critique."],
  "https://www.youtube.com/@tutvid": [null, "In-depth tutorials for Photoshop, Illustrator and Premiere."],
  "https://www.youtube.com/@CharliMarieTV": [null, "A designer's day-to-day life, career and portfolio."],
  "https://www.youtube.com/@PhotoshopTrainingChannel": [null, "Tutorials that dig deep into Photoshop features."],
  "https://www.youtube.com/@femkedesign": [null, "A product designer on real-world work and career advice."],
  "https://www.youtube.com/@AJSmart": [null, "Design sprints and workshop facilitation."],
  "https://www.youtube.com/@NNgroup": [null, "Short UX research lessons from Nielsen Norman Group."],
  "https://www.youtube.com/@GoogleDesign": [null, "Talks from Google's design team and Material Design stories."],
  "https://www.youtube.com/@Figma": [null, "Figma's official channel: new features and Config sessions."],
  "https://www.youtube.com/@AIGAdesign": [null, "Conference talks from the American professional association for design."],
  "https://www.youtube.com/@ItsNiceThat": [null, "Creative interviews and studio visits."],
  "https://www.youtube.com/@gobirdmasterclass": [null, "Short breakdowns of graphic design styles and layouts. Known for Instagram Reels."],
  "https://www.youtube.com/@designbase": ["Designbase", "Design tool lessons and practical tips. The best-known channel for Korean beginners."],
  "https://www.youtube.com/@Park3min": ["Park's 3-Minute Lessons", "Photoshop, Premiere and other tool features explained in three minutes (Korean)."],
  "https://www.youtube.com/@designspectrum": ["Design Spectrum", "Conference and talk videos from a Korean designer community."],
  "https://www.youtube.com/@ahngraphics": ["Ahn Graphics", "Books and author talks from Korean design publisher Ahn Graphics."],
  "https://www.youtube.com/@notefolio": ["Notefolio (YouTube)", "Designer interviews and talks from Notefolio (Korean)."],
  "https://www.youtube.com/@designjungle": ["Design Jungle (YouTube)", "Exhibitions and designer profiles from Design Jungle (Korean)."],
  "https://www.youtube.com/@loudsourcing": ["Loud Sourcing (YouTube)", "Designer interviews and tips from the design contest platform (Korean)."],
  "https://www.instagram.com/gobirdmasterclass/": [null, "Design styles and principles explained as cards and Reels."],
  "https://www.instagram.com/posterlad/": [null, "Mohamed Samir's daily poster project."],
  "https://www.instagram.com/typo_graphic_posters/": [null, "An archive account of typographic posters."],
  "https://www.instagram.com/logoinspirations/": [null, "A logo design curation account."],
  "https://www.instagram.com/pentagramdesign/": [null, "Work from the world's largest independent design studio."],
  "https://www.instagram.com/studiofeixen/": [null, "Experimental type and motion graphics from a Swiss studio."],
  "https://www.instagram.com/brand.new/": [null, "Instagram for the brand redesign review site."],
  "https://www.instagram.com/thedesigntip/": [null, "Graphic design tips and reference curation."],
  "https://www.instagram.com/graphicdesigncentral/": [null, "A graphic design work curation account."],
  "https://www.instagram.com/itsnicethat/": [null, "Daily curation from the creative magazine."],
  "https://www.instagram.com/notefolio_official/": ["Notefolio (Instagram)", "Work by Korean designers."],
  "https://www.instagram.com/designjungle/": ["Design Jungle (Instagram)", "Korean design news and exhibitions."],
  "https://www.designmattersmedia.com": [null, "The longest-running design podcast. Interviews with designers and writers."],
  "https://designdetails.fm": [null, "Two product designers talk about their work."],
  "https://grok.com": [null, "xAI's chat assistant, with real-time X (Twitter) data and image generation."],
  "https://gemini.google.com": [null, "Google's chat assistant. Strong at image generation and editing (Nano Banana) and Deep Research."],
  "https://copilot.microsoft.com": [null, "Microsoft's AI assistant, integrated with Office and Windows."],
  "https://chat.deepseek.com": [null, "A Chinese chat assistant known for its open-weight models."],
  "https://chat.mistral.ai": [null, "The chat assistant from Europe's Mistral. Fast answers and document handling."],
  "https://chat.qwen.ai": [null, "Alibaba's chat assistant, with image and video generation in the same place."],
  "https://www.meta.ai": [null, "Meta's chat assistant, with image generation and Instagram and WhatsApp integration."],
  "https://manus.im": [null, "An autonomous agent that carries tasks through to the end: research, slides, websites."],
  "https://stability.ai": [null, "The maker of Stable Diffusion. Open image, video and audio models."],
  "https://bfl.ai": [null, "The open FLUX image models. Photorealistic output and accurate text rendering."],
  "https://playground.com": [null, "An AI design tool that generates logos, posters and social graphics from templates."],
  "https://www.comfy.org": [null, "A node-based, open-source workflow tool for image and video generation. Runs locally."],
  "https://www.kittl.com": [null, "A browser graphic design tool with built-in AI. Logos, T-shirts and posters."],
  "https://www.freepik.com/ai": [null, "Freepik's AI image and video generators, many models in one place."],
  "https://www.topazlabs.com": [null, "The standard for photo and video upscaling and noise reduction."],
  "https://labs.google/fx/tools/flow": [null, "Google's AI filmmaking tool built on its Veo models."],
  "https://pika.art": [null, "Short-form AI video generation and editing, with effects and lip sync."],
  "https://hailuoai.video": [null, "MiniMax's video generation AI. Natural human motion."],
  "https://higgsfield.ai": [null, "AI for cinematic video using camera-movement presets."],
  "https://www.heygen.com": [null, "AI avatar and dubbing videos with multilingual lip sync."],
  "https://www.synthesia.io": [null, "An AI avatar video platform for businesses."],
  "https://www.capcut.com": [null, "A video editor strong in AI captions, background removal and templates. Mobile and desktop."],
  "https://www.descript.com": [null, "Edit video and podcasts by editing the transcript."],
  "https://www.swishy.ai": [null, "An AI motion designer: describe it, and it animates text, logos and UI."],
  "https://www.udio.com": [null, "AI music generation, the other big name alongside Suno."],
  "https://replit.com": [null, "Build apps with an AI agent in the browser and deploy right away."],
  "https://github.com/features/copilot": [null, "The most widely used AI coding assistant, built into VS Code and more."],
  "https://www.toools.design": [null, "A directory of 1,500+ design resources and tools."],
  "https://www.landingfolio.com": [null, "Landing page and component inspiration, searchable by section."],
  "https://supahero.io": [null, "A gallery of hero sections only. Good for nailing a landing page's first impression."],
  "https://www.cssdesignawards.com": [null, "One of the major web design awards, alongside Awwwards."],
  "https://thefwa.com": [null, "Interactive web awards running since 2000."],
  "https://onepagelove.com": [null, "One-page website gallery and templates."],
  "https://bentogrids.com": [null, "Bento grid layout references."],
  "https://uxarchive.com": [null, "Mobile app user flows, step by step in screenshots."],
  "https://goodux.appcues.com": [null, "Well-made UX examples: onboarding, empty states and more."],
  "https://ui8.net": [null, "A marketplace for premium UI kits, icons and 3D assets."],
  "https://www.ripplix.com": [null, "7,000+ UI animations and micro-interactions from real apps and sites, searchable by element, industry and product."],
  "https://mindsparklemag.com": [null, "A curation magazine for branding and web design."],
  "https://gurafiku.tumblr.com": [null, "An archive of Japanese graphic design."],
  "https://colors.muz.li": [null, "Palette generation with previews on real UI and illustrations."],
  "https://colorkit.co": [null, "A palette generator, popular palettes and color tools."],
  "https://www.dafont.com": [null, "The biggest collection of fonts free for personal use. Always check the license."],
  "https://www.fontsquirrel.com": [null, "Only fonts that are free for commercial use, plus a webfont generator."],
  "https://pangrampangram.com": [null, "A foundry that releases trendy typefaces free for personal use."],
  "https://klim.co.nz": [null, "A New Zealand foundry. Premium typefaces often used in branding."],
  "https://icons8.com": [null, "A large site of icons, illustrations, photos and 3D, organized by style."],
  "https://iconoir.com": [null, "1,600+ open-source line icons."],
  "https://pixabay.com": [null, "Free photos, illustrations, vectors, video and music."],
  "https://creativemarket.com": [null, "A marketplace for fonts, graphics, templates and mockups, sold individually."],
  "https://elements.envato.com": [null, "One subscription for unlimited templates, fonts, video and music."],
  "https://craftwork.design": [null, "Bundles of illustrations, UI kits and 3D assets."],
  "https://getbootstrap.com": [null, "The longest-running CSS framework. Responsive grid and components."],
  "https://www.frontendmentor.io": [null, "Learn by building real designs in code."],
  "https://uiverse.io": [null, "Open-source CSS buttons, loaders and cards made by the community."],
  "https://www.sketch.com": [null, "The Mac-only UI design tool. The standard before Figma."],
  "https://penpot.app": [null, "An open-source design and prototyping tool. The free alternative to Figma."],
  "https://jitter.video": [null, "Simple motion and animation design in the browser, with Figma integration."],
  "https://www.loom.com": [null, "Quick screen recordings to explain and share designs."],
  "https://www.glassdoor.com": [null, "Company reviews, salaries and jobs worldwide."],
  "https://wellfound.com": [null, "A startup hiring platform (formerly AngelList Talent)."],
  "https://www.densediscovery.com": [null, "A weekly newsletter on design, tech and culture."],
  "https://publy.co": ["Publy", "A subscription for articles by working professionals (Korean)."],
};

/* 스타일: 영문 이름 -> [시대, 설명, 특징, 대표 인물] */
const STYLES_EN = {
  "Art Nouveau": ["1890–1910", "Organic curves and plant motifs taken from nature, with ornamental hand lettering. Where poster art began.", "Organic curves · Floral motifs · Ornamental lettering · Pastel tones", "Alphonse Mucha, Aubrey Beardsley"],
  "Dada": ["1916–1924", "An anti-art movement born in reaction to war. Mocked order with random type and photomontage.", "Collage · Photomontage · Jumbled type · Chance", "Hannah Höch, Kurt Schwitters"],
  "Constructivism": ["1915–1930s", "Propaganda graphics of the Russian Revolution. Diagonal compositions, red and black, and photomontage for a forceful message.", "Diagonals · Red/black · Photomontage · Geometric shapes", "El Lissitzky, Alexander Rodchenko"],
  "De Stijl": ["1917–1931", "A Dutch abstract style built from vertical and horizontal lines and the three primaries. The root of today's grid systems.", "Vertical/horizontal lines · Red, blue, yellow · Asymmetric grid", "Piet Mondrian, Theo van Doesburg"],
  "Bauhaus": ["1919–1933", "A German design school and philosophy. Under \"form follows function\" it established geometric forms and sans-serif type.", "Circle, triangle, square · Primaries · Sans-serif · Functionalism", "Herbert Bayer, László Moholy-Nagy, Jan Tschichold"],
  "Art Deco": ["1920s–1930s", "The glamour of the machine age. Luxury expressed through symmetric geometric ornament, metallic sheen and soaring verticals.", "Symmetry · Fans/zigzags · Gold and black · Vertical emphasis", "A. M. Cassandre"],
  "Mid-century Modern": ["1945–1965", "Postwar American optimism. Simple forms, a warm palette and witty illustration opened the golden age of corporate identity.", "Simple forms · Mustard, olive, orange · Witty illustration", "Paul Rand, Saul Bass, Alexander Girard"],
  "International Typographic Style": ["1950s–", "Grids, Helvetica, flush-left asymmetry and objective photography. The basic grammar of modern graphic design and UI layout.", "Grid systems · Helvetica/Akzidenz · Flush left · White space", "Josef Müller-Brockmann, Armin Hofmann, Emil Ruder"],
  "Pop Art": ["1955–1970", "The movement that raised mass culture and advertising imagery to art. Halftone dots, primaries and repetition.", "Halftone dots · Primaries · Comic panels · Repetition", "Andy Warhol, Roy Lichtenstein"],
  "Psychedelic": ["1966–1972", "A hallucinatory style born on rock concert posters. Fluorescent complements and flowing lettering reinterpreted Art Nouveau.", "Fluorescent complements · Melting lettering · Swirls · Low legibility", "Wes Wilson, Victor Moscoso"],
  "Punk": ["1975–1980s", "A DIY aesthetic, made by hand and run off on photocopiers. Letters cut from newspapers and rough collage.", "Cut-out type · Photocopy texture · Safety pins · Black, white and red", "Jamie Reid"],
  "New Wave": ["1970s–1980s", "Experiments that broke the Swiss grid on purpose. Stepped type, varied letterspacing and weight contrast create rhythm.", "Broken grid · Stepped type · Weight and size contrast · Collage", "Wolfgang Weingart, April Greiman"],
  "Memphis": ["1981–1988", "The playful style of the Italian design group Memphis. Clashing pastels and primaries, terrazzo patterns, geometric shapes.", "Terrazzo and squiggles · Pastels + primaries · Geometric shapes · Humor", "Ettore Sottsass, Nathalie Du Pasquier"],
  "Grunge": ["1990s", "Typography that put emotion before legibility. Overlapping, broken letters and messy textures.", "Overlapping type · Stains and scratches · Distortion · Low saturation", "David Carson (Ray Gun)"],
  "Retrofuturism": ["1950s–60s / revival", "The future as the past imagined it. Space-age streamlining, chrome and rounded forms, seen with nostalgia.", "Streamlined forms · Chrome · Space motifs · Rounded sans-serifs", ""],
  "Y2K Aesthetic": ["1997–2004 / 2020s revival", "Tech optimism around the millennium. Chrome, holograms, bubbly shapes and translucent plastic.", "Chrome · Holograms · Bubble fonts · Translucent plastic · Silver", "The Designers Republic"],
  "Frutiger Aero": ["2004–2013", "The glossy UI of the Windows Vista and early iPhone era. Glass, water droplets, nature imagery and clear blues.", "Glossy glass · Droplets and grass · Blue/green · Frutiger type", ""],
  "Skeuomorphism": ["2007–2013", "UI that copied the textures of real objects: leather notebooks, wooden shelves, torn paper. Apple's style through iOS 6.", "Real-world textures · Shadows and highlights · Leather and paper · Raised buttons", ""],
  "Flat Design": ["2012–", "Two-dimensional UI stripped of shadows and textures. Popularized by Windows 8 and iOS 7, it became the default for all UI.", "Solid colors · No shadows · Simple icons · Bold type", ""],
  "Material Design": ["2014–", "Google's design language. A paper-and-ink metaphor, shadows that express layers, and meaningful motion.", "Paper layers · Shadow depth · Floating buttons · Responsive motion", ""],
  "Brutalism (Web)": ["2014–", "The raw, undecorated web. System fonts, a default-HTML feel, asymmetry and harsh contrast for a studied indifference.", "System fonts · Black borders · Asymmetry · Marquees and default links", ""],
  "Vaporwave": ["2010s", "A nostalgic aesthetic born in internet subculture. Classical statues, pastel pink and cyan, grids and Japanese text.", "Pink/cyan gradients · Statues · Grids · Glitch · Japanese text", ""],
  "Minimalism": ["Always", "An attitude that keeps only the essentials. Generous white space, a limited palette and restrained type let the content speak.", "White space · Black and white/monochrome · One typeface · Refined grid", ""],
  "Corporate Memphis": ["2017–2022", "The house style of Big Tech illustration. Flat figures with long limbs and pastels. Friendly, but criticized as generic.", "Long-limbed figures · Pastels · Flat illustration · Rounded forms", "Facebook's Alegria"],
  "Neumorphism": ["2020", "UI where elements in the background color seem softly extruded or pressed in. Pretty, but low contrast limits real-world use.", "Double shadows · Monochrome background · Soft extrusion · Low contrast", ""],
  "Glassmorphism": ["2020–", "UI that suggests glass with translucent blur and thin white borders. Back in the mainstream after Apple's Liquid Glass in 2025.", "Background blur · Translucency · Thin borders · Layering", ""],
  "Acid Graphics": ["2018–", "A style from rave and club culture. Liquid chrome type, fluorescent color, distortion and noise.", "Liquid chrome · Neon green/purple · Distorted type · Noise", ""],
  "Risograph": ["1980s press / 2010s revival", "A style that embraces the quirks of the Riso printer. Overlapping fluorescent inks, coarse grain and slight misregistration.", "Overlapping neon inks · Coarse grain · Misregistration · Two- or three-color print", ""],
  "Collage": ["Always", "Mixed media combining cut photos, paper, tape and handwriting. Back in fashion as a handmade touch in the digital age.", "Cut-out photos · Masking tape · Handwriting · Paper texture", ""],
  "Maximalism": ["2020s", "More is more. Heavy ornament, clashing patterns and many typefaces at once create energy.", "Clashing patterns · Many typefaces · High saturation · Dense layouts", ""],
  "Pixel Art": ["1980s / revival", "Low-resolution grids and limited palettes. Back in branding and UI on a wave of retro game nostalgia.", "Pixel grid · Limited palette · Bitmap fonts · Jaggies", ""],
  "Cyberpunk": ["1980s–", "Neon cities and dystopia. High tech, low life, layered with glitches, holograms and Japanese and technical text.", "Neon pink/cyan · Glitch · Scanlines · Technical text", ""],
  "Japanese Modern": ["1960s–", "Traditional motifs and the beauty of empty space translated into modern graphics. Restrained forms and bold fields of color.", "White space · Vertical typesetting · Reinterpreted traditional motifs · Bold color fields", "Ikko Tanaka, Tadanori Yokoo, Kashiwa Sato"],
  "Anti-design": ["2019–", "Awkward and ugly on purpose. Default fonts, clip art and glaring colors rebel against polish.", "Default fonts · Clip art · Clashing colors · Misalignment", ""],
};

/* 트렌드: 한국어 이름 -> [영문 이름, 분야, 설명] */
const TRENDS_EN = {
  "리퀴드 글래스": ["Liquid Glass", "UI", "The design language Apple introduced in 2025. Refractive, reflective glass is spreading across app and web UI."],
  "클라우드 댄서 (팬톤 2026)": ["Cloud Dancer (Pantone 2026)", "Color", "The soft white Pantone chose as its 2026 Color of the Year. Off-whites and muted minimal palettes are gaining ground again."],
  "AI 비주얼 vs 손맛 회귀": ["AI visuals vs. the handmade", "Graphic", "As AI images become common, hand drawing, analog texture and imperfection become the differentiator."],
  "익스프레시브 타이포": ["Expressive type", "Type", "Huge letters, variable fonts and kinetic type. The typeface itself becomes the hero visual."],
  "네오 브루탈리즘": ["Neo-brutalism", "UI/Web", "Thick black borders, hard shadows and primary-color blocks. Spreading as a reaction to flat SaaS UI."],
  "픽셀 · 로우파이 노스탤지어": ["Pixel and lo-fi nostalgia", "Graphic", "8-bit pixels, bitmap fonts and the early-internet feel. Gen Z's idea of retro has moved to the '90s and 2000s."],
  "벤토 그리드": ["Bento grid", "UI/Web", "Cards of different sizes packed tightly like a bento box. Now standard for landing pages and dashboards."],
  "크롬 · 메탈릭": ["Chrome and metallic", "Graphic", "Liquid metal and chrome type carried over from Y2K, now more refined through 3D."],
  "도파민 컬러": ["Dopamine color", "Color", "High-saturation palettes that lift the mood. Coexisting at the opposite end from the minimal-white trend."],
  "콜라주 · 스티커 · 스크랩북": ["Collage, stickers, scrapbook", "Graphic", "Cut-out photos, masking tape and handwriting. The leading handmade look in social content and branding."],
  "세리프 리바이벌 · 에디토리얼": ["Serif revival and editorial", "Type", "Magazine-style serif headlines and airy editorial layouts. Favored by premium and lifestyle brands."],
  "촉감 있는 3D": ["Tactile 3D", "Graphic/UI", "Clay, inflated and softly rendered objects. Adds depth to icons and hero visuals."],
  "프린트 · 리소 텍스처": ["Print and riso textures", "Graphic", "Grain, ink bleed and print imperfections recreated digitally. The texture of risograph and offset."],
  "오라 · 블러 그라디언트": ["Aura and blur gradients", "UI/Graphic", "Backgrounds of soft, blurry blobs of light. Especially common in AI product branding."],
  "모션 우선 인터페이스": ["Motion-first interfaces", "UI/Web", "Design where scrollytelling, micro-interactions and page transitions come before the static layout."],
};

/* 용어: 한국어 용어 -> [영문 용어, 설명]. 영문판에서는 영문 용어가 제목, 한국어가 보조로 보입니다. */
const GLOSSARY_EN = {
  "서체 / 폰트": ["Typeface / Font", "A typeface is the design of the letters (e.g. Pretendard); a font is one weight or style file of it (e.g. Pretendard Bold). In practice people use the words interchangeably."],
  "세리프 / 산세리프": ["Serif / Sans-serif", "Letters with small strokes at the ends (serifs) are serif; without them, sans-serif. Serif is common for printed body text, sans-serif for screen UI. In Korean type, Myeongjo and Gothic are the rough equivalents."],
  "웨이트": ["Weight", "The thickness of the letters, numbered from Thin (100) to Black (900). UI usually stays within Regular, Medium, SemiBold and Bold."],
  "가변 폰트": ["Variable Font", "One font file where weight, width, slant and more can be adjusted continuously. Fewer files on the web and finer control."],
  "자간": ["Tracking / Letter-spacing", "Overall spacing between letters. By convention, tighten headlines (-2 to -4%) and loosen small caps and captions."],
  "커닝": ["Kerning", "Adjusting the space between specific letter pairs (AV, To). Most noticeable at large sizes, as in logos and headlines."],
  "행간": ["Leading / Line-height", "Space between lines. Body text is usually 1.5–1.7× the font size, headlines 1.1–1.3×. Korean text needs a little more than Latin."],
  "베이스라인": ["Baseline", "The invisible line letters sit on. Align mixed type sizes on their baselines."],
  "엑스하이트": ["x-height", "The height of the lowercase x. Typefaces with a large x-height read well at small sizes, which suits UI body text."],
  "어센더 / 디센더": ["Ascender / Descender", "The parts that rise above the x-height (b, d, h) and drop below the baseline (g, p, y)."],
  "합자": ["Ligature", "A single glyph designed from two joined letters, like fi or fl. Helps serif body text flow naturally."],
  "위도우 / 오펀": ["Widow / Orphan", "A single word left on a paragraph's last line (widow), or a paragraph's first line stranded at the bottom of a page (orphan). Always fixed in editorial work."],
  "리버": ["Rivers", "Gaps in justified text that line up into vertical white streams. Fixed with hyphenation or spacing adjustments."],
  "정렬": ["Alignment", "Left, right, centered or justified. Flush-left (ragged right) is easiest to read for body text; keep centered text for short lines."],
  "타입 스케일": ["Type Scale", "A set of font sizes that grows by a fixed ratio (1.2, 1.25, 1.333…). Decide sizes like 12, 14, 16, 20, 24, 32 up front."],
  "위계": ["Hierarchy", "Ordering information by importance using size, weight, color and spacing. Around three levels per screen is enough."],
  "가독성 / 판독성": ["Readability / Legibility", "Legibility is how easily individual letters are told apart; readability is how comfortably text reads. Choosing a typeface is about legibility, setting it is about readability."],
  "옵티컬 사이즈": ["Optical Size", "Variants of a typeface drawn differently for text and display sizes. Display cuts have stronger contrast and tighter spacing."],
  "판형": ["Trim Size", "The final size of a printed piece: A4 (210×297), or Korean book sizes like Guk-pan (148×210) and Shinguk-pan (152×225). The starting point for grids and margins."],
  "판면": ["Type Area", "The area where the text sits, excluding margins. Its proportions shape the feel of a book."],
  "그리드": ["Grid", "The invisible framework of columns and rows on a page. The basis for consistent placement and rhythm."],
  "컬럼 / 거터": ["Column / Gutter", "Columns are the vertical divisions of a grid; gutters are the gaps between them. On the web, 12 columns with 16–24px gutters is typical."],
  "마진": ["Margin", "The white space at the edges of a page. Books use a wider inner margin on the binding side."],
  "블리드 (도련)": ["Bleed", "Extending images 3mm past the trim line to allow for cutting errors. Without bleed you get white slivers at the edge."],
  "재단선 / 트림 마크": ["Trim Marks", "Marks showing where the paper will be cut after printing. Include them with bleed when exporting a print PDF."],
  "세이프 존": ["Safe Area", "The zone 3–5mm inside the trim line. Keep text and important elements inside it so nothing gets cut off."],
  "스프레드 (펼침면)": ["Spread", "Two facing pages viewed as one. Books and brochures are designed spread by spread."],
  "폴리오": ["Folio", "The page number, usually placed with the running head at the top or bottom of the page."],
  "캡션 / 풀아웃": ["Caption / Pull Quote", "A caption describes an image; a pull quote lifts a line from the text and sets it large for emphasis."],
  "CMYK / RGB": ["CMYK / RGB", "Print uses four ink colors (CMYK); screens use three colors of light (RGB). Vivid RGB colors turn muddy in print, so convert to CMYK and check."],
  "별색": ["Spot Color (Pantone)", "A premixed ink rather than a CMYK mix. Used when a color must be exact: brand colors, metallics, fluorescents."],
  "DPI / PPI": ["DPI / PPI", "Resolution. Print images need 300dpi at actual size; 72–144ppi is plenty for screens."],
  "리치 블랙": ["Rich Black", "K100 alone looks grayish, so a deep black mixes in C, M and Y (e.g. C60 M40 Y40 K100). Keep small text at K100 only."],
  "오버프린트 / 트래핑": ["Overprint / Trapping", "Printing one ink over another (overprint) or slightly widening edges (trapping) so misregistration doesn't leave white gaps. Black text is usually overprinted."],
  "후가공": ["Finishing", "Processes added after printing: foil stamping, embossing, spot UV, coating, scoring, die cutting and more."],
  "제본": ["Binding", "Saddle stitch (staples, thin booklets), perfect binding (glued, most paperbacks), case binding (hardcover), sewn binding (lies flat)."],
  "평량": ["Paper Weight (g/㎡)", "Paper thickness expressed as weight. Roughly 300g for business cards, 150–200g for posters, 80–100g for book pages."],
  "교정쇄 / 프루프": ["Proof", "A sample for checking color and typos before the final run. If color matters, always see a proof on the actual paper."],
  "아웃라인 처리": ["Create Outlines", "Converting text to paths before sending files to the printer so missing fonts can't cause problems. Keep an editable original."],
  "터잡기": ["Imposition", "Arranging pages on a large press sheet so they fall in order once folded. Page counts are usually multiples of four."],
  "HEX / RGB / HSL": ["Color Notation", "HEX (#5B5BD6) is the most common on the web; HSL describes hue, saturation and lightness, which makes palette tweaks easy."],
  "색상 · 채도 · 명도": ["Hue · Saturation · Value", "Hue is the kind of color (red, blue), saturation is its intensity, value is its lightness. Thinking in these three axes makes combining colors easier."],
  "보색 / 유사색": ["Complementary / Analogous", "Colors opposite each other on the wheel are complementary (strong contrast); neighbors are analogous (harmony). Complements for emphasis, analogous for backgrounds."],
  "톤온톤 / 톤인톤": ["Tone on Tone / Tone in Tone", "Tone on tone varies the lightness of one hue; tone in tone uses different hues of a similar tone. Common terms in Korean and Japanese design."],
  "60-30-10": ["60-30-10 Rule", "Split colors 60% dominant, 30% secondary, 10% accent. Keeps things balanced even with several colors."],
  "명도 대비": ["Contrast Ratio", "The brightness difference between text and background, from 1:1 to 21:1. WCAG requires at least 4.5:1 for body text and 3:1 for large text."],
  "WCAG AA / AAA": ["WCAG Levels", "Conformance levels of the web accessibility guidelines. Most services aim for AA (4.5:1 contrast)."],
  "시맨틱 컬러": ["Semantic Color", "Colors named by purpose: primary, success, warning, error. Defining colors by meaning makes dark mode much easier."],
  "컬러 스케일": ["Color Scale", "One hue laid out in about ten lightness steps, like 50–950. The basic unit of a design system's color."],
  "색 공간": ["Color Space (sRGB · P3 · OKLCH)", "sRGB is the web standard, Display P3 is a wider gamut, and OKLCH is a newer notation that is perceptually uniform. Modern CSS supports all three."],
  "그라디언트": ["Gradient", "A gradual change between colors. Blend colors that sit close on the color wheel so the middle doesn't turn muddy."],
  "컬러 프로파일": ["Color Profile (ICC)", "Settings that match color across devices and papers. Use the profile your printer specifies for print files (e.g. Japan Color 2001 Coated)."],
  "CI / BI": ["Corporate / Brand Identity", "CI is a company's overall identity; BI is the identity of an individual brand or product. Both cover logo, color, type and tone. Common abbreviations in Korea."],
  "심볼 / 워드마크 / 로고타입": ["Symbol / Wordmark / Logotype", "A symbol is a pictorial mark; a wordmark (logotype) is a logo made of letters. Combining them by set rules gives the signature."],
  "브랜드 가이드라인": ["Brand Guidelines", "The document covering logo usage, minimum size, clear space, misuse, color, type and image tone. Always ask for it when taking client work."],
  "키 비주얼": ["Key Visual", "The core image that represents a campaign or brand. The original that gets adapted into posters, banners and social posts."],
  "무드보드": ["Mood Board", "A board of reference images, colors and textures for setting direction. Used to agree with the client before drafting."],
  "톤앤매너": ["Tone & Manner", "Consistency in how a brand speaks and looks: color, type, photography and writing style. A very common phrase in Korean agencies."],
  "그래픽 모티프": ["Graphic Motif", "A shape or pattern derived from the logo and used repeatedly. It makes the brand recognizable even without the logo."],
  "시안": ["Draft / Comp", "A design option shown to the client. In Korea these are usually presented as options A, B and C, and one is developed further."],
  "룩앤필": ["Look & Feel", "The visual impression (look) and the sense of use (feel). \"Match the look and feel\" means don't break from the existing tone."],
  "어플리케이션": ["Application", "The identity applied to real media: business cards, signage, packaging, web."],
  "벡터 / 래스터": ["Vector / Raster", "Vector (AI, SVG) is math-based and scales without breaking; raster (PNG, JPG) is pixel-based. Logos should always be vector."],
  "베지어 곡선 / 패스": ["Bézier Curve / Path", "Curves built from anchor points and handles. The basis of the pen tool; fewer anchors make smoother curves."],
  "클리핑 마스크": ["Clipping Mask", "Shows the image below only within the shape above. Non-destructive, so it's easy to edit."],
  "블렌딩 모드": ["Blending Mode", "How overlapping layers mix. Multiply darkens, Screen lightens, Overlay adds contrast."],
  "목업 (그래픽)": ["Mockup", "A composite showing the design on a real product (business card, sign, package). Made with smart-object PSDs."],
  "아트워크": ["Artwork", "The final files sent to production. In Korean studios, \"send the artwork\" means send the finished files."],
  "와이어프레임": ["Wireframe", "A blueprint of screen structure and layout in gray boxes and lines, without color or images."],
  "로파이 / 하이파이": ["Lo-fi / Hi-fi", "Levels of fidelity. Lo-fi is sketches and wireframes; hi-fi looks like the real thing."],
  "목업 (UI)": ["Mockup", "A static hi-fi screen that doesn't work yet. Add interactions and it becomes a prototype."],
  "프로토타입": ["Prototype", "A clickable simulation with transitions. Used to validate flows and run usability tests before development."],
  "디자인 시스템": ["Design System", "A reusable system of color, type, spacing, components and usage rules. Essential as teams grow."],
  "컴포넌트": ["Component", "A reusable UI piece like a button, input or card. Edit the main component and every instance updates."],
  "디자인 토큰": ["Design Token", "The smallest unit that stores a value by name (color-primary, space-4). Lets design and code share the same values."],
  "아토믹 디자인": ["Atomic Design", "A method of building UI from atoms (button) to molecules (search bar), organisms (header), templates and pages."],
  "8pt 그리드": ["8pt Grid", "A rule that keeps spacing and sizes in multiples of 8 (8, 16, 24, 32…). Scales cleanly at any resolution."],
  "브레이크포인트": ["Breakpoint", "The screen width at which a layout changes. Typically mobile up to 640, tablet up to 1024, desktop 1280 and up."],
  "반응형 / 적응형": ["Responsive / Adaptive", "Responsive layouts flow fluidly with width; adaptive layouts switch between a few fixed layouts."],
  "뷰포트 / 폴드": ["Viewport / Fold", "The viewport is the visible screen area; the fold is the edge before scrolling. Put the key message and CTA above the fold."],
  "히어로 섹션": ["Hero Section", "The big headline, image and CTA at the top of a landing page. It should say what the product does within three seconds."],
  "CTA": ["Call to Action", "A button that prompts action, like \"Get started\" or \"Buy\". Emphasize only one primary CTA per screen."],
  "GNB / LNB": ["Global / Local Navigation", "GNB is the site-wide menu (top); LNB is the submenu within a section (usually left). Everyday terms in Korean product teams."],
  "햄버거 메뉴 / 탭 바": ["Hamburger / Tab Bar", "The ≡ icon that hides a menu on mobile, versus a tab bar always visible at the bottom. With five or fewer key features, a tab bar works better."],
  "모달 / 다이얼로그": ["Modal / Dialog", "A window on top of the screen that blocks other actions. Tiring when overused; save it for moments that need confirmation."],
  "바텀 시트": ["Bottom Sheet", "A panel that slides up from the bottom of a mobile screen. Lighter than a modal and easy to reach with a thumb."],
  "토스트 / 스낵바": ["Toast / Snackbar", "A brief notice that appears and disappears, like \"Saved\". A snackbar adds one action, such as Undo."],
  "툴팁 / 팝오버": ["Tooltip / Popover", "A short hint on hover or click (tooltip) versus a small window with more content (popover)."],
  "드롭다운 / 셀렉트": ["Dropdown / Select", "A control that opens a list when pressed. With five or fewer options, radios or a segmented control are faster."],
  "아코디언": ["Accordion", "A list where tapping a heading expands or collapses its content. Common for FAQs."],
  "카드": ["Card", "A container grouping an image, title and description. Easy to lay out in a grid, but too many make a page busy."],
  "스켈레톤 UI": ["Skeleton", "Gray blocks shown where content will load. Feels faster than a spinner."],
  "엠프티 스테이트": ["Empty State", "The screen when there's no data. Instead of a blank screen, guide the next action."],
  "온보딩": ["Onboarding", "How new users learn the product: tutorials, permission requests and initial setup screens."],
  "마이크로인터랙션": ["Microinteraction", "Small responses like a button press or a like animation. They give feedback and raise perceived quality."],
  "어포던스": ["Affordance", "The quality that shows how something is used just by looking. Buttons should look pressable; links should be underlined."],
  "상태": ["States (Hover · Active · Focus · Disabled)", "The different looks of a component. Define default, hover, pressed, focus, disabled, loading and error so nothing gets missed in development."],
  "오토 레이아웃": ["Auto Layout", "Figma frames that resize and space themselves around their content. The same idea as CSS flexbox."],
  "컨스트레인트": ["Constraints", "Rules for which edges an element sticks to when its frame resizes. The basis of responsive components."],
  "배리언트": ["Variants", "Several versions of one component (size, state, type) grouped as a set and switched by properties."],
  "핸드오프": ["Handoff", "Passing designs to developers. Should include specs (spacing, color, fonts), assets and interaction notes."],
  "레드라인 / 스펙": ["Redline / Spec", "Documents marking spacing and sizes with red lines and numbers. Figma's Dev Mode now does this automatically."],
  "세이프 에어리어": ["Safe Area", "The area not covered by device UI like the notch or home indicator. Keep important elements inside it."],
  "터치 타깃": ["Touch Target", "The minimum size a finger can reliably tap: at least 44pt on iOS and 48dp on Android."],
  "플레이스홀더 / 밸리데이션": ["Placeholder / Validation", "Hint text before input, and checking what was entered. Using a placeholder as the label is frustrating because it disappears while typing."],
  "브레드크럼": ["Breadcrumb", "Navigation showing the current path, like Home > Category > Product."],
  "페이지네이션 / 무한 스크롤": ["Pagination / Infinite Scroll", "Splitting a list into pages versus loading more as you scroll. Pagination is better for purposeful browsing."],
  "배지 / 칩": ["Badge / Chip", "A badge is a small label for counts or status; a chip is a pill-shaped element used for selection, filters or tags."],
  "캐러셀": ["Carousel", "Slides you swipe through sideways. Most people ignore autoplay, so use it with care."],
  "다크 모드": ["Dark Mode", "A dark background theme. Not a simple inversion: use dark gray instead of pure black, and desaturate accent colors."],
  "UX / UI": ["User Experience / User Interface", "UI is the visible screens and controls; UX is the whole experience of using a product. A pretty UI doesn't guarantee a good UX."],
  "유저 리서치": ["User Research", "Understanding user behavior and needs through interviews, surveys and observation. Split into qualitative (why) and quantitative (how many)."],
  "페르소나": ["Persona", "A representative fictional user built from research. A name, goals and pain points help the team picture the same person."],
  "유저 저니 맵": ["User Journey Map", "A timeline of a user's actions, feelings and touchpoints on the way to a goal. A tool for finding pain points."],
  "정보 구조": ["Information Architecture (IA)", "Deciding how content and features are grouped, named and connected. The sitemap is its output."],
  "유저 플로우": ["User Flow", "A diagram of the screens and branches for a specific goal (sign-up, checkout). Drawn before wireframes."],
  "카드 소팅": ["Card Sorting", "A research method where users sort item cards into groups to shape the menu structure."],
  "사용성 테스트": ["Usability Test", "Giving real users tasks and watching them work. Five people are enough to surface most major problems."],
  "휴리스틱 평가": ["Heuristic Evaluation", "Experts review a UI against criteria like Nielsen's ten heuristics. Faster and cheaper than testing."],
  "A/B 테스트": ["A/B Test", "An experiment that shows two versions to different users and compares metrics like clicks and conversions."],
  "접근성": ["Accessibility (a11y)", "Making products usable by everyone regardless of disability or situation: contrast, keyboard access, alt text, screen reader support."],
  "인지 부하": ["Cognitive Load", "The mental effort needed to understand a screen. Fewer choices, less information and less decoration lower it."],
  "힉의 법칙": ["Hick's Law", "More choices mean longer decisions. Trim menus and break things into steps."],
  "피츠의 법칙": ["Fitts's Law", "Bigger, closer targets are faster to hit. Make important buttons large and near the thumb."],
  "제이콥의 법칙": ["Jakob's Law", "Users expect your product to work like the others they know. Following convention is usually right."],
  "멘탈 모델": ["Mental Model", "A user's belief about how something will work. Match it and no explanation is needed."],
  "다크 패턴": ["Dark Pattern", "Design that tricks users for profit, like hidden cancel buttons or pre-checked consent. Increasingly regulated."],
  "퍼널 / 전환율": ["Funnel / Conversion Rate", "The narrowing steps from visit to sign-up to purchase (funnel), and the share who move to the next step (conversion rate). Basic metrics for finding drop-off."],
  "리텐션": ["Retention", "The share of users who come back. Says more about a product's health than new sign-ups."],
  "KPI / OKR": ["KPI / OKR", "Key metrics for measuring performance (KPI) and a framework for setting objectives and key results (OKR). Used to justify design decisions."],
  "MVP": ["Minimum Viable Product", "The smallest product that delivers the core value, shipped as fast as possible. The goal is learning speed, not polish."],
  "디자인 씽킹 / 더블 다이아몬드": ["Design Thinking / Double Diamond", "Process models that widen then narrow a problem: empathize, define, ideate, prototype, test; or discover, define, develop, deliver."],
  "애자일 / 스프린트": ["Agile / Sprint", "Building, shipping and improving in one- to two-week cycles (sprints). Designers work in sprints too."],
  "백로그": ["Backlog", "A prioritized list of work. Design requests also pile up here and get assigned to sprints."],
  "JTBD": ["Jobs To Be Done", "A lens focused on the job a user \"hires\" a product to do. People don't want a drill, they want a hole."],
  "히트맵": ["Heatmap", "Analytics that color where clicks, scrolls or attention concentrate. Shows how much content below the fold gets seen."],
  "HTML / CSS / JS": ["HTML / CSS / JavaScript", "HTML is structure, CSS is appearance, JS is behavior. Designers who can read CSS have much more precise handoff conversations."],
  "px / rem / em": ["CSS Units", "px is fixed, rem is relative to the root font size (usually 16px = 1rem), em is relative to the parent. Use rem for text for accessibility."],
  "박스 모델": ["Box Model (Margin · Padding · Border)", "An element is wrapped by content, then padding (inner space), border, then margin (outer space). The same idea as padding in Figma's auto layout."],
  "플렉스박스 / 그리드": ["Flexbox / CSS Grid", "Flexbox for one-direction alignment, Grid for two-dimensional rows and columns. Auto layout translates to flexbox."],
  "미디어 쿼리": ["Media Query", "CSS syntax that applies styles based on conditions like screen width or dark mode. This is where breakpoints are implemented."],
  "SVG / PNG / WebP": ["Image Formats", "SVG for icons and logos, PNG for transparency, WebP (or AVIF) for lightweight photos. JPG is steadily being replaced by WebP."],
  "이징": ["Easing", "The speed curve of an animation. Ease-out starts fast and settles gently, which feels most natural in UI. Keep durations around 150–300ms."],
  "z-index": ["z-index", "Stacking order when elements overlap. Define the layers for modals, tooltips and dropdowns in the design system."],
  "시맨틱 마크업": ["Semantic Markup", "Using tags that match meaning: button for buttons, h1–h6 for headings. The basis of accessibility and search visibility."],
  "컴포넌트 라이브러리 / 스토리북": ["Component Library / Storybook", "A set of components implemented in code, and a tool to view them in isolation. The engineering counterpart of a design system."],
  "CSS 변수": ["CSS Custom Properties", "A CSS feature that stores values by name, like --color-primary. This is what design tokens become in code."],
  "웹폰트 / FOUT": ["Web Font / FOUT", "Fonts downloaded from a server, and the flash of fallback text before they load. Subset fonts reduce the size and the flash."],
  "레이지 로딩": ["Lazy Loading", "Loading images only when they come into view. Greatly speeds up the first load of long pages."],
  "LCP / CLS": ["Core Web Vitals", "Google's performance metrics. LCP is when the largest content appears; CLS is how much the layout jumps while loading. Setting image dimensions reduces CLS."],
  "QA": ["Quality Assurance", "Checking for bugs before release. Design QA catches where the build differs from the design: spacing, color, states."],
  "스테이징 / 배포": ["Staging / Deploy", "Staging is the test server used before production. \"It's on staging\" means please take a look."],
  "Git / PR": ["Git / Pull Request", "A tool for tracking code changes, and a request to merge a change. The same idea as branching and versions in design files."],
  "API": ["Application Programming Interface", "The agreement programs use to exchange data. \"The API isn't ready\" means the real data for the screen isn't available yet."],
  "CMS": ["Content Management System", "A tool for publishing and editing content without developers, like WordPress or Webflow CMS. Designing the templates falls to designers."],
};
