/* =========================================================
   디자인 허브 데이터
   - CATEGORIES : 카테고리 목록 (순서대로 표시됨) { id, label, desc }
   - SITES      : 사이트 목록
     { name, url, desc, cat, tags, sub? }
       cat  : CATEGORIES 의 id
       tags : '한국' | '무료' | '유료' | 'AI' 등 자유롭게
       sub  : (선택) 카테고리 안 소분류. AI 카테고리는 AI_SUBS 순서로 묶여 표시됨
   새 사이트를 추가하려면 SITES 배열에 객체 하나만 넣으면 됩니다.
   ========================================================= */

/* AI 카테고리 소분류 표시 순서 (SITES 의 sub 값) */
const AI_SUBS = ['LLM · 대화형', '이미지 생성', '이미지 편집 · 업스케일', '영상 생성 · 편집', '오디오 · 음성', 'UI · 코드 생성', '문서 · 프레젠테이션', '리서치 · 모델 허브'];

const CATEGORIES = [
  { id: 'uiux',      label: 'UI/UX 레퍼런스',    desc: '앱·웹 화면, 유저 플로우, 랜딩페이지 인스피레이션' },
  { id: 'graphic',   label: '그래픽 / 브랜딩',   desc: '포스터, 로고, 패키지, 브랜딩, 편집 디자인 레퍼런스' },
  { id: 'color',     label: '컬러 가이드',       desc: '팔레트 생성, 그라디언트, 명도 대비 검사' },
  { id: 'typo',      label: '타이포 / 폰트',     desc: '무료 폰트, 폰트 조합, 타이포그래피 레퍼런스' },
  { id: 'asset',     label: '아이콘 / 에셋',     desc: '아이콘, 일러스트, 목업, 사진, 영상 소스' },
  { id: 'dev',       label: '디자인 개발',       desc: '디자인 시스템, 플랫폼 가이드라인, 인터랙션 구현' },
  { id: 'tool',      label: '디자인 툴',         desc: '제작·협업·프로토타이핑·유틸리티 도구' },
  { id: 'freelance', label: '외주 / 프리랜서',   desc: '외주 매칭 플랫폼, 계약서·대가 기준' },
  { id: 'job',       label: '채용공고',          desc: '디자이너 채용, 기업 정보, 커리어' },
  { id: 'ai',        label: 'AI',                desc: '이미지·영상·UI 생성, AI 코딩 도구' },
  { id: 'community', label: '커뮤니티 / 매거진', desc: '아티클, 뉴스레터, 강의, 디자이너 커뮤니티' },
  { id: 'creator',   label: '크리에이터 / 채널', desc: '디자인 유튜버, 인스타그램 큐레이션 계정, 팟캐스트' },
];

const SITES = [
  /* ---------------- UI/UX 레퍼런스 ---------------- */
  { name: 'Mobbin', url: 'https://mobbin.com', desc: '실제 서비스 앱·웹 화면과 플로우를 통째로 모아둔 UI 아카이브. 화면 단위 검색이 강력합니다.', cat: 'uiux', tags: ['유료'] },
  { name: 'Refero', url: 'https://refero.design', desc: '실제 프로덕트의 UI 패턴을 컴포넌트·페이지 유형별로 검색할 수 있는 레퍼런스 툴.', cat: 'uiux', tags: ['유료'] },
  { name: 'Dribbble', url: 'https://dribbble.com', desc: '전 세계 디자이너들의 샷(Shot) 쇼케이스. 비주얼 트렌드 파악에 좋습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'Behance', url: 'https://www.behance.net', desc: '어도비의 포트폴리오 플랫폼. 프로젝트 단위의 긴 호흡 작업물을 볼 수 있습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'Awwwards', url: 'https://www.awwwards.com', desc: '세계적인 웹 디자인 어워드. 인터랙션이 뛰어난 사이트를 매일 선정합니다.', cat: 'uiux', tags: ['무료'] },
  { name: '지디웹 (GDWEB)', url: 'https://www.gdweb.co.kr', desc: '국내 웹·앱 디자인 어워드. 한국 기업 사이트 레퍼런스를 찾을 때 유용합니다.', cat: 'uiux', tags: ['한국', '무료'] },
  { name: '디비컷 (DBCUT)', url: 'https://www.dbcut.com', desc: '국내 웹디자인 레퍼런스 모음. 업종별·스타일별로 한국 사이트를 살펴볼 수 있습니다.', cat: 'uiux', tags: ['한국', '무료'] },
  { name: 'Land-book', url: 'https://land-book.com', desc: '랜딩페이지 갤러리. 산업·스타일·컬러별 필터가 잘 되어 있습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'Lapa Ninja', url: 'https://www.lapa.ninja', desc: '랜딩페이지 인스피레이션 모음. 무료 UI 킷·북도 함께 제공합니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'Recent (구 Godly)', url: 'https://recent.design', desc: '감각적인 웹사이트만 엄선한 큐레이션. Godly에서 이름을 바꿨습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'Siteinspire', url: 'https://www.siteinspire.com', desc: '깔끔하고 세련된 웹사이트 쇼케이스. 스타일·타입·주제별 필터 제공.', cat: 'uiux', tags: ['무료'] },
  { name: 'Httpster', url: 'https://httpster.net', desc: '트렌디하고 실험적인 웹사이트를 모아둔 갤러리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Minimal Gallery', url: 'https://minimal.gallery', desc: '미니멀한 웹사이트만 모아둔 갤러리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Dark Mode Design', url: 'https://www.darkmodedesign.com', desc: '다크 모드 웹사이트 레퍼런스만 모아둔 사이트.', cat: 'uiux', tags: ['무료'] },
  { name: 'SaaS Landing Page', url: 'https://saaslandingpage.com', desc: 'SaaS 랜딩페이지 예시를 섹션·유형별로 정리한 사이트.', cat: 'uiux', tags: ['무료'] },
  { name: 'Nicelydone', url: 'https://nicelydone.club', desc: 'SaaS 프로덕트의 UI 패턴·플로우를 모아둔 레퍼런스.', cat: 'uiux', tags: ['무료'] },
  { name: 'Page Flows', url: 'https://pageflows.com', desc: '온보딩, 결제 등 유저 플로우를 영상으로 기록해 둔 사이트.', cat: 'uiux', tags: ['유료'] },
  { name: 'Pttrns', url: 'https://www.pttrns.com', desc: '모바일 앱 UI 패턴 레퍼런스의 고전.', cat: 'uiux', tags: ['무료'] },
  { name: 'ScreensDesign', url: 'https://screensdesign.com', desc: '앱스토어 스크린샷과 실제 앱 UI 플로우를 모아둔 사이트.', cat: 'uiux', tags: ['무료'] },
  { name: 'Collect UI', url: 'https://collectui.com', desc: 'Dribbble 샷을 UI 요소(로그인, 404, 대시보드 등)별로 분류한 갤러리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Design Spells', url: 'https://www.designspells.com', desc: '사용자를 미소 짓게 하는 UI 디테일·인터랙션 모음.', cat: 'uiux', tags: ['무료'] },
  { name: 'Footer.design', url: 'https://www.footer.design', desc: '웹사이트 푸터 디자인만 모아둔 레퍼런스.', cat: 'uiux', tags: ['무료'] },
  { name: 'Navbar Gallery', url: 'https://www.navbar.gallery', desc: '내비게이션 바 디자인 레퍼런스 모음.', cat: 'uiux', tags: ['무료'] },
  { name: 'Curated Design', url: 'https://www.curated.design', desc: '트렌디한 웹 디자인 큐레이션. 타입·스타일별 필터 제공.', cat: 'uiux', tags: ['무료'] },
  { name: 'Muzli', url: 'https://muz.li', desc: '디자인 인스피레이션 피드. 크롬 확장 프로그램으로 새 탭에서 바로 볼 수 있습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'UI Patterns', url: 'https://ui-patterns.com', desc: 'UI 패턴을 문제·해결 관점에서 정리한 패턴 라이브러리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Laws of UX', url: 'https://lawsofux.com', desc: '힉의 법칙, 피츠의 법칙 등 UX 심리학 법칙을 카드로 정리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Growth.design', url: 'https://growth.design', desc: '유명 서비스의 UX를 만화 형식으로 분석한 케이스 스터디.', cat: 'uiux', tags: ['무료'] },
  { name: 'Checklist Design', url: 'https://www.checklist.design', desc: '페이지·컴포넌트별 디자인 체크리스트.', cat: 'uiux', tags: ['무료'] },
  { name: 'Nielsen Norman Group', url: 'https://www.nngroup.com', desc: 'UX 리서치의 권위 있는 기관. 휴리스틱, 리서치 아티클이 풍부합니다.', cat: 'uiux', tags: ['무료'] },

  /* ---------------- 그래픽 / 브랜딩 ---------------- */
  { name: 'Pinterest', url: 'https://kr.pinterest.com', desc: '이미지 기반 인스피레이션 보드. 무드보드 만들 때 필수.', cat: 'graphic', tags: ['무료'] },
  { name: '노트폴리오', url: 'https://notefolio.net', desc: '국내 최대 디자이너 포트폴리오 플랫폼. 그래픽·브랜딩·일러스트 레퍼런스.', cat: 'graphic', tags: ['한국', '무료'] },
  { name: 'Are.na', url: 'https://www.are.na', desc: '광고 없는 리서치·큐레이션 도구. 디자이너들의 채널을 탐색할 수 있습니다.', cat: 'graphic', tags: ['무료'] },
  { name: 'Savee', url: 'https://savee.com', desc: '비주얼 인스피레이션 수집 툴. 감각적인 이미지 피드.', cat: 'graphic', tags: ['무료'] },
  { name: 'Cosmos', url: 'https://www.cosmos.so', desc: '알고리즘 없는 큐레이션 기반 디자인 무드보드 플랫폼.', cat: 'graphic', tags: ['무료'] },
  { name: 'Designspiration', url: 'https://www.designspiration.com', desc: '그래픽 디자인 인스피레이션 검색. 컬러로 검색 가능.', cat: 'graphic', tags: ['무료'] },
  { name: 'It\'s Nice That', url: 'https://www.itsnicethat.com', desc: '크리에이티브 산업 전반의 작업물을 소개하는 영국 매거진.', cat: 'graphic', tags: ['무료'] },
  { name: 'Brand New', url: 'https://www.underconsideration.com/brandnew/', desc: '기업 로고·아이덴티티 리뉴얼을 리뷰하는 브랜딩 전문 블로그.', cat: 'graphic', tags: ['무료'] },
  { name: 'BP&O', url: 'https://bpando.org', desc: '브랜딩·패키징 프로젝트를 깊이 있게 소개하는 아카이브.', cat: 'graphic', tags: ['무료'] },
  { name: 'The Dieline', url: 'https://thedieline.com', desc: '패키지 디자인 전문 매거진.', cat: 'graphic', tags: ['무료'] },
  { name: 'Packaging of the World', url: 'https://packagingoftheworld.com', desc: '전 세계 패키지 디자인 갤러리.', cat: 'graphic', tags: ['무료'] },
  { name: 'Logobook', url: 'https://www.logobook.com', desc: '클래식 로고 아카이브. 형태·업종별 분류.', cat: 'graphic', tags: ['무료'] },
  { name: 'LogoLounge', url: 'https://www.logolounge.com', desc: '로고 디자인 트렌드 리포트와 방대한 로고 데이터베이스.', cat: 'graphic', tags: ['유료'] },
  { name: 'Branding Style Guides', url: 'https://brandingstyleguides.com', desc: '기업 브랜드 가이드라인 문서를 모아둔 사이트.', cat: 'graphic', tags: ['무료'] },
  { name: 'Typographic Posters', url: 'https://www.typographicposters.com', desc: '타이포그래피 중심 포스터 아카이브.', cat: 'graphic', tags: ['무료'] },
  { name: 'Ads of the World', url: 'https://www.adsoftheworld.com', desc: '전 세계 광고 캠페인 아카이브.', cat: 'graphic', tags: ['무료'] },
  { name: 'Abduzeedo', url: 'https://abduzeedo.com', desc: '그래픽·브랜딩·일러스트 인스피레이션 블로그.', cat: 'graphic', tags: ['무료'] },
  { name: 'Visuelle', url: 'https://visuelle.co.uk', desc: '편집·브랜딩 디자인 위주의 큐레이션 블로그.', cat: 'graphic', tags: ['무료'] },
  { name: 'Book Cover Archive', url: 'https://bookcoverarchive.com', desc: '북 커버 디자인 아카이브.', cat: 'graphic', tags: ['무료'] },

  /* ---------------- 컬러 가이드 ---------------- */
  { name: 'Coolors', url: 'https://coolors.co', desc: '스페이스바로 팔레트를 빠르게 생성. 이미지에서 컬러 추출, 대비 검사까지.', cat: 'color', tags: ['무료'] },
  { name: 'Adobe Color', url: 'https://color.adobe.com', desc: '색상환 기반 조화 팔레트 생성. 트렌드·탐색 탭도 유용합니다.', cat: 'color', tags: ['무료'] },
  { name: 'Color Hunt', url: 'https://colorhunt.co', desc: '큐레이션된 4색 팔레트 모음. 인기순·트렌드순 정렬.', cat: 'color', tags: ['무료'] },
  { name: 'Realtime Colors', url: 'https://www.realtimecolors.com', desc: '팔레트를 실제 웹 UI에 바로 적용해 보며 확인.', cat: 'color', tags: ['무료'] },
  { name: 'Happy Hues', url: 'https://www.happyhues.co', desc: '팔레트를 페이지 전체에 적용한 모습을 보며 고를 수 있는 사이트.', cat: 'color', tags: ['무료'] },
  { name: 'Khroma', url: 'https://www.khroma.co', desc: '취향을 학습해 팔레트를 추천하는 AI 컬러 툴.', cat: 'color', tags: ['무료', 'AI'] },
  { name: 'Huemint', url: 'https://huemint.com', desc: '브랜드·웹·그라디언트용 팔레트를 AI로 생성.', cat: 'color', tags: ['무료', 'AI'] },
  { name: 'Colormind', url: 'http://colormind.io', desc: '딥러닝 기반 팔레트 생성기. 일부 색을 고정하고 나머지 추천.', cat: 'color', tags: ['무료', 'AI'] },
  { name: 'Paletton', url: 'https://paletton.com', desc: '색상 이론 기반 조합 생성기의 고전.', cat: 'color', tags: ['무료'] },
  { name: 'UI Colors', url: 'https://uicolors.app', desc: '한 가지 색으로 Tailwind 스타일 50~950 단계 팔레트 자동 생성.', cat: 'color', tags: ['무료'] },
  { name: 'Radix Colors', url: 'https://www.radix-ui.com/colors', desc: '접근성을 고려해 설계된 12단계 컬러 스케일 시스템.', cat: 'color', tags: ['무료'] },
  { name: 'Material Theme Builder', url: 'https://material-foundation.github.io/material-theme-builder/', desc: '구글 머티리얼 3 기반 다이내믹 컬러 테마 생성.', cat: 'color', tags: ['무료'] },
  { name: 'WebAIM Contrast Checker', url: 'https://webaim.org/resources/contrastchecker/', desc: 'WCAG 명도 대비 기준 통과 여부 검사.', cat: 'color', tags: ['무료'] },
  { name: 'OKLCH Color Picker', url: 'https://oklch.com', desc: '지각적으로 균일한 OKLCH 색공간 피커. 최신 CSS 컬러 작업에 유용.', cat: 'color', tags: ['무료'] },
  { name: 'Color Leap', url: 'https://colorleap.app', desc: '시대별(고대~현대) 역사적 컬러 팔레트 모음.', cat: 'color', tags: ['무료'] },
  { name: 'Picular', url: 'https://picular.co', desc: '검색어를 입력하면 연관 이미지에서 색을 뽑아주는 컬러 검색.', cat: 'color', tags: ['무료'] },
  { name: 'Color Space', url: 'https://mycolor.space', desc: '한 색을 넣으면 여러 조합과 그라디언트를 한 번에 생성.', cat: 'color', tags: ['무료'] },
  { name: 'Grabient', url: 'https://www.grabient.com', desc: 'CSS 그라디언트를 만들고 코드로 바로 복사.', cat: 'color', tags: ['무료'] },
  { name: 'Grainient', url: 'https://grainient.supply', desc: '그레인·부드러운 그라디언트, 움직이는 그라디언트, AI 배경을 모은 곳. 셰이더로 직접 만들 수도 있고 무료 모음도 있습니다.', cat: 'color', tags: ['무료', '유료'] },
  { name: 'Colors & Fonts', url: 'https://www.colorsandfonts.com', desc: '컬러 팔레트·그라디언트·폰트 조합을 함께 제공.', cat: 'color', tags: ['무료'] },
  { name: 'Encycolorpedia', url: 'https://encycolorpedia.kr', desc: '색상 코드 백과사전. HEX·RGB·CMYK·페인트 매칭 정보.', cat: 'color', tags: ['한국', '무료'] },
  { name: 'Pantone', url: 'https://www.pantone.com', desc: '팬톤 컬러 시스템과 올해의 컬러.', cat: 'color', tags: ['무료'] },

  /* ---------------- 타이포 / 폰트 ---------------- */
  { name: '눈누', url: 'https://noonnu.cc', desc: '상업용 무료 한글 폰트 모음. 라이선스 범위를 한눈에 확인.', cat: 'typo', tags: ['한국', '무료'] },
  { name: 'Google Fonts', url: 'https://fonts.google.com', desc: '오픈소스 웹폰트의 표준. 한글 폰트도 다수 포함.', cat: 'typo', tags: ['무료'] },
  { name: 'Pretendard', url: 'https://github.com/orioncactus/pretendard', desc: '국내 UI 디자인에서 가장 널리 쓰이는 무료 한글 폰트.', cat: 'typo', tags: ['한국', '무료'] },
  { name: '산돌구름', url: 'https://www.sandollcloud.com', desc: '산돌의 폰트 구독 서비스. 국내 상업용 폰트가 가장 많습니다.', cat: 'typo', tags: ['한국', '유료'] },
  { name: '네이버 한글한글 아름답게', url: 'https://hangeul.naver.com', desc: '나눔글꼴, 마루 부리 등 네이버 무료 한글 폰트 배포처.', cat: 'typo', tags: ['한국', '무료'] },
  { name: 'Adobe Fonts', url: 'https://fonts.adobe.com', desc: 'Creative Cloud 구독자를 위한 폰트 라이브러리.', cat: 'typo', tags: ['유료'] },
  { name: 'Fontshare', url: 'https://www.fontshare.com', desc: 'Indian Type Foundry의 고품질 무료 폰트.', cat: 'typo', tags: ['무료'] },
  { name: 'Uncut', url: 'https://uncut.wtf', desc: '현대적인 무료 폰트만 엄선한 카탈로그.', cat: 'typo', tags: ['무료'] },
  { name: 'Velvetyne', url: 'https://velvetyne.fr', desc: '실험적인 오픈소스 폰트 파운드리.', cat: 'typo', tags: ['무료'] },
  { name: 'Free Faces', url: 'https://www.freefaces.gallery', desc: '무료 폰트를 스타일별로 탐색할 수 있는 갤러리.', cat: 'typo', tags: ['무료'] },
  { name: 'Fontesk', url: 'https://fontesk.com', desc: '무료·유료 폰트를 폭넓게 모아둔 사이트.', cat: 'typo', tags: ['무료'] },
  { name: 'Fonts In Use', url: 'https://fontsinuse.com', desc: '실제 작업물에서 폰트가 어떻게 쓰였는지 보여주는 아카이브.', cat: 'typo', tags: ['무료'] },
  { name: 'Typewolf', url: 'https://www.typewolf.com', desc: '폰트 추천, 조합, 대체 폰트 정보가 잘 정리된 사이트.', cat: 'typo', tags: ['무료'] },
  { name: 'Font Pair', url: 'https://www.fontpair.co', desc: 'Google Fonts 조합 추천.', cat: 'typo', tags: ['무료'] },
  { name: 'Typ.io', url: 'https://typ.io', desc: '실제 웹사이트에서 사용된 폰트 조합 모음.', cat: 'typo', tags: ['무료'] },
  { name: 'Fontjoy', url: 'https://fontjoy.com', desc: '딥러닝으로 폰트 조합을 생성.', cat: 'typo', tags: ['무료', 'AI'] },
  { name: 'Type Scale', url: 'https://typescale.com', desc: '타이포그래피 스케일(크기 체계) 계산기.', cat: 'typo', tags: ['무료'] },
  { name: 'Wordmark', url: 'https://wordmark.it', desc: '내 컴퓨터에 설치된 폰트로 문구를 한 번에 미리보기.', cat: 'typo', tags: ['무료'] },
  { name: 'WhatTheFont', url: 'https://www.myfonts.com/pages/whatthefont', desc: '이미지 속 폰트가 무엇인지 찾아주는 서비스.', cat: 'typo', tags: ['무료'] },

  /* ---------------- 아이콘 / 에셋 ---------------- */
  { name: 'Lucide', url: 'https://lucide.dev', desc: '깔끔하고 일관된 오픈소스 아이콘 세트. React 등 패키지 제공.', cat: 'asset', tags: ['무료'] },
  { name: 'Heroicons', url: 'https://heroicons.com', desc: 'Tailwind 팀이 만든 SVG 아이콘.', cat: 'asset', tags: ['무료'] },
  { name: 'Phosphor Icons', url: 'https://phosphoricons.com', desc: '6가지 굵기를 지원하는 유연한 아이콘 패밀리.', cat: 'asset', tags: ['무료'] },
  { name: 'Tabler Icons', url: 'https://tabler.io/icons', desc: '5,000개 이상의 무료 SVG 아이콘.', cat: 'asset', tags: ['무료'] },
  { name: 'Iconify', url: 'https://icon-sets.iconify.design', desc: '200,000개 이상의 아이콘을 한곳에서 검색.', cat: 'asset', tags: ['무료'] },
  { name: 'Feather', url: 'https://feathericons.com', desc: '심플한 선 아이콘의 고전.', cat: 'asset', tags: ['무료'] },
  { name: 'The Noun Project', url: 'https://thenounproject.com', desc: '방대한 픽토그램·아이콘 라이브러리.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'Flaticon', url: 'https://www.flaticon.com', desc: '스타일별 아이콘 팩이 풍부한 대형 아이콘 사이트.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'SVG Repo', url: 'https://www.svgrepo.com', desc: '무료 SVG 아이콘·벡터 모음.', cat: 'asset', tags: ['무료'] },
  { name: '3dicons', url: 'https://3dicons.co', desc: '오픈소스 3D 아이콘. Figma·Blender 파일 제공.', cat: 'asset', tags: ['무료'] },
  { name: 'Lordicon', url: 'https://lordicon.com', desc: '애니메이션 아이콘 라이브러리.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'LottieFiles', url: 'https://lottiefiles.com', desc: '벡터 애니메이션(Lottie) 마켓과 에디터.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'unDraw', url: 'https://undraw.co', desc: '컬러를 바꿔 쓸 수 있는 오픈소스 일러스트.', cat: 'asset', tags: ['무료'] },
  { name: 'Storyset', url: 'https://storyset.com', desc: '커스터마이징 가능한 일러스트. Freepik 제공.', cat: 'asset', tags: ['무료'] },
  { name: 'Humaaans', url: 'https://www.humaaans.com', desc: '조합해서 쓰는 사람 일러스트 라이브러리.', cat: 'asset', tags: ['무료'] },
  { name: 'Open Doodles', url: 'https://www.opendoodles.com', desc: '손그림 느낌의 무료 일러스트.', cat: 'asset', tags: ['무료'] },
  { name: 'Blush', url: 'https://blush.design', desc: '아티스트별 일러스트를 조합해 만드는 툴.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'Unsplash', url: 'https://unsplash.com', desc: '고품질 무료 사진의 대명사.', cat: 'asset', tags: ['무료'] },
  { name: 'Pexels', url: 'https://www.pexels.com', desc: '무료 사진·영상 소스.', cat: 'asset', tags: ['무료'] },
  { name: 'Freepik', url: 'https://www.freepik.com', desc: '벡터·사진·PSD·목업 종합 소스 사이트.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'Mixkit', url: 'https://mixkit.co', desc: '무료 영상 클립·음악·효과음.', cat: 'asset', tags: ['무료'] },
  { name: 'Coverr', url: 'https://coverr.co', desc: '웹 배경용 무료 영상 소스.', cat: 'asset', tags: ['무료'] },
  { name: 'Mockup World', url: 'https://www.mockupworld.co', desc: '무료 PSD 목업 모음.', cat: 'asset', tags: ['무료'] },
  { name: 'LS Graphics', url: 'https://www.ls.graphics', desc: '고품질 목업·3D 일러스트·UI 킷.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'Shots', url: 'https://shots.so', desc: '스크린샷을 예쁜 목업으로 바로 만들어 주는 툴.', cat: 'asset', tags: ['무료'] },
  { name: 'Haikei', url: 'https://haikei.app', desc: '웨이브, 블롭 등 SVG 배경 생성기.', cat: 'asset', tags: ['무료'] },
  { name: 'Book of Shapes', url: 'https://bookofshapes.com', desc: '격자·노이즈·아이소메트릭 등 값을 조절해 쓰는 제너레이티브 SVG 패턴 모음. 상업적 사용 가능, 출처 표기 불필요.', cat: 'asset', tags: ['무료'] },
  { name: 'Figma Community', url: 'https://www.figma.com/community', desc: 'UI 킷, 아이콘, 템플릿, 플러그인을 무료로 복제해 사용.', cat: 'asset', tags: ['무료'] },
  { name: 'Untitled UI', url: 'https://www.untitledui.com', desc: '가장 널리 쓰이는 Figma UI 킷. 무료 버전도 제공.', cat: 'asset', tags: ['무료', '유료'] },

  /* ---------------- 디자인 개발 ---------------- */
  { name: 'Material Design 3', url: 'https://m3.material.io', desc: '구글 머티리얼 디자인 가이드라인과 컴포넌트.', cat: 'dev', tags: ['무료'] },
  { name: 'Apple HIG', url: 'https://developer.apple.com/design/human-interface-guidelines/', desc: 'iOS·macOS 등 애플 플랫폼 휴먼 인터페이스 가이드라인.', cat: 'dev', tags: ['무료'] },
  { name: 'KRDS 디지털정부서비스 UI/UX', url: 'https://www.krds.go.kr', desc: '한국 디지털 정부서비스 UI/UX 가이드라인. 공공 프로젝트 필수 참고.', cat: 'dev', tags: ['한국', '무료'] },
  { name: 'LINE Design System', url: 'https://designsystem.line.me', desc: '라인의 공개 디자인 시스템.', cat: 'dev', tags: ['무료'] },
  { name: 'Atlassian Design System', url: 'https://atlassian.design', desc: '문서화가 잘 된 디자인 시스템의 교과서.', cat: 'dev', tags: ['무료'] },
  { name: 'Shopify Polaris', url: 'https://shopify.dev/docs/api/polaris', desc: '쇼피파이 디자인 시스템. 콘텐츠 가이드가 특히 좋습니다.', cat: 'dev', tags: ['무료'] },
  { name: 'IBM Carbon', url: 'https://carbondesignsystem.com', desc: 'IBM의 오픈소스 디자인 시스템.', cat: 'dev', tags: ['무료'] },
  { name: 'Ant Design', url: 'https://ant.design', desc: '엔터프라이즈 UI 디자인 언어와 React 컴포넌트.', cat: 'dev', tags: ['무료'] },
  { name: 'Design Systems Repo', url: 'https://designsystemsrepo.com', desc: '공개된 디자인 시스템 모음.', cat: 'dev', tags: ['무료'] },
  { name: 'Component Gallery', url: 'https://component.gallery', desc: '여러 디자인 시스템의 동일 컴포넌트를 비교해 볼 수 있는 갤러리.', cat: 'dev', tags: ['무료'] },
  { name: 'shadcn/ui', url: 'https://ui.shadcn.com', desc: '복사해서 쓰는 React 컴포넌트. 최근 웹 UI의 기본값처럼 쓰입니다.', cat: 'dev', tags: ['무료'] },
  { name: 'Tailwind CSS', url: 'https://tailwindcss.com', desc: '유틸리티 클래스 기반 CSS 프레임워크.', cat: 'dev', tags: ['무료'] },
  { name: 'Radix UI', url: 'https://www.radix-ui.com', desc: '접근성이 보장된 헤드리스 UI 컴포넌트.', cat: 'dev', tags: ['무료'] },
  { name: 'Storybook', url: 'https://storybook.js.org', desc: 'UI 컴포넌트를 독립적으로 개발·문서화하는 툴.', cat: 'dev', tags: ['무료'] },
  { name: 'Zeroheight', url: 'https://zeroheight.com', desc: '디자인 시스템 문서화 플랫폼.', cat: 'dev', tags: ['무료', '유료'] },
  { name: 'Supernova', url: 'https://www.supernova.io', desc: '디자인 토큰 관리와 코드 동기화.', cat: 'dev', tags: ['무료', '유료'] },
  { name: 'Zeplin', url: 'https://zeplin.io', desc: '디자인-개발 핸드오프 툴.', cat: 'dev', tags: ['무료', '유료'] },
  { name: 'Codrops', url: 'https://tympanus.net/codrops/', desc: '고급 웹 인터랙션·애니메이션 데모와 튜토리얼.', cat: 'dev', tags: ['무료'] },
  { name: 'CodePen', url: 'https://codepen.io', desc: '프론트엔드 코드 스니펫 공유 플레이그라운드.', cat: 'dev', tags: ['무료'] },
  { name: 'GSAP', url: 'https://gsap.com', desc: '웹 애니메이션 라이브러리의 표준.', cat: 'dev', tags: ['무료'] },
  { name: 'Motion', url: 'https://motion.dev', desc: 'React·JS용 모던 애니메이션 라이브러리(구 Framer Motion).', cat: 'dev', tags: ['무료'] },
  { name: 'Three.js', url: 'https://threejs.org', desc: '웹 3D 라이브러리. 예제 갤러리가 인스피레이션이 됩니다.', cat: 'dev', tags: ['무료'] },
  { name: 'Easings.net', url: 'https://easings.net', desc: '이징 함수 치트시트.', cat: 'dev', tags: ['무료'] },
  { name: 'cubic-bezier.com', url: 'https://cubic-bezier.com', desc: 'CSS 베지어 이징 커브 시각 편집기.', cat: 'dev', tags: ['무료'] },
  { name: 'Animista', url: 'https://animista.net', desc: 'CSS 애니메이션을 눌러보며 골라 코드 복사.', cat: 'dev', tags: ['무료'] },
  { name: 'MDN Web Docs', url: 'https://developer.mozilla.org/ko/', desc: 'HTML·CSS·JS 공식 레퍼런스 문서.', cat: 'dev', tags: ['무료'] },
  { name: 'CSS-Tricks', url: 'https://css-tricks.com', desc: 'CSS 기법 아티클과 가이드.', cat: 'dev', tags: ['무료'] },
  { name: 'Can I Use', url: 'https://caniuse.com', desc: '브라우저별 CSS·JS 기능 지원 여부 확인.', cat: 'dev', tags: ['무료'] },
  { name: 'WCAG 2.2 Quick Reference', url: 'https://www.w3.org/WAI/WCAG22/quickref/', desc: '웹 접근성 지침 빠른 참조.', cat: 'dev', tags: ['무료'] },
  { name: 'Responsively', url: 'https://responsively.app', desc: '여러 기기 화면을 동시에 보며 반응형을 확인하는 브라우저.', cat: 'dev', tags: ['무료'] },

  /* ---------------- 디자인 툴 ---------------- */
  { name: 'Figma', url: 'https://www.figma.com', desc: 'UI 디자인·프로토타이핑·협업의 표준 툴.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Framer', url: 'https://www.framer.com', desc: '디자인하듯 웹사이트를 만들어 바로 배포하는 노코드 빌더.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Webflow', url: 'https://webflow.com', desc: 'CMS까지 갖춘 비주얼 웹 빌더.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'ProtoPie', url: 'https://www.protopie.io', desc: '코드 없이 고급 인터랙션을 만드는 국산 프로토타이핑 툴.', cat: 'tool', tags: ['한국', '유료'] },
  { name: 'Rive', url: 'https://rive.app', desc: '인터랙티브 벡터 애니메이션 제작 툴.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Spline', url: 'https://spline.design', desc: '웹용 3D 디자인 툴. 인터랙티브 3D를 쉽게 제작.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Adobe Creative Cloud', url: 'https://www.adobe.com/kr/', desc: '포토샵, 일러스트레이터, 인디자인 등.', cat: 'tool', tags: ['유료'] },
  { name: 'Affinity', url: 'https://www.affinity.studio', desc: '어도비 대안 그래픽 툴. 2025년 캔바 인수 후 무료로 전환.', cat: 'tool', tags: ['유료'] },
  { name: 'Canva', url: 'https://www.canva.com', desc: '템플릿 기반 간편 디자인 툴.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Photopea', url: 'https://www.photopea.com', desc: '브라우저에서 돌아가는 무료 포토샵 대체 툴.', cat: 'tool', tags: ['무료'] },
  { name: 'Procreate', url: 'https://procreate.com', desc: 'iPad 드로잉·페인팅 앱.', cat: 'tool', tags: ['유료'] },
  { name: 'Blender', url: 'https://www.blender.org', desc: '무료 오픈소스 3D 제작 툴.', cat: 'tool', tags: ['무료'] },
  { name: 'Glyphs', url: 'https://glyphsapp.com', desc: '맥용 폰트 제작 툴. 한글 폰트 제작에도 널리 사용.', cat: 'tool', tags: ['유료'] },
  { name: 'FontForge', url: 'https://fontforge.org', desc: '무료 오픈소스 폰트 에디터.', cat: 'tool', tags: ['무료'] },
  { name: 'Miro', url: 'https://miro.com', desc: '온라인 화이트보드. 워크숍·리서치 정리.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Whimsical', url: 'https://whimsical.com', desc: '와이어프레임·플로우차트·마인드맵을 빠르게 그리는 툴.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Excalidraw', url: 'https://excalidraw.com', desc: '손그림 느낌의 무료 다이어그램 툴.', cat: 'tool', tags: ['무료'] },
  { name: 'Notion', url: 'https://www.notion.com', desc: '문서·프로젝트 관리. 포트폴리오 페이지로도 활용.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Maze', url: 'https://maze.co', desc: '프로토타입 사용성 테스트·설문 플랫폼.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Hotjar', url: 'https://contentsquare.com/hotjar/', desc: '히트맵·세션 녹화로 실제 사용자 행동 분석. 현재 Contentsquare에 합류.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'TinyPNG', url: 'https://tinypng.com', desc: 'PNG·JPG·WebP 이미지 압축.', cat: 'tool', tags: ['무료'] },
  { name: 'Squoosh', url: 'https://squoosh.app', desc: '구글의 브라우저 이미지 압축·변환 툴.', cat: 'tool', tags: ['무료'] },
  { name: 'remove.bg', url: 'https://www.remove.bg', desc: '이미지 배경을 자동으로 제거.', cat: 'tool', tags: ['무료', '유료', 'AI'] },
  { name: 'Screen Studio', url: 'https://screen.studio', desc: '자동 줌·모션이 들어간 세련된 화면 녹화(맥).', cat: 'tool', tags: ['유료'] },
  { name: 'CleanShot X', url: 'https://cleanshot.com', desc: '맥용 스크린샷·녹화 툴.', cat: 'tool', tags: ['유료'] },

  /* ---------------- 외주 / 프리랜서 ---------------- */
  { name: '크몽', url: 'https://kmong.com', desc: '국내 최대 프리랜서 마켓. 디자인 카테고리가 가장 활발합니다.', cat: 'freelance', tags: ['한국'] },
  { name: '숨고', url: 'https://soomgo.com', desc: '견적 요청 기반 전문가 매칭 플랫폼.', cat: 'freelance', tags: ['한국'] },
  { name: '위시켓', url: 'https://www.wishket.com', desc: 'IT·디자인 프로젝트 아웃소싱 플랫폼. 규모 있는 프로젝트가 많습니다.', cat: 'freelance', tags: ['한국'] },
  { name: '프리모아', url: 'https://www.freemoa.net', desc: '프리랜서 프로젝트 매칭 플랫폼.', cat: 'freelance', tags: ['한국'] },
  { name: '라우드소싱', url: 'https://www.loud.kr', desc: '로고·네이밍·패키지 디자인 콘테스트 플랫폼.', cat: 'freelance', tags: ['한국'] },
  { name: '이랜서', url: 'https://www.elancer.co.kr', desc: 'IT 프리랜서 매칭. 상주 프로젝트가 많습니다.', cat: 'freelance', tags: ['한국'] },
  { name: '원티드 긱스', url: 'https://www.wanted.co.kr/gigs', desc: '원티드의 프리랜서·긱 프로젝트 매칭.', cat: 'freelance', tags: ['한국'] },
  { name: '디자인DB (한국디자인진흥원)', url: 'https://www.designdb.com', desc: '디자인 표준 대가 기준, 표준계약서 등 외주 시 참고할 공식 자료.', cat: 'freelance', tags: ['한국', '무료'] },
  { name: 'Upwork', url: 'https://www.upwork.com', desc: '글로벌 프리랜서 플랫폼. 해외 클라이언트와 작업.', cat: 'freelance', tags: [] },
  { name: 'Fiverr', url: 'https://www.fiverr.com', desc: '서비스 단위로 판매하는 글로벌 프리랜서 마켓.', cat: 'freelance', tags: [] },
  { name: 'Toptal', url: 'https://www.toptal.com', desc: '상위 프리랜서만 선별하는 프리미엄 매칭.', cat: 'freelance', tags: [] },
  { name: '99designs', url: 'https://99designs.com', desc: '디자인 콘테스트·1:1 프로젝트 플랫폼.', cat: 'freelance', tags: [] },
  { name: 'Contra', url: 'https://contra.com', desc: '수수료 없는 독립 프리랜서 플랫폼. 포트폴리오 기능 포함.', cat: 'freelance', tags: [] },

  /* ---------------- 채용공고 ---------------- */
  { name: '원티드', url: 'https://www.wanted.co.kr', desc: 'IT·스타트업 채용의 중심. 프로덕트 디자이너 공고가 많습니다.', cat: 'job', tags: ['한국'] },
  { name: '사람인', url: 'https://www.saramin.co.kr', desc: '국내 대표 채용 사이트.', cat: 'job', tags: ['한국'] },
  { name: '잡코리아', url: 'https://www.jobkorea.co.kr', desc: '국내 대표 채용 사이트.', cat: 'job', tags: ['한국'] },
  { name: '로켓펀치', url: 'https://www.rocketpunch.com', desc: '스타트업 채용·비즈니스 네트워크.', cat: 'job', tags: ['한국'] },
  { name: '디자이너잡', url: 'https://www.designerjob.co.kr', desc: '디자이너 전문 채용 사이트.', cat: 'job', tags: ['한국'] },
  { name: '랠릿', url: 'https://www.rallit.com', desc: '인크루트의 IT·디자인 직군 채용 플랫폼.', cat: 'job', tags: ['한국'] },
  { name: '리멤버', url: 'https://www.rememberapp.co.kr', desc: '명함 앱 기반 경력직 채용 제안.', cat: 'job', tags: ['한국'] },
  { name: '잡플래닛', url: 'https://www.jobplanet.co.kr', desc: '기업 리뷰·연봉 정보. 지원 전 회사 분위기 확인.', cat: 'job', tags: ['한국'] },
  { name: '캐치', url: 'https://www.catch.co.kr', desc: '기업 정보·채용 공고·취업 준비 정보.', cat: 'job', tags: ['한국'] },
  { name: '블라인드', url: 'https://www.teamblind.com/kr', desc: '익명 직장인 커뮤니티. 회사 내부 이야기 참고.', cat: 'job', tags: ['한국'] },
  { name: '인디드', url: 'https://kr.indeed.com', desc: '글로벌 채용 검색 엔진의 한국판.', cat: 'job', tags: ['한국'] },
  { name: 'LinkedIn Jobs', url: 'https://www.linkedin.com/jobs/', desc: '글로벌·외국계 기업 채용.', cat: 'job', tags: [] },
  { name: 'Dribbble Jobs', url: 'https://dribbble.com/jobs', desc: '해외 디자인 채용 보드.', cat: 'job', tags: [] },
  { name: 'Behance Jobs', url: 'https://www.behance.net/joblist', desc: '비핸스 채용 공고.', cat: 'job', tags: [] },
  { name: 'Working Not Working', url: 'https://workingnotworking.com', desc: '크리에이티브 전문 인재·채용 플랫폼.', cat: 'job', tags: [] },
  { name: 'UX Jobs Board', url: 'https://uxjobsboard.com', desc: 'UX 직군 전문 채용 보드.', cat: 'job', tags: [] },
  { name: 'Remote OK', url: 'https://remoteok.com', desc: '원격 근무 채용 모음. 디자인 카테고리 제공.', cat: 'job', tags: [] },

  /* ---------------- AI ---------------- */
  { name: 'Midjourney', url: 'https://www.midjourney.com', desc: '가장 널리 쓰이는 이미지 생성 AI. 스타일 레퍼런스 기능이 강력.', cat: 'ai', tags: ['유료', 'AI'], sub: '이미지 생성' },
  { name: 'ChatGPT', url: 'https://chatgpt.com', desc: 'OpenAI의 대화형 AI. 이미지 생성·기획·카피 작성.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Claude', url: 'https://claude.ai', desc: 'Anthropic의 대화형 AI. 긴 문서 작업·코드 작성에 강점.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Adobe Firefly', url: 'https://firefly.adobe.com', desc: '상업적 사용이 안전한 어도비 생성형 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Ideogram', url: 'https://ideogram.ai', desc: '텍스트 렌더링에 강한 이미지 생성 AI. 포스터·로고 시안.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Recraft', url: 'https://www.recraft.ai', desc: '벡터·브랜드 스타일 일관성에 특화된 이미지 생성 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Leonardo.Ai', url: 'https://leonardo.ai', desc: '게임·컨셉 아트에 강한 이미지 생성 플랫폼.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Krea', url: 'https://www.krea.ai', desc: '실시간 생성·업스케일·영상까지 지원하는 크리에이티브 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Civitai', url: 'https://civitai.com', desc: 'Stable Diffusion 모델·LoRA 공유 커뮤니티.', cat: 'ai', tags: ['무료', 'AI'], sub: '이미지 생성' },
  { name: 'Runway', url: 'https://runway.com', desc: '영상 생성·편집 AI의 선두주자.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Luma Dream Machine', url: 'https://lumalabs.ai', desc: '이미지·영상 생성 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Kling', url: 'https://kling.ai', desc: '고품질 영상 생성 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Sora', url: 'https://sora.chatgpt.com', desc: 'OpenAI의 영상 생성 AI.', cat: 'ai', tags: ['유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Google Stitch', url: 'https://stitch.withgoogle.com', desc: '프롬프트로 UI 화면을 생성하고 Figma로 내보내는 구글 툴.', cat: 'ai', tags: ['무료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Uizard', url: 'https://uizard.io', desc: '텍스트·스케치로 UI 프로토타입 생성.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Relume', url: 'https://www.relume.ai', desc: 'AI로 사이트맵·와이어프레임을 만들고 Figma·Webflow로 내보내기.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Figma Make', url: 'https://www.figma.com/make/', desc: '프롬프트로 동작하는 프로토타입을 만드는 Figma의 AI 기능.', cat: 'ai', tags: ['유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'v0', url: 'https://v0.app', desc: 'Vercel의 UI 코드 생성 AI. React·Tailwind 컴포넌트 생성.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Lovable', url: 'https://lovable.dev', desc: '대화로 풀스택 웹 앱을 만드는 AI 빌더.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Bolt', url: 'https://bolt.new', desc: '브라우저에서 프롬프트로 웹 앱을 만들고 배포.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Cursor', url: 'https://cursor.com', desc: 'AI 코드 에디터. 디자이너의 코드 작업 진입 장벽을 낮춥니다.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Claude Code', url: 'https://claude.com/product/claude-code', desc: '터미널·데스크톱에서 코드를 작성·수정하는 Anthropic의 에이전트.', cat: 'ai', tags: ['유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'Magnific', url: 'https://www.magnific.com', desc: '디테일을 살려주는 AI 업스케일러.', cat: 'ai', tags: ['유료', 'AI'], sub: '이미지 편집 · 업스케일' },
  { name: 'Upscayl', url: 'https://upscayl.org', desc: '무료 오픈소스 AI 이미지 업스케일러.', cat: 'ai', tags: ['무료', 'AI'], sub: '이미지 편집 · 업스케일' },
  { name: 'Clipdrop', url: 'https://clipdrop.co', desc: '배경 제거, 조명 변경, 확장 등 AI 이미지 편집 툴 모음.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 편집 · 업스케일' },
  { name: 'Vizcom', url: 'https://vizcom.com', desc: '스케치를 렌더링 이미지로 바꿔주는 산업 디자인용 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Looka', url: 'https://looka.com', desc: 'AI 로고·브랜드 킷 생성.', cat: 'ai', tags: ['유료', 'AI'], sub: '이미지 생성' },
  { name: 'Gamma', url: 'https://gamma.app', desc: 'AI 프레젠테이션·문서·웹페이지 생성.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '문서 · 프레젠테이션' },
  { name: 'Napkin', url: 'https://www.napkin.ai', desc: '텍스트를 다이어그램·인포그래픽으로 변환.', cat: 'ai', tags: ['무료', 'AI'], sub: '문서 · 프레젠테이션' },
  { name: 'ElevenLabs', url: 'https://elevenlabs.io', desc: 'AI 음성 합성. 영상·프로토타입 내레이션.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '오디오 · 음성' },
  { name: 'Suno', url: 'https://suno.com', desc: 'AI 음악 생성.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '오디오 · 음성' },
  { name: 'Perplexity', url: 'https://www.perplexity.ai', desc: '출처를 함께 보여주는 AI 검색.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '리서치 · 모델 허브' },
  { name: 'NotebookLM', url: 'https://notebooklm.google.com', desc: '자료를 올리면 요약·질문·팟캐스트로 정리해 주는 구글 AI.', cat: 'ai', tags: ['무료', 'AI'], sub: '리서치 · 모델 허브' },
  { name: '뤼튼', url: 'https://wrtn.ai', desc: '국산 AI 포털. 여러 모델을 한곳에서 무료로 사용.', cat: 'ai', tags: ['한국', '무료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Hugging Face', url: 'https://huggingface.co', desc: '오픈소스 AI 모델·데모 허브.', cat: 'ai', tags: ['무료', 'AI'], sub: '리서치 · 모델 허브' },

  /* ---------------- 커뮤니티 / 매거진 ---------------- */
  { name: '디자인정글', url: 'https://www.jungle.co.kr', desc: '국내 디자인 뉴스·칼럼·전시 소식. 디자인 분야 채용 정보도 제공.', cat: 'community', tags: ['한국', '무료'] },
  { name: '월간 디자인', url: 'https://mdesign.designhouse.co.kr', desc: '디자인하우스의 월간 디자인 매거진.', cat: 'community', tags: ['한국'] },
  { name: '디자인프레스', url: 'https://blog.naver.com/designpress2016', desc: '네이버 디자인프레스. 국내 디자이너 인터뷰·이슈.', cat: 'community', tags: ['한국', '무료'] },
  { name: '서핏', url: 'https://www.surfit.io', desc: '디자이너·개발자 아티클 큐레이션. 새 탭 확장 프로그램 제공.', cat: 'community', tags: ['한국', '무료'] },
  { name: '요즘IT', url: 'https://yozm.wishket.com', desc: '위시켓의 IT·디자인 아티클 매거진.', cat: 'community', tags: ['한국', '무료'] },
  { name: '디스콰이엇', url: 'https://disquiet.io', desc: '프로덕트 메이커 커뮤니티. 사이드 프로젝트 공유.', cat: 'community', tags: ['한국', '무료'] },
  { name: '커리어리', url: 'https://careerly.co.kr', desc: '현직자 인사이트를 공유하는 커리어 SNS.', cat: 'community', tags: ['한국', '무료'] },
  { name: '브런치', url: 'https://brunch.co.kr', desc: '디자이너들의 에세이·회고가 많은 글 플랫폼.', cat: 'community', tags: ['한국', '무료'] },
  { name: '토스 기술 블로그', url: 'https://toss.tech', desc: '토스의 디자인·개발 아티클.', cat: 'community', tags: ['한국', '무료'] },
  { name: '디자인베이스', url: 'https://designbase.co.kr', desc: '디자인 툴 강의·아티클. 입문자에게 좋습니다.', cat: 'community', tags: ['한국', '무료'] },
  { name: 'Coloso', url: 'https://coloso.co.kr', desc: '현업 디자이너·아티스트의 온라인 강의.', cat: 'community', tags: ['한국', '유료'] },
  { name: '인프런', url: 'https://www.inflearn.com', desc: 'IT·디자인 온라인 강의 플랫폼.', cat: 'community', tags: ['한국', '무료', '유료'] },
  { name: '패스트캠퍼스', url: 'https://fastcampus.co.kr', desc: '실무 중심 온라인 강의.', cat: 'community', tags: ['한국', '유료'] },
  { name: '클래스101', url: 'https://class101.net', desc: '취미·실무 크리에이티브 강의 구독.', cat: 'community', tags: ['한국', '유료'] },
  { name: 'Layers', url: 'https://layers.to', desc: '디자이너 커뮤니티·포트폴리오 플랫폼.', cat: 'community', tags: ['무료'] },
  { name: 'Product Hunt', url: 'https://www.producthunt.com', desc: '새로운 프로덕트·툴이 매일 올라오는 커뮤니티.', cat: 'community', tags: ['무료'] },
  { name: 'Sidebar', url: 'https://sidebar.io', desc: '매일 5개의 디자인 링크를 보내주는 뉴스레터.', cat: 'community', tags: ['무료'] },
  { name: 'UX Collective', url: 'https://uxdesign.cc', desc: 'Medium 최대 UX 퍼블리케이션.', cat: 'community', tags: ['무료'] },
  { name: 'UX Planet', url: 'https://uxplanet.org', desc: 'UX 아티클 퍼블리케이션.', cat: 'community', tags: ['무료'] },
  { name: 'Smashing Magazine', url: 'https://www.smashingmagazine.com', desc: '웹 디자인·프론트엔드 심층 아티클.', cat: 'community', tags: ['무료'] },
  { name: 'Figma Blog', url: 'https://www.figma.com/blog/', desc: 'Figma의 디자인·프로덕트 아티클.', cat: 'community', tags: ['무료'] },
  { name: 'Eye on Design', url: 'https://eyeondesign.aiga.org', desc: 'AIGA의 그래픽 디자인 매거진.', cat: 'community', tags: ['무료'] },
  { name: 'Creative Boom', url: 'https://www.creativeboom.com', desc: '크리에이티브 산업 뉴스·인터뷰.', cat: 'community', tags: ['무료'] },
  { name: 'Dezeen', url: 'https://www.dezeen.com', desc: '건축·인테리어·제품 디자인 매거진.', cat: 'community', tags: ['무료'] },
  { name: 'Design Milk', url: 'https://design-milk.com', desc: '모던 디자인·아트·인테리어 매거진.', cat: 'community', tags: ['무료'] },
  { name: 'Refactoring UI', url: 'https://www.refactoringui.com', desc: '개발자·디자이너를 위한 실전 UI 디자인 책.', cat: 'community', tags: ['유료'] },
  { name: 'Interaction Design Foundation', url: 'https://ixdf.org', desc: 'UX 이론·강의를 제공하는 비영리 교육 기관.', cat: 'community', tags: ['유료'] },

  /* ---------- 크리에이터 / 채널 (유튜브 · 인스타그램 · 팟캐스트) ---------- */
  { name: 'The Futur (Chris Do)', url: 'https://www.youtube.com/@thefutur', desc: '디자인 비즈니스, 클라이언트 협상, 브랜딩 전략. 디자이너 채널 중 가장 큰 규모.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Flux Academy (Ran Segall)', url: 'https://www.youtube.com/@FluxAcademy', desc: '웹 디자인 실무와 프리랜서 운영. Figma·Webflow 튜토리얼.', cat: 'creator', tags: ['유튜브'] },
  { name: 'DesignCourse (Gary Simon)', url: 'https://www.youtube.com/@DesignCourse', desc: 'UI 디자인과 프론트엔드를 함께 다루는 채널.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Satori Graphics', url: 'https://www.youtube.com/@SatoriGraphics', desc: '로고·그래픽 디자인 이론과 일러스트레이터 팁.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Will Paterson', url: 'https://www.youtube.com/@WillPaterson', desc: '로고 디자인과 핸드 레터링, 브랜딩 프로세스.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Dansky', url: 'https://www.youtube.com/@ForeverDansky', desc: '어도비·Figma 등 툴 사용법을 짧고 명확하게.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Mizko', url: 'https://www.youtube.com/@Mizko', desc: '프로덕트 디자인 실무, Figma 고급 활용, 커리어.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Malewicz', url: 'https://www.youtube.com/@MalewiczHype', desc: 'UI 디자인 팁과 트렌드 비평. 짧고 직설적인 영상.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Juxtopposed', url: 'https://www.youtube.com/@juxtopposed', desc: 'UI/UX 리디자인 케이스 스터디. 유머와 완성도 높은 편집.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Jesse Showalter', url: 'https://www.youtube.com/@JesseShowalter', desc: 'UI/UX 디자인 입문, 포트폴리오, 툴 튜토리얼.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Linus Boman', url: 'https://www.youtube.com/@LinusBoman', desc: '타이포그래피와 로고에 대한 비디오 에세이. 서체 역사와 비평.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Yes I\'m a Designer', url: 'https://www.youtube.com/@yesimadesigner', desc: '어도비 공인 강사 마틴 페르히니악의 포토샵·일러스트 튜토리얼.', cat: 'creator', tags: ['유튜브'] },
  { name: 'PiXimperfect', url: 'https://www.youtube.com/@PiXimperfect', desc: '포토샵 리터칭·합성의 교과서 같은 채널.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Abi Connick', url: 'https://www.youtube.com/@AbiConnick', desc: '브랜딩 디자이너의 프로세스, 프리랜서 팁, 클라이언트 작업 공개.', cat: 'creator', tags: ['유튜브'] },
  { name: 'The Design Theory', url: 'https://www.youtube.com/@TheDesignTheory', desc: '디자인 이론·역사·비평 중심의 에세이 채널.', cat: 'creator', tags: ['유튜브'] },
  { name: 'tutvid (Nathaniel Dodson)', url: 'https://www.youtube.com/@tutvid', desc: '포토샵·일러스트레이터·프리미어 심화 튜토리얼.', cat: 'creator', tags: ['유튜브'] },
  { name: 'CharliMarieTV', url: 'https://www.youtube.com/@CharliMarieTV', desc: '디자이너의 일상, 커리어, 포트폴리오 이야기.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Photoshop Training Channel', url: 'https://www.youtube.com/@PhotoshopTrainingChannel', desc: '포토샵 기능을 깊이 파는 튜토리얼 채널.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Femke', url: 'https://www.youtube.com/@femkedesign', desc: '프로덕트 디자이너의 실무 이야기와 커리어 조언.', cat: 'creator', tags: ['유튜브'] },
  { name: 'AJ&Smart', url: 'https://www.youtube.com/@AJSmart', desc: '디자인 스프린트와 워크숍 퍼실리테이션.', cat: 'creator', tags: ['유튜브'] },
  { name: 'NNgroup', url: 'https://www.youtube.com/@NNgroup', desc: '닐슨 노먼 그룹의 UX 리서치 짧은 강의.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Google Design', url: 'https://www.youtube.com/@GoogleDesign', desc: '구글 디자인 팀의 토크와 머티리얼 디자인 이야기.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Figma', url: 'https://www.youtube.com/@Figma', desc: 'Figma 공식 채널. 신기능, Config 컨퍼런스 세션.', cat: 'creator', tags: ['유튜브'] },
  { name: 'AIGA', url: 'https://www.youtube.com/@AIGAdesign', desc: '미국 그래픽 디자인 협회의 디자인 컨퍼런스 강연.', cat: 'creator', tags: ['유튜브'] },
  { name: "It's Nice That (YouTube)", url: 'https://www.youtube.com/@ItsNiceThat', desc: '크리에이티브 인터뷰와 스튜디오 방문 영상.', cat: 'creator', tags: ['유튜브'] },
  { name: 'Gobird Masterclass', url: 'https://www.youtube.com/@gobirdmasterclass', desc: '그래픽 디자인 스타일·레이아웃을 짧게 정리하는 채널. 인스타 릴스로 유명.', cat: 'creator', tags: ['유튜브', '인스타그램'] },
  { name: '디자인베이스', url: 'https://www.youtube.com/@designbase', desc: '디자인 툴 강의와 실무 팁. 국내 입문자에게 가장 알려진 채널.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '빠르크의 3분 강좌', url: 'https://www.youtube.com/@Park3min', desc: '포토샵·프리미어 등 툴 기능을 3분 안에 설명.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '디자인 스펙트럼', url: 'https://www.youtube.com/@designspectrum', desc: '국내 디자이너 커뮤니티의 컨퍼런스·토크 영상.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '안그라픽스', url: 'https://www.youtube.com/@ahngraphics', desc: '디자인 전문 출판사 안그라픽스의 책·저자 이야기.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '노트폴리오 (YouTube)', url: 'https://www.youtube.com/@notefolio', desc: '노트폴리오의 디자이너 인터뷰와 강연.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '디자인정글 (YouTube)', url: 'https://www.youtube.com/@designjungle', desc: '디자인정글의 전시·디자이너 소개 영상.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: '라우드소싱 (YouTube)', url: 'https://www.youtube.com/@loudsourcing', desc: '디자인 콘테스트 플랫폼의 디자이너 인터뷰·팁.', cat: 'creator', tags: ['한국', '유튜브'] },
  { name: 'Gobird (Instagram)', url: 'https://www.instagram.com/gobirdmasterclass/', desc: '디자인 스타일과 원칙을 카드·릴스로 정리하는 계정.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Posterlad', url: 'https://www.instagram.com/posterlad/', desc: '모하메드 사미르의 매일 포스터 프로젝트.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Typo/Graphic Posters', url: 'https://www.instagram.com/typo_graphic_posters/', desc: '타이포그래피 포스터 아카이브 계정.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Logo Inspirations', url: 'https://www.instagram.com/logoinspirations/', desc: '로고 디자인 큐레이션 계정.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Pentagram', url: 'https://www.instagram.com/pentagramdesign/', desc: '세계 최대 독립 디자인 스튜디오의 작업 공개.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Studio Feixen', url: 'https://www.instagram.com/studiofeixen/', desc: '스위스 스튜디오의 실험적 타이포·모션 그래픽.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Brand New (Instagram)', url: 'https://www.instagram.com/brand.new/', desc: '브랜드 리뉴얼 리뷰 매체의 인스타그램.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'The Design Tip', url: 'https://www.instagram.com/thedesigntip/', desc: '그래픽 디자인 팁과 레퍼런스 큐레이션.', cat: 'creator', tags: ['인스타그램'] },
  { name: 'Graphic Design Central', url: 'https://www.instagram.com/graphicdesigncentral/', desc: '그래픽 디자인 작업물 큐레이션 계정.', cat: 'creator', tags: ['인스타그램'] },
  { name: "It's Nice That (Instagram)", url: 'https://www.instagram.com/itsnicethat/', desc: '크리에이티브 매거진의 데일리 큐레이션.', cat: 'creator', tags: ['인스타그램'] },
  { name: '노트폴리오 (Instagram)', url: 'https://www.instagram.com/notefolio_official/', desc: '국내 디자이너 작업물 소개 계정.', cat: 'creator', tags: ['한국', '인스타그램'] },
  { name: '디자인정글 (Instagram)', url: 'https://www.instagram.com/designjungle/', desc: '디자인 뉴스와 전시 소식.', cat: 'creator', tags: ['한국', '인스타그램'] },
  { name: 'Design Matters (Debbie Millman)', url: 'https://www.designmattersmedia.com', desc: '가장 오래된 디자인 팟캐스트. 디자이너·작가 인터뷰.', cat: 'creator', tags: ['팟캐스트'] },
  { name: 'Design Details', url: 'https://designdetails.fm', desc: '프로덕트 디자이너 두 명의 실무 이야기 팟캐스트.', cat: 'creator', tags: ['팟캐스트'] },
  /* ---- 추가 (2026-09 검증) ---- */
  { name: 'Grok (xAI)', url: 'https://grok.com', desc: 'xAI의 대화형 AI. 실시간 X(트위터) 정보와 이미지 생성 기능.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Gemini', url: 'https://gemini.google.com', desc: '구글의 대화형 AI. 이미지 생성·편집(나노 바나나)과 딥 리서치가 강점.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Microsoft Copilot', url: 'https://copilot.microsoft.com', desc: '마이크로소프트의 AI 비서. 오피스·윈도우와 통합.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'DeepSeek', url: 'https://chat.deepseek.com', desc: '오픈 웨이트 모델로 주목받은 중국의 대화형 AI.', cat: 'ai', tags: ['무료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Mistral Le Chat', url: 'https://chat.mistral.ai', desc: '유럽 미스트랄의 대화형 AI. 빠른 응답과 문서 처리.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Qwen', url: 'https://chat.qwen.ai', desc: '알리바바의 대화형 AI. 이미지·영상 생성까지 한곳에서.', cat: 'ai', tags: ['무료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Meta AI', url: 'https://www.meta.ai', desc: '메타의 대화형 AI. 이미지 생성과 인스타그램·왓츠앱 연동.', cat: 'ai', tags: ['무료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Manus', url: 'https://manus.im', desc: '작업을 끝까지 대신 수행하는 자율 에이전트. 리서치·슬라이드·웹 제작.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'LLM · 대화형' },
  { name: 'Stability AI', url: 'https://stability.ai', desc: 'Stable Diffusion 개발사. 오픈 이미지·영상·오디오 모델.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'FLUX (Black Forest Labs)', url: 'https://bfl.ai', desc: '오픈 이미지 생성 모델 FLUX. 사실적인 이미지와 정확한 텍스트 렌더링.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Playground', url: 'https://playground.com', desc: '로고·포스터·SNS 그래픽을 템플릿 기반으로 생성하는 AI 디자인 툴.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'ComfyUI', url: 'https://www.comfy.org', desc: '노드 기반 오픈소스 이미지·영상 생성 워크플로 툴. 로컬에서 실행.', cat: 'ai', tags: ['무료', 'AI'], sub: '이미지 생성' },
  { name: 'Kittl', url: 'https://www.kittl.com', desc: 'AI 기능이 통합된 브라우저 그래픽 디자인 툴. 로고·티셔츠·포스터.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Freepik AI Suite', url: 'https://www.freepik.com/ai', desc: '프리픽의 AI 이미지·영상 생성 모음. 여러 모델을 한곳에서.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '이미지 생성' },
  { name: 'Topaz Labs', url: 'https://www.topazlabs.com', desc: '사진·영상 업스케일과 노이즈 제거의 표준 툴.', cat: 'ai', tags: ['유료', 'AI'], sub: '이미지 편집 · 업스케일' },
  { name: 'Google Flow (Veo)', url: 'https://labs.google/fx/tools/flow', desc: '구글 Veo 모델로 영상을 만드는 AI 영화 제작 툴.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Pika', url: 'https://pika.art', desc: '짧은 영상 생성·편집 AI. 효과와 립싱크 기능.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Hailuo', url: 'https://hailuoai.video', desc: 'MiniMax의 영상 생성 AI. 자연스러운 인물 동작.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Higgsfield', url: 'https://higgsfield.ai', desc: '카메라 무빙 프리셋으로 시네마틱 영상을 만드는 AI.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'HeyGen', url: 'https://www.heygen.com', desc: 'AI 아바타·더빙 영상 생성. 다국어 립싱크.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Synthesia', url: 'https://www.synthesia.io', desc: '기업용 AI 아바타 영상 제작 플랫폼.', cat: 'ai', tags: ['유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'CapCut', url: 'https://www.capcut.com', desc: 'AI 자막·배경 제거·템플릿이 강한 영상 편집기. 모바일·데스크톱.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Descript', url: 'https://www.descript.com', desc: '텍스트를 고치듯 영상·팟캐스트를 편집하는 AI 편집기.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Swishy', url: 'https://www.swishy.ai', desc: '말로 설명하면 텍스트·로고·UI 애니메이션을 만들어 주는 AI 모션 디자이너.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '영상 생성 · 편집' },
  { name: 'Udio', url: 'https://www.udio.com', desc: 'AI 음악 생성. Suno와 양대 산맥.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: '오디오 · 음성' },
  { name: 'Replit', url: 'https://replit.com', desc: '브라우저에서 AI 에이전트로 앱을 만들고 바로 배포.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },
  { name: 'GitHub Copilot', url: 'https://github.com/features/copilot', desc: '가장 널리 쓰이는 AI 코딩 어시스턴트. VS Code 등에 통합.', cat: 'ai', tags: ['무료', '유료', 'AI'], sub: 'UI · 코드 생성' },

  { name: 'Toools.design', url: 'https://www.toools.design', desc: '디자인 리소스·툴 1,500개 이상을 모아둔 디렉터리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Landingfolio', url: 'https://www.landingfolio.com', desc: '랜딩페이지·컴포넌트 인스피레이션. 섹션별 검색.', cat: 'uiux', tags: ['무료'] },
  { name: 'Supahero', url: 'https://supahero.io', desc: '웹사이트 첫 화면(히어로 섹션)만 골라 모은 갤러리. 랜딩페이지의 첫인상을 잡을 때 좋습니다.', cat: 'uiux', tags: ['무료'] },
  { name: 'CSS Design Awards', url: 'https://www.cssdesignawards.com', desc: 'Awwwards와 함께 대표적인 웹 디자인 어워드.', cat: 'uiux', tags: ['무료'] },
  { name: 'FWA', url: 'https://thefwa.com', desc: '2000년부터 이어진 인터랙티브 웹 어워드.', cat: 'uiux', tags: ['무료'] },
  { name: 'One Page Love', url: 'https://onepagelove.com', desc: '원페이지 웹사이트 갤러리와 템플릿.', cat: 'uiux', tags: ['무료'] },
  { name: 'Bento Grids', url: 'https://bentogrids.com', desc: '벤토 그리드 레이아웃 레퍼런스 모음.', cat: 'uiux', tags: ['무료'] },
  { name: 'UX Archive', url: 'https://uxarchive.com', desc: '모바일 앱 유저 플로우를 단계별 스크린샷으로 정리.', cat: 'uiux', tags: ['무료'] },
  { name: 'Really Good UX', url: 'https://goodux.appcues.com', desc: '온보딩·엠프티 스테이트 등 잘 만든 UX 사례 모음.', cat: 'uiux', tags: ['무료'] },
  { name: 'UI8', url: 'https://ui8.net', desc: '프리미엄 UI 킷·아이콘·3D 에셋 마켓.', cat: 'uiux', tags: ['유료'] },
  { name: 'Ripplix', url: 'https://www.ripplix.com', desc: '실제 앱·웹에서 모은 UI 애니메이션과 마이크로 인터랙션 7,000여 개. 요소·업종·서비스별로 찾아볼 수 있습니다.', cat: 'uiux', tags: ['무료', '유료'] },

  { name: 'Mindsparkle Mag', url: 'https://mindsparklemag.com', desc: '브랜딩·웹 디자인 큐레이션 매거진.', cat: 'graphic', tags: ['무료'] },
  { name: 'Gurafiku', url: 'https://gurafiku.tumblr.com', desc: '일본 그래픽 디자인 아카이브.', cat: 'graphic', tags: ['무료'] },

  { name: 'Muzli Colors', url: 'https://colors.muz.li', desc: '팔레트 생성과 실제 UI·일러스트 적용 미리보기.', cat: 'color', tags: ['무료'] },
  { name: 'ColorKit', url: 'https://colorkit.co', desc: '팔레트 생성기와 인기 팔레트, 컬러 도구 모음.', cat: 'color', tags: ['무료'] },

  { name: 'DaFont', url: 'https://www.dafont.com', desc: '개인용 무료 폰트가 가장 많은 사이트. 라이선스 확인 필수.', cat: 'typo', tags: ['무료'] },
  { name: 'Font Squirrel', url: 'https://www.fontsquirrel.com', desc: '상업용 무료 폰트만 골라 모은 사이트. 웹폰트 변환기 제공.', cat: 'typo', tags: ['무료'] },
  { name: 'Pangram Pangram', url: 'https://pangrampangram.com', desc: '트렌디한 서체를 개인용 무료로 배포하는 파운드리.', cat: 'typo', tags: ['무료', '유료'] },
  { name: 'Klim Type Foundry', url: 'https://klim.co.nz', desc: '뉴질랜드의 서체 파운드리. 브랜딩에 자주 쓰이는 고급 서체.', cat: 'typo', tags: ['유료'] },

  { name: 'Icons8', url: 'https://icons8.com', desc: '아이콘·일러스트·사진·3D를 스타일별로 제공하는 대형 사이트.', cat: 'asset', tags: ['무료', '유료'] },
  { name: 'Iconoir', url: 'https://iconoir.com', desc: '1,600개 이상의 오픈소스 선 아이콘.', cat: 'asset', tags: ['무료'] },
  { name: 'Pixabay', url: 'https://pixabay.com', desc: '무료 사진·일러스트·벡터·영상·음악.', cat: 'asset', tags: ['무료'] },
  { name: 'Creative Market', url: 'https://creativemarket.com', desc: '폰트·그래픽·템플릿·목업을 개별 구매하는 마켓.', cat: 'asset', tags: ['유료'] },
  { name: 'Envato Elements', url: 'https://elements.envato.com', desc: '구독 하나로 템플릿·폰트·영상·음악을 무제한 사용.', cat: 'asset', tags: ['유료'] },
  { name: 'Craftwork', url: 'https://craftwork.design', desc: '일러스트·UI 킷·3D 에셋 번들.', cat: 'asset', tags: ['무료', '유료'] },

  { name: 'Bootstrap', url: 'https://getbootstrap.com', desc: '가장 오래 쓰인 CSS 프레임워크. 반응형 그리드와 컴포넌트.', cat: 'dev', tags: ['무료'] },
  { name: 'Frontend Mentor', url: 'https://www.frontendmentor.io', desc: '디자인 시안을 코드로 구현하며 배우는 실습 플랫폼.', cat: 'dev', tags: ['무료', '유료'] },
  { name: 'Uiverse', url: 'https://uiverse.io', desc: '커뮤니티가 만든 오픈소스 CSS 버튼·로더·카드 모음.', cat: 'dev', tags: ['무료'] },

  { name: 'Sketch', url: 'https://www.sketch.com', desc: '맥 전용 UI 디자인 툴. Figma 이전의 표준.', cat: 'tool', tags: ['유료'] },
  { name: 'Penpot', url: 'https://penpot.app', desc: '오픈소스 디자인·프로토타이핑 툴. Figma의 무료 대안.', cat: 'tool', tags: ['무료'] },
  { name: 'Jitter', url: 'https://jitter.video', desc: '브라우저에서 쓰는 간편한 모션·애니메이션 디자인 툴. Figma 연동.', cat: 'tool', tags: ['무료', '유료'] },
  { name: 'Loom', url: 'https://www.loom.com', desc: '화면 녹화로 디자인 설명 영상을 빠르게 공유.', cat: 'tool', tags: ['무료', '유료'] },

  { name: 'Glassdoor', url: 'https://www.glassdoor.com', desc: '글로벌 기업 리뷰·연봉·채용 정보.', cat: 'job', tags: [] },
  { name: 'Wellfound', url: 'https://wellfound.com', desc: '스타트업 채용 플랫폼(구 AngelList Talent).', cat: 'job', tags: [] },

  { name: 'Dense Discovery', url: 'https://www.densediscovery.com', desc: '디자인·테크·문화를 다루는 주간 뉴스레터.', cat: 'community', tags: ['무료'] },
  { name: '퍼블리', url: 'https://publy.co', desc: '실무자 인사이트 아티클 구독 서비스.', cat: 'community', tags: ['한국', '유료'] },
];

/* =========================================================
   스타일 사전 — 유명 그래픽 디자인 양식 / 흐름
   { name, en, era, desc, traits, people?, q(핀터레스트 검색어), wiki?, img?, imgTitle? }
   img 는 위키미디어 공용(퍼블릭 도메인/CC) 이미지 주소, imgTitle 은 출처 표기
   ========================================================= */
const STYLES = [
  { name: '아르누보', en: 'Art Nouveau', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Alfons_Mucha_-_The_Four_Seasons_-_Autumn%2C_1896.jpg/500px-Alfons_Mucha_-_The_Four_Seasons_-_Autumn%2C_1896.jpg', imgTitle: 'Alfons Mucha - The Four Seasons - Autumn, 1896.jpg (Wikimedia Commons, Public domain)', era: '1890–1910', desc: '자연에서 가져온 유기적 곡선과 식물 모티프, 장식적인 손글씨 레터링. 포스터 예술의 출발점.', traits: '유기적 곡선 · 식물 문양 · 장식 레터링 · 파스텔 톤', people: '알폰스 무하, 오브리 비어즐리', q: 'art nouveau poster', wiki: 'https://en.wikipedia.org/wiki/Art_Nouveau' },
  { name: '다다', en: 'Dada', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Theo_van_Doesburg_224.jpg/500px-Theo_van_Doesburg_224.jpg', imgTitle: 'Theo van Doesburg 224.jpg (Wikimedia Commons, Public domain)', era: '1916–1924', desc: '전쟁에 대한 반발로 태어난 반(反)예술 운동. 무작위 타이포와 포토몽타주로 질서를 조롱했다.', traits: '콜라주 · 포토몽타주 · 뒤섞인 활자 · 우연성', people: '한나 회흐, 쿠르트 슈비터스', q: 'dada collage typography', wiki: 'https://en.wikipedia.org/wiki/Dada' },
  { name: '구성주의', en: 'Constructivism', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Beat_the_Whites_with_the_Red_Wedge.jpg/500px-Beat_the_Whites_with_the_Red_Wedge.jpg', imgTitle: 'Beat the Whites with the Red Wedge.jpg (Wikimedia Commons, Public domain)', era: '1915–1930s', desc: '러시아 혁명기의 선전 그래픽. 사선 구도와 빨강·검정, 사진 몽타주로 강한 메시지를 전달.', traits: '사선 구도 · 빨강/검정 · 포토몽타주 · 기하 도형', people: '엘 리시츠키, 알렉산더 로드첸코', q: 'russian constructivism poster', wiki: 'https://en.wikipedia.org/wiki/Constructivism_(art)' },
  { name: '데 스틸', en: 'De Stijl', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Composition_with_Red%2C_Yellow%2C_Black%2C_Blue_and_Grey_by_Piet_Mondrian%2C_1921.jpg/500px-Composition_with_Red%2C_Yellow%2C_Black%2C_Blue_and_Grey_by_Piet_Mondrian%2C_1921.jpg', imgTitle: 'Composition with Red, Yellow, Black, Blue and Grey by Piet Mondrian, 1921.jpg (Wikimedia Commons, Public domain)', era: '1917–1931', desc: '수직·수평선과 삼원색만으로 이루어진 네덜란드의 추상 양식. 오늘날 그리드 시스템의 뿌리.', traits: '수직/수평선 · 빨강·파랑·노랑 · 비대칭 격자', people: '피트 몬드리안, 테오 반 두스뷔르흐', q: 'de stijl design', wiki: 'https://en.wikipedia.org/wiki/De_Stijl' },
  { name: '바우하우스', en: 'Bauhaus', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Postkarte_Bauhaus_Oskar_Schlemmer_Postkarte_f%C3%BCr_die_Bauhaus-Ausstellung.jpg/500px-Postkarte_Bauhaus_Oskar_Schlemmer_Postkarte_f%C3%BCr_die_Bauhaus-Ausstellung.jpg', imgTitle: 'Postkarte Bauhaus Oskar Schlemmer Postkarte für die Bauhaus-Ausstellung.jpg (Wikimedia Commons, Public domain)', era: '1919–1933', desc: '독일의 디자인 학교이자 사상. 형태는 기능을 따른다는 원칙 아래 기하 형태와 산세리프를 정착시켰다.', traits: '원·삼각·사각 · 원색 · 산세리프 · 기능주의', people: '헤르베르트 바이어, 라슬로 모호이너지, 얀 치홀트', q: 'bauhaus poster design', wiki: 'https://en.wikipedia.org/wiki/Bauhaus' },
  { name: '아르데코', en: 'Art Deco', era: '1920s–1930s', desc: '기계 시대의 화려함. 대칭적인 기하 장식과 금속 광택, 수직으로 뻗은 형태로 고급스러움을 표현.', traits: '대칭 · 부채꼴/지그재그 · 금색·검정 · 수직 강조', people: 'A. M. 카상드르', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Chrysler_Building_spire%2C_Manhattan%2C_by_Carol_Highsmith_%28LOC_highsm.04444%29.jpg/500px-Chrysler_Building_spire%2C_Manhattan%2C_by_Carol_Highsmith_%28LOC_highsm.04444%29.jpg', imgTitle: 'Chrysler Building spire, Manhattan, by Carol Highsmith (LOC highsm.04444).jpg (Wikimedia Commons, Public domain)', q: 'art deco poster', wiki: 'https://en.wikipedia.org/wiki/Art_Deco' },
  { name: '미드센추리 모던', en: 'Mid-century Modern', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Anatomia_di_un_omicidio_-_Poster.jpg/500px-Anatomia_di_un_omicidio_-_Poster.jpg', imgTitle: 'Anatomia di un omicidio - Poster.jpg (Wikimedia Commons, Public domain)', era: '1945–1965', desc: '전후 미국의 낙관주의. 단순한 형태와 따뜻한 팔레트, 유머 있는 일러스트로 기업 아이덴티티의 황금기를 열었다.', traits: '단순 형태 · 머스터드·올리브·오렌지 · 위트 있는 일러스트', people: '폴 랜드, 솔 바스, 알렉산더 지라드', q: 'mid century modern graphic design', wiki: 'https://en.wikipedia.org/wiki/Mid-century_modern' },
  { name: '스위스 스타일', en: 'International Typographic Style', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Kunsthalle_Basel_Gubler_Zurkinden_1959.jpg/500px-Kunsthalle_Basel_Gubler_Zurkinden_1959.jpg', imgTitle: 'Kunsthalle Basel Gubler Zurkinden 1959.jpg (Wikimedia Commons, Public domain)', era: '1950s–', desc: '그리드, 헬베티카, 비대칭 좌측 정렬, 객관적 사진. 현대 그래픽 디자인과 UI 레이아웃의 기본 문법.', traits: '그리드 시스템 · 헬베티카/악치덴츠 · 좌측 정렬 · 여백', people: '요제프 뮐러브로크만, 아민 호프만, 에밀 루더', q: 'swiss style poster design', wiki: 'https://en.wikipedia.org/wiki/International_Typographic_Style' },
  { name: '팝아트', en: 'Pop Art', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg/500px-Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg', imgTitle: 'Campbell’s Soup Cans by Andy Warhol.jpg (Wikimedia Commons, Public domain)', era: '1955–1970', desc: '대중문화와 광고 이미지를 예술로 끌어올린 운동. 망점과 원색, 반복이 특징.', traits: '망점(하프톤) · 원색 · 만화 컷 · 반복', people: '앤디 워홀, 로이 리히텐슈타인', q: 'pop art graphic design', wiki: 'https://en.wikipedia.org/wiki/Pop_art' },
  { name: '사이키델릭', en: 'Psychedelic', era: '1966–1972', desc: '록 콘서트 포스터에서 시작된 환각적 스타일. 형광 보색과 흐르는 레터링이 아르누보를 재해석했다.', traits: '형광 보색 · 녹아내리는 레터링 · 소용돌이 · 낮은 가독성', people: '웨스 윌슨, 빅터 모스코소', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Psychedelic_trance_culture_of_Kazantip_%282006-08-007%29_%28324324207%29.jpg/500px-Psychedelic_trance_culture_of_Kazantip_%282006-08-007%29_%28324324207%29.jpg', imgTitle: 'Psychedelic trance culture of Kazantip (2006-08-007) (324324207).jpg (Wikimedia Commons, CC BY 2.0)', q: 'psychedelic poster 60s', wiki: 'https://en.wikipedia.org/wiki/Psychedelic_art' },
  { name: '펑크', en: 'Punk', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/1970s_fanzines_%2821224199545%29.jpg/500px-1970s_fanzines_%2821224199545%29.jpg', imgTitle: '1970s fanzines (21224199545).jpg (Wikimedia Commons, CC BY 2.0)', era: '1975–1980s', desc: '직접 만들고 복사기로 찍어낸 DIY 미학. 신문에서 오려 붙인 레터링과 거친 콜라주.', traits: '오려 붙인 활자 · 복사기 질감 · 안전핀 · 흑백+빨강', people: '제이미 리드', q: 'punk poster collage design', wiki: 'https://en.wikipedia.org/wiki/Punk_visual_art' },
  { name: '뉴 웨이브 / 스위스 펑크', en: 'New Wave', era: '1970s–1980s', desc: '스위스 그리드를 일부러 깨뜨린 실험. 계단식 활자 배열, 자간 변주, 굵기 대비로 리듬을 만든다.', traits: '깨진 그리드 · 계단식 타이포 · 굵기·크기 대비 · 콜라주', people: '볼프강 바인가르트, 에이프릴 그레이먼', q: 'wolfgang weingart new wave typography', wiki: 'https://en.wikipedia.org/wiki/New_Wave_(design)' },
  { name: '멤피스', en: 'Memphis', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Ettore_sottsass_per_memphis%2C_libreria_carlton%2C_1981.jpg/500px-Ettore_sottsass_per_memphis%2C_libreria_carlton%2C_1981.jpg', imgTitle: 'Ettore sottsass per memphis, libreria carlton, 1981.jpg (Wikimedia Commons, CC BY-SA 4.0)', era: '1981–1988', desc: '이탈리아 디자인 그룹 멤피스의 유희적 스타일. 파스텔과 원색의 충돌, 테라조 패턴, 기하 도형.', traits: '테라조·물결 패턴 · 파스텔+원색 · 기하 도형 · 유머', people: '에토레 소트사스, 나탈리 뒤 파스키에', q: 'memphis design pattern', wiki: 'https://en.wikipedia.org/wiki/Memphis_Group' },
  { name: '그런지', en: 'Grunge', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/41_Grunge_style_urban_wall_background_-_dirty_peeled_posters_on_rusty_metal_gate.jpg/500px-41_Grunge_style_urban_wall_background_-_dirty_peeled_posters_on_rusty_metal_gate.jpg', imgTitle: '41 Grunge style urban wall background - dirty peeled posters on rusty metal gate.jpg (Wikimedia Commons, CC BY 3.0)', era: '1990s', desc: '가독성보다 감정을 우선한 타이포그래피. 겹치고 부서진 글자와 지저분한 텍스처.', traits: '겹친 활자 · 얼룩·긁힘 텍스처 · 왜곡 · 저채도', people: '데이비드 카슨(Ray Gun)', q: 'david carson grunge typography', wiki: 'https://en.wikipedia.org/wiki/Grunge_typography' },
  { name: '레트로 퓨처리즘', en: 'Retrofuturism', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/General_Motors_Building%2C_1939_NY_World%27s_Fair_4_of_10_%288570424156%29.jpg/500px-General_Motors_Building%2C_1939_NY_World%27s_Fair_4_of_10_%288570424156%29.jpg', imgTitle: 'General Motors Building, 1939 NY World’s Fair 4 of 10 (8570424156).jpg (Wikimedia Commons, CC BY 2.0)', era: '1950s–60s / 재유행', desc: '과거가 상상했던 미래. 우주 시대의 유선형과 크롬, 둥근 형태를 향수 어린 시선으로 재현.', traits: '유선형 · 크롬 · 우주 모티프 · 둥근 산세리프', q: 'retro futurism poster', wiki: 'https://en.wikipedia.org/wiki/Retrofuturism' },
  { name: 'Y2K', en: 'Y2K Aesthetic', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Imac_G3_Blue_Dalmatian_3q_back.jpg/500px-Imac_G3_Blue_Dalmatian_3q_back.jpg', imgTitle: 'Imac G3 Blue Dalmatian 3q back.jpg (Wikimedia Commons, CC BY-SA 4.0)', era: '1997–2004 / 2020s 재유행', desc: '밀레니엄 전후의 기술 낙관주의. 크롬과 홀로그램, 버블 형태, 투명 플라스틱 질감.', traits: '크롬 · 홀로그램 · 버블 폰트 · 투명 플라스틱 · 은색', people: '더 디자이너스 리퍼블릭', q: 'y2k graphic design', wiki: 'https://en.wikipedia.org/wiki/Y2K_aesthetic' },
  { name: '프루티거 에어로', en: 'Frutiger Aero', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Frutiger_Aero_%282%29.jpg/500px-Frutiger_Aero_%282%29.jpg', imgTitle: 'Frutiger Aero (2).jpg (Wikimedia Commons, CC0)', era: '2004–2013', desc: 'Windows Vista·초기 iPhone 시대의 광택 UI. 유리 질감과 물방울, 자연 이미지, 투명한 파랑.', traits: '광택 유리 · 물방울·풀잎 · 파랑/초록 · 프루티거 서체', q: 'frutiger aero design', wiki: 'https://en.wikipedia.org/wiki/Frutiger_Aero' },
  { name: '스큐어모피즘', en: 'Skeuomorphism', era: '2007–2013', desc: '실물의 질감을 그대로 모사한 UI. 가죽 노트, 나무 책장, 종이 찢김 등. iOS 6까지의 애플 스타일.', traits: '실물 질감 · 그림자·하이라이트 · 가죽·종이 · 입체 버튼', q: 'skeuomorphism ui design', wiki: 'https://en.wikipedia.org/wiki/Skeuomorph' },
  { name: '플랫 디자인', en: 'Flat Design', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Laptop-coffee-flat-design-by-david-mendoza.png/500px-Laptop-coffee-flat-design-by-david-mendoza.png', imgTitle: 'Laptop-coffee-flat-design-by-david-mendoza.png (Wikimedia Commons, CC BY-SA 4.0)', era: '2012–', desc: '그림자와 질감을 걷어낸 2차원 UI. Windows 8과 iOS 7이 대중화했고, 이후 모든 UI의 기본이 됐다.', traits: '단색 · 그림자 없음 · 단순 아이콘 · 굵은 타이포', q: 'flat design ui', wiki: 'https://en.wikipedia.org/wiki/Flat_design' },
  { name: '머티리얼 디자인', en: 'Material Design', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Android_Lollipop.jpeg/500px-Android_Lollipop.jpeg', imgTitle: 'Android Lollipop.jpeg (Wikimedia Commons, CC BY-SA 4.0)', era: '2014–', desc: '구글의 디자인 언어. 종이와 잉크의 은유, 층을 표현하는 그림자, 의미 있는 모션.', traits: '종이 레이어 · 그림자 깊이 · 플로팅 버튼 · 반응형 모션', q: 'material design ui', wiki: 'https://en.wikipedia.org/wiki/Material_Design' },
  { name: '브루탈리즘', en: 'Brutalism (Web)', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Brutalist_Wall_-_geograph.org.uk_-_6519634.jpg/500px-Brutalist_Wall_-_geograph.org.uk_-_6519634.jpg', imgTitle: 'Brutalist Wall - geograph.org.uk - 6519634.jpg (Wikimedia Commons, CC BY-SA 2.0)', era: '2014–', desc: '꾸미지 않은 날것의 웹. 시스템 폰트, 기본 HTML 느낌, 비대칭과 거친 대비로 세련된 무심함을 연출.', traits: '시스템 폰트 · 검정 테두리 · 비대칭 · 마키·기본 링크', q: 'brutalist web design' },
  { name: '바포웨이브', en: 'Vaporwave', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Vaporwave_sunset.jpg/500px-Vaporwave_sunset.jpg', imgTitle: 'Vaporwave sunset.jpg (Wikimedia Commons, Public domain)', era: '2010s', desc: '인터넷 서브컬처에서 태어난 향수 미학. 고전 조각상, 파스텔 핑크·시안, 격자, 일본어 텍스트.', traits: '핑크·시안 그라디언트 · 조각상 · 격자 · 글리치 · 일본어', q: 'vaporwave aesthetic design', wiki: 'https://en.wikipedia.org/wiki/Vaporwave' },
  { name: '미니멀리즘', en: 'Minimalism', era: '상시', desc: '본질만 남기는 태도. 넓은 여백, 제한된 팔레트, 절제된 타이포로 콘텐츠 자체를 드러낸다.', traits: '여백 · 흑백/단색 · 한 가지 서체 · 정제된 그리드', q: 'minimalist graphic design', wiki: 'https://en.wikipedia.org/wiki/Minimalism' },
  { name: '코퍼레이트 멤피스', en: 'Corporate Memphis', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Corporate_Memphis_%282019%29.png/500px-Corporate_Memphis_%282019%29.png', imgTitle: 'Corporate Memphis (2019).png (Wikimedia Commons, CC BY 4.0)', era: '2017–2022', desc: '빅테크 일러스트의 정형. 긴 팔다리의 평면 인물, 파스텔, 친근하지만 몰개성하다는 비판도.', traits: '긴 팔다리 인물 · 파스텔 · 평면 일러스트 · 둥근 형태', people: '페이스북 Alegria', q: 'corporate memphis illustration', wiki: 'https://en.wikipedia.org/wiki/Corporate_Memphis' },
  { name: '뉴모피즘', en: 'Neumorphism', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Neumorphism-fixed.jpg/500px-Neumorphism-fixed.jpg', imgTitle: 'Neumorphism-fixed.jpg (Wikimedia Commons, CC BY-SA 4.0)', era: '2020', desc: '배경과 같은 색의 요소가 부드럽게 돌출·함몰된 듯한 UI. 예쁘지만 대비가 낮아 실무 적용은 제한적.', traits: '이중 그림자 · 단색 배경 · 부드러운 돌출 · 낮은 대비', q: 'neumorphism ui', wiki: 'https://en.wikipedia.org/wiki/Neumorphism' },
  { name: '글래스모피즘', en: 'Glassmorphism', era: '2020–', desc: '반투명 블러와 얇은 흰 테두리로 유리를 표현하는 UI. 2025년 애플 리퀴드 글래스로 다시 주류가 됐다.', traits: '배경 블러 · 반투명 · 얇은 테두리 · 층 구조', q: 'glassmorphism ui design', wiki: 'https://en.wikipedia.org/wiki/Glassmorphism' },
  { name: '에이시드 그래픽', en: 'Acid Graphics', era: '2018–', desc: '레이브·클럽 문화에서 온 스타일. 액체 크롬 타이포, 형광색, 왜곡과 노이즈.', traits: '액체 크롬 · 형광 초록/보라 · 왜곡 타이포 · 노이즈', q: 'acid graphics design' },
  { name: '리소그래프', en: 'Risograph', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Impress%C3%A3o_em_risografia_em_dua_cores%2C_2014.jpg/500px-Impress%C3%A3o_em_risografia_em_dua_cores%2C_2014.jpg', imgTitle: 'Impressão em risografia em dua cores, 2014.jpg (Wikimedia Commons, CC BY 2.0)', era: '1980s 인쇄기 / 2010s 재유행', desc: '리소 인쇄기의 특성을 살린 스타일. 형광 잉크의 겹침, 거친 입자, 살짝 어긋난 판.', traits: '형광 잉크 겹침 · 거친 입자 · 판 어긋남 · 2~3도 인쇄', q: 'risograph print design', wiki: 'https://en.wikipedia.org/wiki/Risograph' },
  { name: '콜라주 / 스크랩북', en: 'Collage', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Hannah_H%C3%B6ch_with_dada_doll.jpg/500px-Hannah_H%C3%B6ch_with_dada_doll.jpg', imgTitle: 'Hannah Höch with dada doll.jpg (Wikimedia Commons, Public domain)', era: '상시', desc: '오려 붙인 사진과 종이, 테이프, 손글씨를 섞는 믹스드 미디어. 디지털 시대에 손맛으로 재유행.', traits: '오린 사진 · 마스킹 테이프 · 손글씨 · 종이 질감', q: 'collage graphic design', wiki: 'https://en.wikipedia.org/wiki/Collage' },
  { name: '맥시멀리즘', en: 'Maximalism', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Ornate_Bedchamber_Detail_at_Pena_Palace_%2854935407340%29.jpg/500px-Ornate_Bedchamber_Detail_at_Pena_Palace_%2854935407340%29.jpg', imgTitle: 'Ornate Bedchamber Detail at Pena Palace (54935407340).jpg (Wikimedia Commons, CC BY 4.0)', era: '2020s', desc: '많을수록 좋다. 과잉 장식과 패턴 충돌, 여러 서체의 혼용으로 에너지를 만든다.', traits: '패턴 충돌 · 다서체 · 고채도 · 빽빽한 레이아웃', q: 'maximalist graphic design', wiki: 'https://en.wikipedia.org/wiki/Maximalism' },
  { name: '픽셀 아트 / 8비트', en: 'Pixel Art', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Upscaled_pixel_art_of_a_city_at_night.png/500px-Upscaled_pixel_art_of_a_city_at_night.png', imgTitle: 'Upscaled pixel art of a city at night.png (Wikimedia Commons, CC0)', era: '1980s / 재유행', desc: '저해상도 격자와 제한된 팔레트. 레트로 게임 향수를 타고 브랜딩과 UI에 다시 등장.', traits: '픽셀 격자 · 제한 팔레트 · 비트맵 폰트 · 계단 현상', q: 'pixel art graphic design', wiki: 'https://en.wikipedia.org/wiki/Pixel_art' },
  { name: '사이버펑크', en: 'Cyberpunk', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/595421639_megacity_advertising_people_crowds_flying_cars_cyberpunk_neon_light_tone_androids.png/500px-595421639_megacity_advertising_people_crowds_flying_cars_cyberpunk_neon_light_tone_androids.png', imgTitle: '595421639 megacity advertising people crowds flying cars cyberpunk neon light tone androids.png (Wikimedia Commons, Public domain)', era: '1980s–', desc: '네온 도시와 디스토피아. 글리치, 홀로그램, 일본어·기술 텍스트가 겹치는 하이테크 로우라이프.', traits: '네온 핑크/시안 · 글리치 · 스캔라인 · 기술 텍스트', q: 'cyberpunk graphic design', wiki: 'https://en.wikipedia.org/wiki/Cyberpunk' },
  { name: '일본 모던 그래픽', en: 'Japanese Modern', img: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Tokyo_1964_%28184023408%29.jpg/500px-Tokyo_1964_%28184023408%29.jpg', imgTitle: 'Tokyo 1964 (184023408).jpg (Wikimedia Commons, CC BY-SA 2.0)', era: '1960s–', desc: '전통 문양과 여백의 미를 현대 그래픽으로 번역. 절제된 형태와 대담한 색면.', traits: '여백 · 세로 조판 · 전통 문양 재해석 · 대담한 색면', people: '다나카 잇코, 요코오 다다노리, 사토 가시와', q: 'japanese graphic design poster' },
  { name: '안티 디자인 / 뉴 어글리', en: 'Anti-design', era: '2019–', desc: '의도적으로 어색하고 못생기게. 기본 서체, 클립아트, 눈부신 색으로 세련됨에 반기를 든다.', traits: '기본 서체 · 클립아트 · 충돌하는 색 · 어긋난 정렬', q: 'anti design ugly graphic design' },
];

/* =========================================================
   2026 트렌드 키워드
   업계 트렌드 리포트(Pantone, Behance, Adobe, Pinterest 등)와
   커뮤니티에서 반복 언급되는 흐름을 정리. 해마다 갱신하세요.
   { name, area, desc, q(핀터레스트 검색어), link? }
   ========================================================= */
const TRENDS = [
  { name: '리퀴드 글래스', area: 'UI', desc: '2025년 애플이 발표한 새 디자인 언어. 굴절·반사가 있는 유리 질감이 앱과 웹 UI 전반으로 번지는 중.', q: 'liquid glass ui design', link: 'https://en.wikipedia.org/wiki/Liquid_Glass' },
  { name: '클라우드 댄서 (팬톤 2026)', area: '컬러', desc: '팬톤이 2026 올해의 컬러로 고른 부드러운 흰색. 오프화이트와 저채도 미니멀 팔레트가 다시 힘을 얻는다.', q: 'off white minimal branding', link: 'https://www.pantone.com/color-of-the-year/2026' },
  { name: 'AI 비주얼 vs 손맛 회귀', area: '그래픽', desc: 'AI 생성 이미지가 흔해질수록 손그림, 아날로그 텍스처, 불완전함이 오히려 차별점이 된다.', q: 'hand drawn analog texture branding' },
  { name: '익스프레시브 타이포', area: '타이포', desc: '초대형 글자, 가변 폰트, 움직이는 키네틱 타입. 서체 자체가 비주얼의 주인공.', q: 'expressive typography kinetic type' },
  { name: '네오 브루탈리즘', area: 'UI/웹', desc: '굵은 검정 테두리, 딱딱한 그림자, 원색 블록. 플랫한 SaaS UI에 대한 반동으로 확산.', q: 'neo brutalism ui design' },
  { name: '픽셀 · 로우파이 노스탤지어', area: '그래픽', desc: '8비트 픽셀, 비트맵 폰트, 초기 인터넷 감성. Z세대의 레트로가 90년대·2000년대로 이동.', q: 'pixel lo-fi retro design 2026' },
  { name: '벤토 그리드', area: 'UI/웹', desc: '도시락 칸처럼 크기가 다른 카드를 촘촘히 배치하는 레이아웃. 랜딩페이지와 대시보드의 표준이 됐다.', q: 'bento grid layout design' },
  { name: '크롬 · 메탈릭', area: '그래픽', desc: 'Y2K에서 이어진 액체 금속과 크롬 타이포가 3D와 결합해 더 정교해짐.', q: 'chrome metallic typography 3d' },
  { name: '도파민 컬러', area: '컬러', desc: '기분을 끌어올리는 고채도 팔레트. 미니멀 흰색 트렌드와 정반대에서 공존.', q: 'dopamine color palette design' },
  { name: '콜라주 · 스티커 · 스크랩북', area: '그래픽', desc: '오려 붙인 사진, 마스킹 테이프, 손글씨. SNS 콘텐츠와 브랜딩에서 손맛의 대표 주자.', q: 'scrapbook sticker collage design' },
  { name: '세리프 리바이벌 · 에디토리얼', area: '타이포', desc: '잡지 같은 세리프 헤드라인과 여백 많은 편집 레이아웃. 프리미엄·라이프스타일 브랜드가 선호.', q: 'editorial serif typography branding' },
  { name: '촉감 있는 3D', area: '그래픽/UI', desc: '클레이, 인플레이트, 부드러운 렌더링 오브젝트. 아이콘과 히어로 비주얼에 입체감을 더한다.', q: 'inflated 3d clay render design' },
  { name: '프린트 · 리소 텍스처', area: '그래픽', desc: '입자, 잉크 번짐, 인쇄 오차를 디지털에서 재현. 리소그래프와 오프셋의 질감.', q: 'risograph grain texture poster' },
  { name: '오라 · 블러 그라디언트', area: 'UI/그래픽', desc: '흐릿하게 번지는 빛 덩어리 배경. AI 제품 브랜딩에서 특히 많이 쓰인다.', q: 'aura blur gradient background design' },
  { name: '모션 우선 인터페이스', area: 'UI/웹', desc: '스크롤텔링, 마이크로 인터랙션, 페이지 전환 애니메이션이 정적 레이아웃보다 우선되는 설계.', q: 'motion design website interaction 2026' },
];

const TREND_SOURCES = [
  { name: 'Pantone Color of the Year 2026', url: 'https://www.pantone.com/color-of-the-year/2026', desc: '팬톤 올해의 컬러 공식 페이지' },
  { name: 'Behance Trends', url: 'https://www.behance.net/trends', desc: '비핸스 큐레이션 트렌드 갤러리' },
  { name: 'Pinterest Predicts', url: 'https://business.pinterest.com/pinterest-predicts/', desc: '핀터레스트 검색 데이터 기반 연간 트렌드 리포트' },
];

/* =========================================================
   용어 사전 — 디자인 · 편집/인쇄 · UI/UX 구축 시 자주 쓰는 용어
   { term, en, group, desc }   group 은 GLOSSARY_GROUPS 의 id
   ========================================================= */
const GLOSSARY_GROUPS = [
  { id: 'typo',  label: '타이포그래피' },
  { id: 'print', label: '편집 · 인쇄' },
  { id: 'color', label: '컬러' },
  { id: 'brand', label: '그래픽 · 브랜딩' },
  { id: 'ui',    label: 'UI 설계' },
  { id: 'ux',    label: 'UX · 리서치' },
  { id: 'dev',   label: '개발 협업' },
];

const GLOSSARY = [
  /* ---- 타이포그래피 ---- */
  { term: '서체 / 폰트', en: 'Typeface / Font', group: 'typo', desc: '서체는 글자의 디자인(예: Pretendard), 폰트는 그 서체의 특정 굵기·스타일 파일(예: Pretendard Bold). 실무에서는 섞어 씁니다.' },
  { term: '세리프 / 산세리프', en: 'Serif / Sans-serif', group: 'typo', desc: '획 끝에 돌기(세리프)가 있으면 세리프(명조 계열), 없으면 산세리프(고딕 계열). 본문 인쇄물은 세리프, 화면 UI는 산세리프가 일반적.' },
  { term: '웨이트', en: 'Weight', group: 'typo', desc: '글자 굵기 단계. Thin(100)부터 Black(900)까지 숫자로 표기하며 UI에서는 보통 Regular·Medium·SemiBold·Bold 4단계 안에서 씁니다.' },
  { term: '가변 폰트', en: 'Variable Font', group: 'typo', desc: '굵기·너비·기울기 등을 파일 하나에서 연속적으로 조절할 수 있는 폰트. 웹에서 파일 수를 줄이고 미세 조정이 가능합니다.' },
  { term: '자간', en: 'Tracking / Letter-spacing', group: 'typo', desc: '글자 사이의 전체적인 간격. 제목은 좁히고(-2~-4%), 작은 대문자나 캡션은 넓히는 것이 관례.' },
  { term: '커닝', en: 'Kerning', group: 'typo', desc: '특정 글자 쌍(AV, To 등) 사이 간격을 개별 조정하는 것. 로고·헤드라인처럼 큰 글자에서 눈에 띕니다.' },
  { term: '행간', en: 'Leading / Line-height', group: 'typo', desc: '줄과 줄 사이 간격. 본문은 글자 크기의 1.5~1.7배, 제목은 1.1~1.3배가 기준. 한글은 영문보다 조금 넉넉하게.' },
  { term: '베이스라인', en: 'Baseline', group: 'typo', desc: '글자가 올라앉는 가상의 기준선. 여러 크기의 글자를 정렬할 때는 베이스라인을 맞춥니다.' },
  { term: '엑스하이트', en: 'x-height', group: 'typo', desc: '소문자 x의 높이. 엑스하이트가 큰 서체는 작은 크기에서도 잘 읽혀 UI 본문에 유리합니다.' },
  { term: '어센더 / 디센더', en: 'Ascender / Descender', group: 'typo', desc: '엑스하이트 위로 올라가는 부분(b, d, h)과 베이스라인 아래로 내려가는 부분(g, p, y).' },
  { term: '합자', en: 'Ligature', group: 'typo', desc: 'fi, fl처럼 두 글자가 붙어 하나로 디자인된 글리프. 세리프 본문에서 자연스러운 흐름을 만듭니다.' },
  { term: '위도우 / 오펀', en: 'Widow / Orphan', group: 'typo', desc: '단락 마지막 줄에 한 단어만 남거나(위도우), 단락 첫 줄이 페이지 끝에 홀로 남는 것(오펀). 편집에서 반드시 잡는 오류.' },
  { term: '리버', en: 'Rivers', group: 'typo', desc: '양끝 정렬에서 단어 간격이 벌어져 세로로 흰 강줄기처럼 보이는 현상. 하이픈이나 자간 조정으로 해결.' },
  { term: '정렬', en: 'Alignment', group: 'typo', desc: '좌·우·가운데·양끝 정렬. 본문은 좌측 정렬(래그드 라이트)이 가장 읽기 편하고, 가운데 정렬은 짧은 문장에만.' },
  { term: '타입 스케일', en: 'Type Scale', group: 'typo', desc: '일정 비율(1.2, 1.25, 1.333 등)로 커지는 글자 크기 체계. 12·14·16·20·24·32처럼 미리 정해 두고 씁니다.' },
  { term: '위계', en: 'Hierarchy', group: 'typo', desc: '크기·굵기·색·간격으로 정보의 중요도 순서를 만드는 것. 한 화면에 3단계 정도면 충분합니다.' },
  { term: '가독성 / 판독성', en: 'Readability / Legibility', group: 'typo', desc: '판독성은 글자 하나가 구분되는 정도, 가독성은 문장이 편하게 읽히는 정도. 서체 선택은 판독성, 조판은 가독성.' },
  { term: '옵티컬 사이즈', en: 'Optical Size', group: 'typo', desc: '본문용·제목용으로 크기에 따라 형태가 다르게 설계된 서체 변형. 제목용은 대비가 강하고 자간이 좁습니다.' },

  /* ---- 편집 · 인쇄 ---- */
  { term: '판형', en: 'Trim Size', group: 'print', desc: '인쇄물의 최종 크기. A4(210×297), 국판(148×210), 신국판(152×225) 등. 판형이 그리드와 여백의 출발점.' },
  { term: '판면', en: 'Type Area', group: 'print', desc: '여백을 제외하고 본문이 놓이는 영역. 판면 비율이 책의 인상을 좌우합니다.' },
  { term: '그리드', en: 'Grid', group: 'print', desc: '페이지를 컬럼과 행으로 나눈 보이지 않는 틀. 요소를 일관되게 배치하고 리듬을 만드는 기준.' },
  { term: '컬럼 / 거터', en: 'Column / Gutter', group: 'print', desc: '컬럼은 그리드의 세로 단, 거터는 컬럼 사이 간격. 웹에서는 12컬럼, 거터 16~24px이 일반적.' },
  { term: '마진', en: 'Margin', group: 'print', desc: '페이지 가장자리 여백. 책은 안쪽(제본 쪽) 여백을 더 넓게 잡습니다.' },
  { term: '블리드 (도련)', en: 'Bleed', group: 'print', desc: '재단 오차를 대비해 이미지를 재단선 밖으로 3mm 더 빼는 것. 도련 없이 넘기면 흰 테두리가 생깁니다.' },
  { term: '재단선 / 트림 마크', en: 'Trim Marks', group: 'print', desc: '인쇄 후 종이를 자를 위치 표시. 인쇄용 PDF 내보낼 때 도련과 함께 포함.' },
  { term: '세이프 존', en: 'Safe Area', group: 'print', desc: '재단선 안쪽 3~5mm. 글자나 중요한 요소는 이 안에 두어야 잘리지 않습니다.' },
  { term: '스프레드 (펼침면)', en: 'Spread', group: 'print', desc: '마주 보는 두 페이지를 하나의 화면으로 보는 단위. 책·브로슈어는 스프레드 기준으로 디자인.' },
  { term: '폴리오', en: 'Folio', group: 'print', desc: '쪽번호. 러닝 헤드(장 제목)와 함께 페이지 상단·하단에 놓입니다.' },
  { term: '캡션 / 풀아웃', en: 'Caption / Pull Quote', group: 'print', desc: '캡션은 이미지 설명 글, 풀아웃은 본문에서 뽑아 크게 강조한 인용문.' },
  { term: 'CMYK / RGB', en: 'CMYK / RGB', group: 'print', desc: '인쇄는 잉크 4색 CMYK, 화면은 빛 3색 RGB. RGB의 형광·채도 높은 색은 인쇄하면 탁해지므로 CMYK로 변환해 확인.' },
  { term: '별색', en: 'Spot Color (Pantone)', group: 'print', desc: 'CMYK 조합이 아니라 미리 조색된 잉크로 찍는 색. 브랜드 컬러·금·형광처럼 정확한 색이 필요할 때.' },
  { term: 'DPI / PPI', en: 'DPI / PPI', group: 'print', desc: '인쇄 해상도. 인쇄물 이미지는 실제 크기 기준 300dpi, 화면은 72~144ppi면 충분.' },
  { term: '리치 블랙', en: 'Rich Black', group: 'print', desc: 'K100만 쓰면 회색빛이 돌아 C·M·Y를 섞어 만든 진한 검정(예: C60 M40 Y40 K100). 작은 글자는 K100만.' },
  { term: '오버프린트 / 트래핑', en: 'Overprint / Trapping', group: 'print', desc: '색판이 어긋나 흰 틈이 생기지 않도록 겹쳐 찍거나(오버프린트) 경계를 살짝 넓히는 것(트래핑). 검정 글자는 보통 오버프린트.' },
  { term: '후가공', en: 'Finishing', group: 'print', desc: '인쇄 뒤 더하는 공정. 박(금·은 호일), 형압(눌러 돋움), 부분 UV(광택), 코팅, 오시(접는 선), 타공 등.' },
  { term: '제본', en: 'Binding', group: 'print', desc: '중철(스테이플, 얇은 책자), 무선(풀로 붙임, 일반 단행본), 양장(하드커버), 사철(실로 꿰맴, 펼침 좋음).' },
  { term: '평량', en: 'Paper Weight (g/㎡)', group: 'print', desc: '종이 두께를 무게로 표시. 명함 300g, 포스터 150~200g, 본문 80~100g 정도.' },
  { term: '교정쇄 / 프루프', en: 'Proof', group: 'print', desc: '본 인쇄 전에 색과 오탈자를 확인하는 견본. 색이 중요하면 반드시 실제 종이로 교정쇄를 봅니다.' },
  { term: '아웃라인 처리', en: 'Create Outlines', group: 'print', desc: '인쇄소에 넘기기 전 글자를 패스(도형)로 변환해 폰트 누락을 막는 것. 원본은 따로 보관.' },
  { term: '터잡기', en: 'Imposition', group: 'print', desc: '접었을 때 순서가 맞도록 한 장의 큰 종이에 페이지를 배치하는 작업. 페이지 수는 보통 4의 배수.' },

  /* ---- 컬러 ---- */
  { term: 'HEX / RGB / HSL', en: 'Color Notation', group: 'color', desc: 'HEX(#5B5BD6)는 웹에서 가장 흔한 표기, HSL은 색상·채도·명도로 다루기 쉬워 팔레트 조정에 편리.' },
  { term: '색상 · 채도 · 명도', en: 'Hue · Saturation · Value', group: 'color', desc: '색상은 빨강·파랑 같은 종류, 채도는 선명한 정도, 명도는 밝은 정도. 세 축을 분리해서 생각하면 조합이 쉬워집니다.' },
  { term: '보색 / 유사색', en: 'Complementary / Analogous', group: 'color', desc: '색상환에서 마주 보는 색은 보색(강한 대비), 이웃한 색은 유사색(조화). 강조는 보색, 배경은 유사색.' },
  { term: '톤온톤 / 톤인톤', en: 'Tone on Tone / Tone in Tone', group: 'color', desc: '같은 색상의 명도 차이로 구성하면 톤온톤, 비슷한 톤의 다른 색상으로 구성하면 톤인톤.' },
  { term: '60-30-10', en: '60-30-10 Rule', group: 'color', desc: '주조색 60%, 보조색 30%, 강조색 10% 비율로 배분하는 원칙. 색이 많아도 균형이 잡힙니다.' },
  { term: '명도 대비', en: 'Contrast Ratio', group: 'color', desc: '글자와 배경의 밝기 차이를 1:1~21:1로 표현. WCAG 기준 본문 4.5:1, 큰 글자 3:1 이상이어야 접근성 통과.' },
  { term: 'WCAG AA / AAA', en: 'WCAG Levels', group: 'color', desc: '웹 접근성 지침의 준수 등급. 대부분의 서비스는 AA(대비 4.5:1)를 목표로 합니다.' },
  { term: '시맨틱 컬러', en: 'Semantic Color', group: 'color', desc: '용도에 이름을 붙인 색. primary, success, warning, error처럼 의미로 정의해 두면 다크 모드 전환이 쉬워집니다.' },
  { term: '컬러 스케일', en: 'Color Scale', group: 'color', desc: '한 색상을 50~950처럼 10단계 명도로 늘어놓은 것. 디자인 시스템의 기본 단위.' },
  { term: '색 공간', en: 'Color Space (sRGB · P3 · OKLCH)', group: 'color', desc: 'sRGB가 웹 표준, Display P3는 더 넓은 색역, OKLCH는 사람 눈에 균일한 최신 표기. 최신 CSS는 셋 다 지원.' },
  { term: '그라디언트', en: 'Gradient', group: 'color', desc: '색이 점진적으로 변하는 것. 색상환에서 가까운 색끼리 섞어야 중간이 탁해지지 않습니다.' },
  { term: '컬러 프로파일', en: 'Color Profile (ICC)', group: 'color', desc: '기기·종이마다 다른 색 재현을 맞추는 설정. 인쇄용 파일은 인쇄소가 지정한 프로파일(예: Japan Color 2001 Coated)로.' },

  /* ---- 그래픽 · 브랜딩 ---- */
  { term: 'CI / BI', en: 'Corporate / Brand Identity', group: 'brand', desc: 'CI는 기업 전체의 아이덴티티, BI는 개별 브랜드·제품의 아이덴티티. 로고, 컬러, 서체, 톤을 포함.' },
  { term: '심볼 / 워드마크 / 로고타입', en: 'Symbol / Wordmark / Logotype', group: 'brand', desc: '심볼은 그림 마크, 워드마크(로고타입)는 글자로 된 로고. 둘을 정해진 규칙으로 조합한 것이 시그니처.' },
  { term: '브랜드 가이드라인', en: 'Brand Guidelines', group: 'brand', desc: '로고 사용 규칙, 최소 크기, 여백, 금지 사례, 컬러·서체·이미지 톤을 정리한 문서. 외주 시 반드시 요청.' },
  { term: '키 비주얼', en: 'Key Visual', group: 'brand', desc: '캠페인이나 브랜드를 대표하는 핵심 이미지. 포스터·배너·SNS로 변주되는 원본.' },
  { term: '무드보드', en: 'Mood Board', group: 'brand', desc: '방향을 잡기 위해 레퍼런스 이미지·색·질감을 모아 놓은 보드. 시안 전에 클라이언트와 합의하는 용도.' },
  { term: '톤앤매너', en: 'Tone & Manner', group: 'brand', desc: '브랜드가 말하고 보이는 방식의 일관성. 색·서체·사진 스타일·문체를 아우르는 분위기.' },
  { term: '그래픽 모티프', en: 'Graphic Motif', group: 'brand', desc: '로고에서 파생돼 반복 사용되는 도형·패턴. 로고 없이도 브랜드를 알아보게 하는 장치.' },
  { term: '시안', en: 'Draft / Comp', group: 'brand', desc: '클라이언트에게 보여 주는 디자인 안. 보통 A·B·C안으로 방향을 나눠 제시하고 하나를 골라 발전.' },
  { term: '룩앤필', en: 'Look & Feel', group: 'brand', desc: '보이는 인상(룩)과 사용 감각(필). "룩앤필을 맞춰 달라"는 기존 톤과 어긋나지 않게 하라는 뜻.' },
  { term: '어플리케이션', en: 'Application', group: 'brand', desc: '아이덴티티를 명함·사인·패키지·웹 등 실제 매체에 적용한 결과물.' },
  { term: '벡터 / 래스터', en: 'Vector / Raster', group: 'brand', desc: '벡터(AI, SVG)는 수식 기반이라 확대해도 깨지지 않고, 래스터(PNG, JPG)는 픽셀 기반. 로고는 반드시 벡터로.' },
  { term: '베지어 곡선 / 패스', en: 'Bézier Curve / Path', group: 'brand', desc: '앵커 포인트와 핸들로 만드는 곡선. 펜 툴의 기본이며 앵커는 적을수록 매끄럽습니다.' },
  { term: '클리핑 마스크', en: 'Clipping Mask', group: 'brand', desc: '위 도형의 모양대로 아래 이미지를 잘라 보이게 하는 기능. 원본을 훼손하지 않아 수정이 쉽습니다.' },
  { term: '블렌딩 모드', en: 'Blending Mode', group: 'brand', desc: '레이어를 겹칠 때 색을 섞는 방식. Multiply(곱하기)는 어둡게, Screen은 밝게, Overlay는 대비를 높입니다.' },
  { term: '목업 (그래픽)', en: 'Mockup', group: 'brand', desc: '디자인을 실제 제품(명함, 간판, 패키지)에 입혀 보여 주는 합성 이미지. 스마트 오브젝트 PSD로 제작.' },
  { term: '아트워크', en: 'Artwork', group: 'brand', desc: '인쇄·제작에 넘기는 최종 데이터. "아트워크 넘겨 주세요"는 완성 파일을 달라는 뜻.' },

  /* ---- UI 설계 ---- */
  { term: '와이어프레임', en: 'Wireframe', group: 'ui', desc: '색·이미지 없이 회색 박스와 선으로 화면 구조와 정보 배치만 잡은 설계도.' },
  { term: '로파이 / 하이파이', en: 'Lo-fi / Hi-fi', group: 'ui', desc: '완성도 단계. 로파이는 손그림·와이어프레임 수준, 하이파이는 실제와 같은 시각 디자인.' },
  { term: '목업 (UI)', en: 'Mockup', group: 'ui', desc: '동작하지 않는 하이파이 정적 화면. 여기에 인터랙션을 붙이면 프로토타입.' },
  { term: '프로토타입', en: 'Prototype', group: 'ui', desc: '클릭·전환이 되는 시뮬레이션. 개발 전에 흐름을 검증하고 사용성 테스트에 씁니다.' },
  { term: '디자인 시스템', en: 'Design System', group: 'ui', desc: '컬러·타이포·간격·컴포넌트와 사용 규칙을 묶은 재사용 체계. 팀이 커질수록 필수.' },
  { term: '컴포넌트', en: 'Component', group: 'ui', desc: '버튼·인풋·카드처럼 반복 사용하는 UI 조각. 원본(마스터)을 고치면 모든 인스턴스가 바뀝니다.' },
  { term: '디자인 토큰', en: 'Design Token', group: 'ui', desc: '색·간격·크기 값을 이름으로 저장한 최소 단위(color-primary, space-4). 디자인과 코드가 같은 값을 공유.' },
  { term: '아토믹 디자인', en: 'Atomic Design', group: 'ui', desc: '원자(버튼) → 분자(검색창) → 유기체(헤더) → 템플릿 → 페이지로 UI를 쌓는 방법론.' },
  { term: '8pt 그리드', en: '8pt Grid', group: 'ui', desc: '간격·크기를 8의 배수(8, 16, 24, 32…)로 통일하는 규칙. 어떤 해상도에서도 깔끔하게 떨어집니다.' },
  { term: '브레이크포인트', en: 'Breakpoint', group: 'ui', desc: '레이아웃이 바뀌는 화면 폭 기준. 보통 모바일 ~640, 태블릿 ~1024, 데스크톱 1280 이상.' },
  { term: '반응형 / 적응형', en: 'Responsive / Adaptive', group: 'ui', desc: '반응형은 폭에 따라 유연하게 흐르고, 적응형은 정해진 몇 가지 폭에 맞춘 고정 레이아웃을 골라 보여 줍니다.' },
  { term: '뷰포트 / 폴드', en: 'Viewport / Fold', group: 'ui', desc: '뷰포트는 화면에 보이는 영역, 폴드는 스크롤 전 보이는 경계. 핵심 메시지와 CTA는 폴드 위에.' },
  { term: '히어로 섹션', en: 'Hero Section', group: 'ui', desc: '랜딩페이지 최상단의 큰 제목·이미지·CTA 영역. 3초 안에 무엇을 하는 서비스인지 전달.' },
  { term: 'CTA', en: 'Call to Action', group: 'ui', desc: '"시작하기", "구매하기"처럼 행동을 유도하는 버튼. 화면당 주요 CTA는 하나만 강조.' },
  { term: 'GNB / LNB', en: 'Global / Local Navigation', group: 'ui', desc: 'GNB는 전체 서비스 공통 메뉴(상단), LNB는 현재 섹션 안의 하위 메뉴(왼쪽). 국내 실무 용어.' },
  { term: '햄버거 메뉴 / 탭 바', en: 'Hamburger / Tab Bar', group: 'ui', desc: '모바일에서 메뉴를 숨기는 ≡ 아이콘과 하단에 항상 노출하는 탭 바. 핵심 기능이 5개 이하면 탭 바가 낫습니다.' },
  { term: '모달 / 다이얼로그', en: 'Modal / Dialog', group: 'ui', desc: '화면 위에 떠서 다른 조작을 막는 창. 남용하면 피로하니 확인이 꼭 필요한 순간에만.' },
  { term: '바텀 시트', en: 'Bottom Sheet', group: 'ui', desc: '모바일 화면 아래에서 올라오는 패널. 모달보다 가볍고 엄지로 닿기 좋습니다.' },
  { term: '토스트 / 스낵바', en: 'Toast / Snackbar', group: 'ui', desc: '"저장되었습니다"처럼 잠깐 떴다 사라지는 알림. 스낵바는 실행 취소 같은 액션이 하나 붙습니다.' },
  { term: '툴팁 / 팝오버', en: 'Tooltip / Popover', group: 'ui', desc: '호버·클릭 시 나오는 짧은 설명(툴팁)과 조금 더 많은 내용을 담은 작은 창(팝오버).' },
  { term: '드롭다운 / 셀렉트', en: 'Dropdown / Select', group: 'ui', desc: '눌렀을 때 목록이 펼쳐지는 컨트롤. 선택지가 5개 이하면 라디오·세그먼트가 더 빠릅니다.' },
  { term: '아코디언', en: 'Accordion', group: 'ui', desc: '제목을 누르면 내용이 펼쳐지고 접히는 목록. FAQ에 주로 사용.' },
  { term: '카드', en: 'Card', group: 'ui', desc: '이미지·제목·설명을 한 덩어리로 묶은 컨테이너. 격자로 늘어놓기 쉽지만 남발하면 복잡해집니다.' },
  { term: '스켈레톤 UI', en: 'Skeleton', group: 'ui', desc: '로딩 중 콘텐츠 자리에 회색 블록을 먼저 보여 주는 것. 스피너보다 체감 속도가 빠릅니다.' },
  { term: '엠프티 스테이트', en: 'Empty State', group: 'ui', desc: '데이터가 없을 때의 화면. 빈 화면 대신 다음 행동을 안내해야 합니다.' },
  { term: '온보딩', en: 'Onboarding', group: 'ui', desc: '첫 사용자가 서비스를 익히는 과정. 튜토리얼, 권한 요청, 초기 설정 화면을 포함.' },
  { term: '마이크로인터랙션', en: 'Microinteraction', group: 'ui', desc: '버튼 눌림, 좋아요 애니메이션 같은 작은 반응. 피드백을 주고 완성도를 높입니다.' },
  { term: '어포던스', en: 'Affordance', group: 'ui', desc: '보기만 해도 어떻게 쓰는지 알 수 있는 성질. 버튼은 눌러 보이고 링크는 밑줄이 있어야 합니다.' },
  { term: '상태', en: 'States (Hover · Active · Focus · Disabled)', group: 'ui', desc: '컴포넌트가 가지는 여러 모습. 기본·호버·눌림·포커스·비활성·로딩·에러를 모두 정의해야 개발 누락이 없습니다.' },
  { term: '오토 레이아웃', en: 'Auto Layout', group: 'ui', desc: 'Figma에서 내용에 따라 크기와 간격이 자동으로 늘어나는 프레임. CSS 플렉스박스와 같은 개념.' },
  { term: '컨스트레인트', en: 'Constraints', group: 'ui', desc: '프레임 크기가 바뀔 때 요소가 어느 쪽에 붙어 따라갈지 정하는 규칙. 반응형 컴포넌트의 기본.' },
  { term: '배리언트', en: 'Variants', group: 'ui', desc: '한 컴포넌트의 여러 버전(크기·상태·타입)을 한 세트로 묶은 것. 속성을 바꿔 가며 선택.' },
  { term: '핸드오프', en: 'Handoff', group: 'ui', desc: '디자인을 개발자에게 넘기는 과정. 스펙(간격·색·폰트), 에셋, 인터랙션 설명이 포함되어야 합니다.' },
  { term: '레드라인 / 스펙', en: 'Redline / Spec', group: 'ui', desc: '간격·크기를 빨간 선과 숫자로 표기한 문서. 요즘은 Figma Dev Mode가 자동으로 대신합니다.' },
  { term: '세이프 에어리어', en: 'Safe Area', group: 'ui', desc: '노치·홈 인디케이터 등 기기 UI에 가려지지 않는 영역. 중요한 요소는 이 안에 배치.' },
  { term: '터치 타깃', en: 'Touch Target', group: 'ui', desc: '손가락으로 누를 수 있는 최소 크기. iOS 44pt, 안드로이드 48dp 이상.' },
  { term: '플레이스홀더 / 밸리데이션', en: 'Placeholder / Validation', group: 'ui', desc: '입력 전 힌트 텍스트와 입력값 검증. 라벨을 플레이스홀더로 대체하면 입력 중 사라져 불편합니다.' },
  { term: '브레드크럼', en: 'Breadcrumb', group: 'ui', desc: '홈 > 카테고리 > 상품처럼 현재 위치 경로를 보여 주는 내비게이션.' },
  { term: '페이지네이션 / 무한 스크롤', en: 'Pagination / Infinite Scroll', group: 'ui', desc: '목록을 페이지로 나누거나 스크롤하면 계속 불러오는 방식. 목적 있는 탐색은 페이지네이션이 낫습니다.' },
  { term: '배지 / 칩', en: 'Badge / Chip', group: 'ui', desc: '배지는 알림 개수·상태를 표시하는 작은 라벨, 칩은 선택·필터·태그로 쓰는 알약 모양 요소.' },
  { term: '캐러셀', en: 'Carousel', group: 'ui', desc: '이미지를 옆으로 넘겨 보는 슬라이드. 자동 재생은 사용자가 대부분 무시하므로 신중히.' },
  { term: '다크 모드', en: 'Dark Mode', group: 'ui', desc: '어두운 배경 테마. 단순 반전이 아니라 순검정 대신 진회색, 채도 낮춘 강조색으로 다시 설계해야 합니다.' },

  /* ---- UX · 리서치 ---- */
  { term: 'UX / UI', en: 'User Experience / User Interface', group: 'ux', desc: 'UI는 보이는 화면과 조작 요소, UX는 서비스를 쓰는 전체 경험. 예쁜 UI가 좋은 UX를 보장하지는 않습니다.' },
  { term: '유저 리서치', en: 'User Research', group: 'ux', desc: '인터뷰·설문·관찰로 사용자의 행동과 니즈를 파악하는 활동. 정성(왜)과 정량(얼마나)으로 나뉩니다.' },
  { term: '페르소나', en: 'Persona', group: 'ux', desc: '리서치를 바탕으로 만든 대표 가상 사용자. 이름·목표·불편을 붙여 팀이 같은 사람을 떠올리게 합니다.' },
  { term: '유저 저니 맵', en: 'User Journey Map', group: 'ux', desc: '사용자가 목표를 이루기까지의 단계별 행동·감정·접점을 시간순으로 그린 지도. 불편 구간을 찾는 도구.' },
  { term: '정보 구조', en: 'Information Architecture (IA)', group: 'ux', desc: '콘텐츠와 기능을 어떻게 나누고 이름 붙이고 연결할지 정하는 설계. 사이트맵이 그 결과물.' },
  { term: '유저 플로우', en: 'User Flow', group: 'ux', desc: '특정 목표(회원가입, 결제)를 위해 거치는 화면과 분기의 흐름도. 와이어프레임 전에 그립니다.' },
  { term: '카드 소팅', en: 'Card Sorting', group: 'ux', desc: '사용자에게 항목 카드를 분류하게 해 메뉴 구조를 정하는 리서치 방법.' },
  { term: '사용성 테스트', en: 'Usability Test', group: 'ux', desc: '실제 사용자에게 과제를 주고 수행 과정을 관찰하는 것. 5명만 해도 주요 문제의 대부분이 드러납니다.' },
  { term: '휴리스틱 평가', en: 'Heuristic Evaluation', group: 'ux', desc: '전문가가 닐슨의 10가지 원칙 같은 기준으로 UI를 점검하는 방법. 테스트보다 빠르고 저렴.' },
  { term: 'A/B 테스트', en: 'A/B Test', group: 'ux', desc: '두 버전을 나눠 보여 주고 지표(클릭·전환)로 우열을 가리는 실험.' },
  { term: '접근성', en: 'Accessibility (a11y)', group: 'ux', desc: '장애·환경에 관계없이 누구나 쓸 수 있게 만드는 것. 대비, 키보드 조작, 대체 텍스트, 스크린 리더 대응.' },
  { term: '인지 부하', en: 'Cognitive Load', group: 'ux', desc: '화면을 이해하는 데 드는 정신적 노력. 선택지·정보·장식을 줄일수록 낮아집니다.' },
  { term: '힉의 법칙', en: "Hick's Law", group: 'ux', desc: '선택지가 많을수록 결정 시간이 길어진다. 메뉴는 줄이고 단계를 나눕니다.' },
  { term: '피츠의 법칙', en: "Fitts's Law", group: 'ux', desc: '목표가 크고 가까울수록 빨리 누를 수 있다. 중요한 버튼은 크게, 엄지 근처에.' },
  { term: '제이콥의 법칙', en: "Jakob's Law", group: 'ux', desc: '사용자는 다른 서비스에서 익힌 방식을 기대한다. 관습을 따르는 것이 대개 옳습니다.' },
  { term: '멘탈 모델', en: 'Mental Model', group: 'ux', desc: '사용자가 머릿속에 가진 "이건 이렇게 동작할 것"이라는 믿음. 여기에 맞추면 설명이 필요 없습니다.' },
  { term: '다크 패턴', en: 'Dark Pattern', group: 'ux', desc: '해지 버튼 숨기기, 기본 체크된 동의처럼 사용자를 속여 이익을 얻는 설계. 규제 대상이 되고 있습니다.' },
  { term: '퍼널 / 전환율', en: 'Funnel / Conversion Rate', group: 'ux', desc: '방문 → 가입 → 결제로 좁아지는 단계(퍼널)와 다음 단계로 넘어간 비율(전환율). 이탈 구간을 찾는 기본 지표.' },
  { term: '리텐션', en: 'Retention', group: 'ux', desc: '사용자가 다시 돌아오는 비율. 신규 유입보다 서비스 건강을 더 잘 보여 줍니다.' },
  { term: 'KPI / OKR', en: 'KPI / OKR', group: 'ux', desc: '성과를 재는 핵심 지표(KPI)와 목표·핵심 결과로 정리한 목표 관리 틀(OKR). 디자인 결정의 근거로 쓰입니다.' },
  { term: 'MVP', en: 'Minimum Viable Product', group: 'ux', desc: '핵심 가치만 담아 가장 빨리 내놓는 최소 제품. 완성도보다 검증 속도가 목적.' },
  { term: '디자인 씽킹 / 더블 다이아몬드', en: 'Design Thinking / Double Diamond', group: 'ux', desc: '공감→정의→아이디어→프로토타입→테스트, 또는 발견→정의→개발→전달로 문제를 넓혔다 좁히는 프로세스 모델.' },
  { term: '애자일 / 스프린트', en: 'Agile / Sprint', group: 'ux', desc: '1~2주 단위(스프린트)로 만들고 배포하고 개선을 반복하는 개발 방식. 디자이너도 스프린트 단위로 일합니다.' },
  { term: '백로그', en: 'Backlog', group: 'ux', desc: '해야 할 일의 우선순위 목록. 디자인 요청도 백로그에 쌓여 스프린트에 배정됩니다.' },
  { term: 'JTBD', en: 'Jobs To Be Done', group: 'ux', desc: '사용자가 제품을 "고용"해 해결하려는 일에 집중하는 관점. "드릴이 아니라 구멍을 원한다".' },
  { term: '히트맵', en: 'Heatmap', group: 'ux', desc: '클릭·스크롤·시선이 몰리는 곳을 색으로 표시한 분석. 폴드 아래 콘텐츠가 얼마나 보이는지 확인.' },

  /* ---- 개발 협업 ---- */
  { term: 'HTML / CSS / JS', en: 'HTML / CSS / JavaScript', group: 'dev', desc: 'HTML은 구조, CSS는 모양, JS는 동작. 디자이너가 CSS를 읽을 수 있으면 핸드오프 대화가 훨씬 정확해집니다.' },
  { term: 'px / rem / em', en: 'CSS Units', group: 'dev', desc: 'px는 고정, rem은 루트 글자 크기 기준(보통 16px=1rem), em은 부모 기준. 접근성을 위해 글자는 rem 권장.' },
  { term: '박스 모델', en: 'Box Model (Margin · Padding · Border)', group: 'dev', desc: '요소는 내용 → 패딩(안쪽 여백) → 보더 → 마진(바깥 여백) 순으로 감싸입니다. Figma의 오토 레이아웃 패딩과 같은 개념.' },
  { term: '플렉스박스 / 그리드', en: 'Flexbox / CSS Grid', group: 'dev', desc: '한 방향 정렬은 플렉스, 행·열 2차원 배치는 그리드. 오토 레이아웃은 플렉스로 번역됩니다.' },
  { term: '미디어 쿼리', en: 'Media Query', group: 'dev', desc: '화면 폭·다크 모드 등 조건에 따라 다른 CSS를 적용하는 문법. 브레이크포인트가 여기서 구현됩니다.' },
  { term: 'SVG / PNG / WebP', en: 'Image Formats', group: 'dev', desc: '아이콘·로고는 SVG, 투명 이미지는 PNG, 사진은 WebP(또는 AVIF)가 가볍습니다. JPG는 점점 WebP로 대체.' },
  { term: '이징', en: 'Easing', group: 'dev', desc: '애니메이션 속도 곡선. ease-out은 빠르게 시작해 부드럽게 멈춰 UI에 가장 자연스럽습니다. 지속 시간은 150~300ms.' },
  { term: 'z-index', en: 'z-index', group: 'dev', desc: '요소가 겹칠 때 위아래 순서. 모달·툴팁·드롭다운의 층 순서를 디자인 시스템에서 미리 정해 둡니다.' },
  { term: '시맨틱 마크업', en: 'Semantic Markup', group: 'dev', desc: '버튼은 button, 제목은 h1~h6처럼 의미에 맞는 태그를 쓰는 것. 접근성과 검색 노출의 기본.' },
  { term: '컴포넌트 라이브러리 / 스토리북', en: 'Component Library / Storybook', group: 'dev', desc: '코드로 구현된 컴포넌트 모음과 그것을 따로 띄워 보는 도구. 디자인 시스템의 개발 쪽 짝.' },
  { term: 'CSS 변수', en: 'CSS Custom Properties', group: 'dev', desc: '--color-primary처럼 값을 이름으로 저장하는 CSS 기능. 디자인 토큰이 코드에서 이 형태가 됩니다.' },
  { term: '웹폰트 / FOUT', en: 'Web Font / FOUT', group: 'dev', desc: '서버에서 내려받는 폰트와, 로딩 전 대체 폰트가 잠깐 보이는 현상. 서브셋 폰트로 용량을 줄여 완화.' },
  { term: '레이지 로딩', en: 'Lazy Loading', group: 'dev', desc: '화면에 보일 때 이미지를 불러오는 기법. 긴 페이지의 초기 속도를 크게 개선.' },
  { term: 'LCP / CLS', en: 'Core Web Vitals', group: 'dev', desc: '구글의 성능 지표. LCP는 큰 콘텐츠가 뜨는 시간, CLS는 로딩 중 레이아웃이 튀는 정도. 이미지 크기를 지정하면 CLS가 줄어듭니다.' },
  { term: 'QA', en: 'Quality Assurance', group: 'dev', desc: '배포 전 오류를 찾는 검수. 디자인 QA는 구현이 시안과 다른 곳(간격, 색, 상태)을 잡아내는 단계.' },
  { term: '스테이징 / 배포', en: 'Staging / Deploy', group: 'dev', desc: '실제 서비스(프로덕션) 전에 검수하는 테스트 서버가 스테이징. "스테이징에 올렸어요"는 확인해 달라는 뜻.' },
  { term: 'Git / PR', en: 'Git / Pull Request', group: 'dev', desc: '코드 변경 이력을 관리하는 도구와, 변경을 합쳐 달라는 요청. 디자인 파일의 브랜치·버전 기능과 같은 개념.' },
  { term: 'API', en: 'Application Programming Interface', group: 'dev', desc: '프로그램끼리 데이터를 주고받는 약속. "API가 아직 없다"는 화면에 넣을 실제 데이터가 준비되지 않았다는 뜻.' },
  { term: 'CMS', en: 'Content Management System', group: 'dev', desc: '개발자 없이 콘텐츠를 올리고 고치는 관리 도구. WordPress, Webflow CMS 등. 템플릿 설계가 디자이너 몫.' },
];
